# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Activation.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Activation(object):
    def setupUi(self, Activation):
        Activation.setObjectName("Activation")
        Activation.resize(262, 142)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Activation.sizePolicy().hasHeightForWidth())
        Activation.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("graphics/icon.xpm"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Activation.setWindowIcon(icon)
        Activation.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.gridLayout = QtWidgets.QGridLayout(Activation)
        self.gridLayout.setObjectName("gridLayout")
        self.save_btn = QtWidgets.QPushButton(Activation)
        self.save_btn.setObjectName("save_btn")
        self.gridLayout.addWidget(self.save_btn, 2, 1, 1, 1)
        self.cancel_btn = QtWidgets.QPushButton(Activation)
        self.cancel_btn.setObjectName("cancel_btn")
        self.gridLayout.addWidget(self.cancel_btn, 2, 2, 1, 1)
        self.code1_input = QtWidgets.QLineEdit(Activation)
        self.code1_input.setObjectName("code1_input")
        self.gridLayout.addWidget(self.code1_input, 0, 1, 1, 2)
        self.code2_input = QtWidgets.QLineEdit(Activation)
        self.code2_input.setObjectName("code2_input")
        self.gridLayout.addWidget(self.code2_input, 1, 1, 1, 2)
        self.label = QtWidgets.QLabel(Activation)
        self.label.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(Activation)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 3, 1, 1)

        self.retranslateUi(Activation)
        QtCore.QMetaObject.connectSlotsByName(Activation)

    def retranslateUi(self, Activation):
        _translate = QtCore.QCoreApplication.translate
        Activation.setWindowTitle(_translate("Activation", "التسجيل"))
        self.save_btn.setText(_translate("Activation", "Activate"))
        self.cancel_btn.setText(_translate("Activation", "Cancel"))
        self.label.setText(_translate("Activation", "Code 1:"))
        self.label_2.setText(_translate("Activation", "Code 2:"))
