# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Add_Maintenance_Operation.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Add_Maintenance_Operation(object):
    def setupUi(self, Add_Maintenance_Operation):
        Add_Maintenance_Operation.setObjectName("Add_Maintenance_Operation")
        Add_Maintenance_Operation.resize(400, 500)
        Add_Maintenance_Operation.setMinimumSize(QtCore.QSize(400, 500))
        Add_Maintenance_Operation.setMaximumSize(QtCore.QSize(400, 500))
        Add_Maintenance_Operation.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.gridLayout = QtWidgets.QGridLayout(Add_Maintenance_Operation)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_5 = QtWidgets.QGroupBox(Add_Maintenance_Operation)
        self.groupBox_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_5.setStyleSheet("QComboBox {\n"
"        background-color: #fafafa;\n"
"        border: 1px solid lightgrey;        \n"
"        height: 22px;\n"
"        color: black;\n"
"    }\n"
"    QComboBox::drop-down {\n"
"        border: none;\n"
"    }")
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.name_input = QtWidgets.QLineEdit(self.groupBox_5)
        self.name_input.setObjectName("name_input")
        self.gridLayout_2.addWidget(self.name_input, 0, 0, 1, 2)
        self.select_account_btn = QtWidgets.QPushButton(self.groupBox_5)
        self.select_account_btn.setObjectName("select_account_btn")
        self.gridLayout_2.addWidget(self.select_account_btn, 1, 0, 1, 1)
        self.account_combobox = QtWidgets.QComboBox(self.groupBox_5)
        self.account_combobox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.account_combobox.setObjectName("account_combobox")
        self.gridLayout_2.addWidget(self.account_combobox, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 3, 1, 1)
        self.select_opposite_account_btn = QtWidgets.QPushButton(self.groupBox_5)
        self.select_opposite_account_btn.setObjectName("select_opposite_account_btn")
        self.gridLayout_2.addWidget(self.select_opposite_account_btn, 2, 0, 1, 1)
        self.opposite_account_combobox = QtWidgets.QComboBox(self.groupBox_5)
        self.opposite_account_combobox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.opposite_account_combobox.setObjectName("opposite_account_combobox")
        self.gridLayout_2.addWidget(self.opposite_account_combobox, 2, 1, 1, 1)
        self.maintenance_type_combobox = QtWidgets.QComboBox(self.groupBox_5)
        self.maintenance_type_combobox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.maintenance_type_combobox.setObjectName("maintenance_type_combobox")
        self.maintenance_type_combobox.addItem("")
        self.maintenance_type_combobox.addItem("")
        self.gridLayout_2.addWidget(self.maintenance_type_combobox, 3, 0, 1, 2)
        self.start_period = QtWidgets.QDateTimeEdit(self.groupBox_5)
        self.start_period.setObjectName("start_period")
        self.gridLayout_2.addWidget(self.start_period, 4, 0, 1, 2)
        self.end_period = QtWidgets.QDateTimeEdit(self.groupBox_5)
        self.end_period.setObjectName("end_period")
        self.gridLayout_2.addWidget(self.end_period, 5, 0, 1, 2)
        self.cost_input = QtWidgets.QLineEdit(self.groupBox_5)
        self.cost_input.setObjectName("cost_input")
        self.gridLayout_2.addWidget(self.cost_input, 6, 0, 1, 2)
        self.notes_input = QtWidgets.QLineEdit(self.groupBox_5)
        self.notes_input.setObjectName("notes_input")
        self.gridLayout_2.addWidget(self.notes_input, 7, 0, 1, 2)
        self.save_btn = QtWidgets.QPushButton(self.groupBox_5)
        self.save_btn.setObjectName("save_btn")
        self.gridLayout_2.addWidget(self.save_btn, 8, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_5)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_5)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_5)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 4, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_5)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 6, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_5)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 7, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_5)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 5, 3, 1, 1)
        self.gridLayout.addWidget(self.groupBox_5, 0, 0, 1, 1)

        self.retranslateUi(Add_Maintenance_Operation)
        QtCore.QMetaObject.connectSlotsByName(Add_Maintenance_Operation)

    def retranslateUi(self, Add_Maintenance_Operation):
        _translate = QtCore.QCoreApplication.translate
        Add_Maintenance_Operation.setWindowTitle(_translate("Add_Maintenance_Operation", "إضافة عملية تصنيع"))
        self.groupBox_5.setTitle(_translate("Add_Maintenance_Operation", "إضافة عملىة تصنيع"))
        self.select_account_btn.setText(_translate("Add_Maintenance_Operation", "...اختيار"))
        self.label_5.setText(_translate("Add_Maintenance_Operation", "الحساب:"))
        self.select_opposite_account_btn.setText(_translate("Add_Maintenance_Operation", "...اختيار"))
        self.maintenance_type_combobox.setItemText(0, _translate("Add_Maintenance_Operation", "دورية"))
        self.maintenance_type_combobox.setItemText(1, _translate("Add_Maintenance_Operation", "طارئة"))
        self.save_btn.setText(_translate("Add_Maintenance_Operation", "حفظ"))
        self.label.setText(_translate("Add_Maintenance_Operation", "الاسم:"))
        self.label_4.setText(_translate("Add_Maintenance_Operation", "الحساب المقابل:"))
        self.label_6.setText(_translate("Add_Maintenance_Operation", "طبيعة العملية:"))
        self.label_10.setText(_translate("Add_Maintenance_Operation", "بداية العملية:"))
        self.label_9.setText(_translate("Add_Maintenance_Operation", "الكلفة:"))
        self.label_8.setText(_translate("Add_Maintenance_Operation", "البيان:"))
        self.label_7.setText(_translate("Add_Maintenance_Operation", "انتهاء العملية:"))
