# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_ApiKeys.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ApiKeys(object):
    def setupUi(self, ApiKeys):
        ApiKeys.setObjectName("ApiKeys")
        ApiKeys.resize(300, 200)
        ApiKeys.setMinimumSize(QtCore.QSize(300, 200))
        ApiKeys.setMaximumSize(QtCore.QSize(300, 200))
        ApiKeys.setLayoutDirection(QtCore.Qt.RightToLeft)
        ApiKeys.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(ApiKeys)
        self.gridLayout.setObjectName("gridLayout")
        self.key_name_input = QtWidgets.QLineEdit(ApiKeys)
        self.key_name_input.setObjectName("key_name_input")
        self.gridLayout.addWidget(self.key_name_input, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(ApiKeys)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.save_btn = QtWidgets.QPushButton(ApiKeys)
        self.save_btn.setObjectName("save_btn")
        self.gridLayout.addWidget(self.save_btn, 5, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(ApiKeys)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.key_value_input = QtWidgets.QLineEdit(ApiKeys)
        self.key_value_input.setObjectName("key_value_input")
        self.gridLayout.addWidget(self.key_value_input, 1, 1, 1, 1)

        self.retranslateUi(ApiKeys)
        QtCore.QMetaObject.connectSlotsByName(ApiKeys)

    def retranslateUi(self, ApiKeys):
        _translate = QtCore.QCoreApplication.translate
        ApiKeys.setWindowTitle(_translate("ApiKeys", "إعدادات الاختصارات"))
        self.label.setText(_translate("ApiKeys", "اسم المفتاح:"))
        self.save_btn.setText(_translate("ApiKeys", "حفظ"))
        self.label_2.setText(_translate("ApiKeys", "المفتاح:"))
