# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_AccountBalance.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AccountBalance(object):
    def setupUi(self, AccountBalance):
        AccountBalance.setObjectName("AccountBalance")
        AccountBalance.setWindowModality(QtCore.Qt.WindowModal)
        AccountBalance.resize(625, 420)
        AccountBalance.setMinimumSize(QtCore.QSize(0, 0))
        AccountBalance.setMaximumSize(QtCore.QSize(1686786, 1686786))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/coin_dollar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AccountBalance.setWindowIcon(icon)
        AccountBalance.setModal(True)
        self.gridLayout_2 = QtWidgets.QGridLayout(AccountBalance)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(161, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 2, 2, 1, 1)
        self.account_details_btn = QtWidgets.QPushButton(AccountBalance)
        self.account_details_btn.setObjectName("account_details_btn")
        self.gridLayout_2.addWidget(self.account_details_btn, 2, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(AccountBalance)
        self.groupBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 5, 1, 1)
        self.curreny_combobox = QtWidgets.QComboBox(self.groupBox)
        self.curreny_combobox.setObjectName("curreny_combobox")
        self.gridLayout.addWidget(self.curreny_combobox, 1, 4, 1, 1)
        self.account_combobox = QtWidgets.QComboBox(self.groupBox)
        self.account_combobox.setEnabled(False)
        self.account_combobox.setStyleSheet("QComboBox {\n"
"        background-color: #fafafa;\n"
"        border: 1px solid lightgrey;        \n"
"        height: 22px;\n"
"        color: black;\n"
"    }\n"
"    QComboBox::drop-down {\n"
"        border: none;\n"
"    }")
        self.account_combobox.setObjectName("account_combobox")
        self.gridLayout.addWidget(self.account_combobox, 1, 1, 1, 1)
        self.select_account_btn = QtWidgets.QPushButton(self.groupBox)
        self.select_account_btn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.select_account_btn.setObjectName("select_account_btn")
        self.gridLayout.addWidget(self.select_account_btn, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 3, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 3)
        self.accounts_table = QtWidgets.QTableWidget(AccountBalance)
        self.accounts_table.setEnabled(True)
        self.accounts_table.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.accounts_table.setMouseTracking(False)
        self.accounts_table.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.accounts_table.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.accounts_table.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.accounts_table.setLineWidth(1)
        self.accounts_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.accounts_table.setDragEnabled(False)
        self.accounts_table.setAlternatingRowColors(True)
        self.accounts_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.accounts_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.accounts_table.setTextElideMode(QtCore.Qt.ElideRight)
        self.accounts_table.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.accounts_table.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.accounts_table.setShowGrid(True)
        self.accounts_table.setObjectName("accounts_table")
        self.accounts_table.setColumnCount(4)
        self.accounts_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.accounts_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.accounts_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.accounts_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.accounts_table.setHorizontalHeaderItem(3, item)
        self.accounts_table.horizontalHeader().setVisible(True)
        self.accounts_table.horizontalHeader().setCascadingSectionResizes(False)
        self.accounts_table.horizontalHeader().setHighlightSections(True)
        self.accounts_table.horizontalHeader().setSortIndicatorShown(True)
        self.accounts_table.horizontalHeader().setStretchLastSection(True)
        self.accounts_table.verticalHeader().setVisible(False)
        self.accounts_table.verticalHeader().setHighlightSections(True)
        self.accounts_table.verticalHeader().setSortIndicatorShown(False)
        self.accounts_table.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.accounts_table, 1, 0, 1, 3)

        self.retranslateUi(AccountBalance)
        QtCore.QMetaObject.connectSlotsByName(AccountBalance)

    def retranslateUi(self, AccountBalance):
        _translate = QtCore.QCoreApplication.translate
        AccountBalance.setWindowTitle(_translate("AccountBalance", "أرصدة الحسابات"))
        self.account_details_btn.setText(_translate("AccountBalance", "تفاصيل"))
        self.label.setText(_translate("AccountBalance", "الحساب:"))
        self.select_account_btn.setText(_translate("AccountBalance", "...اختيار"))
        self.label_2.setText(_translate("AccountBalance", "العملة:"))
        self.accounts_table.setSortingEnabled(True)
        item = self.accounts_table.horizontalHeaderItem(0)
        item.setText(_translate("AccountBalance", "المعرف"))
        item = self.accounts_table.horizontalHeaderItem(1)
        item.setText(_translate("AccountBalance", "الحساب"))
        item = self.accounts_table.horizontalHeaderItem(2)
        item.setText(_translate("AccountBalance", "الميزانية الاجمالية"))
        item = self.accounts_table.horizontalHeaderItem(3)
        item.setText(_translate("AccountBalance", "الميزانية دون الأبناء"))
