# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Aggregator.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Aggregator(object):
    def setupUi(self, Aggregator):
        Aggregator.setObjectName("Aggregator")
        Aggregator.setWindowModality(QtCore.Qt.WindowModal)
        Aggregator.resize(992, 587)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("graphics/icon.xpm"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Aggregator.setWindowIcon(icon)
        Aggregator.setLayoutDirection(QtCore.Qt.RightToLeft)
        Aggregator.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(Aggregator)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Aggregator)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.products = QtWidgets.QComboBox(self.groupBox)
        self.products.setMinimumSize(QtCore.QSize(150, 0))
        self.products.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.products.setStyleSheet("QComboBox {\n"
"        background-color: #fafafa;\n"
"        border: 1px solid lightgrey;        \n"
"        height: 22px;\n"
"        color: black;\n"
"    }\n"
"    QComboBox::drop-down {\n"
"        border: none;\n"
"    }")
        self.products.setObjectName("products")
        self.gridLayout_3.addWidget(self.products, 0, 1, 1, 1)
        self.products_btn = QtWidgets.QToolButton(self.groupBox)
        self.products_btn.setObjectName("products_btn")
        self.gridLayout_3.addWidget(self.products_btn, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 3, 1, 1)
        self.target_input = QtWidgets.QLineEdit(self.groupBox)
        self.target_input.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.target_input.setObjectName("target_input")
        self.gridLayout_3.addWidget(self.target_input, 0, 4, 1, 1)
        self.add_btn = QtWidgets.QPushButton(self.groupBox)
        self.add_btn.setObjectName("add_btn")
        self.gridLayout_3.addWidget(self.add_btn, 0, 5, 1, 1)
        self.calc_btn = QtWidgets.QPushButton(self.groupBox)
        self.calc_btn.setObjectName("calc_btn")
        self.gridLayout_3.addWidget(self.calc_btn, 0, 6, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Aggregator)
        self.groupBox_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(789, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 2, 1, 1, 1)
        self.aggregator_items_table = QtWidgets.QTableWidget(self.groupBox_2)
        self.aggregator_items_table.setMaximumSize(QtCore.QSize(16777215, 500))
        self.aggregator_items_table.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.aggregator_items_table.setObjectName("aggregator_items_table")
        self.aggregator_items_table.setColumnCount(4)
        self.aggregator_items_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.aggregator_items_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.aggregator_items_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.aggregator_items_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.aggregator_items_table.setHorizontalHeaderItem(3, item)
        self.aggregator_items_table.horizontalHeader().setStretchLastSection(False)
        self.aggregator_items_table.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.aggregator_items_table, 0, 0, 1, 6)
        self.delete_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.delete_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.delete_btn.setObjectName("delete_btn")
        self.gridLayout_2.addWidget(self.delete_btn, 2, 2, 1, 1)
        self.clear_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.clear_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.clear_btn.setMouseTracking(False)
        self.clear_btn.setObjectName("clear_btn")
        self.gridLayout_2.addWidget(self.clear_btn, 2, 3, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 1)

        self.retranslateUi(Aggregator)
        QtCore.QMetaObject.connectSlotsByName(Aggregator)

    def retranslateUi(self, Aggregator):
        _translate = QtCore.QCoreApplication.translate
        Aggregator.setWindowTitle(_translate("Aggregator", "حاجة المواد الاولية"))
        self.label.setText(_translate("Aggregator", "المنتج:"))
        self.products_btn.setText(_translate("Aggregator", "🔎"))
        self.label_2.setText(_translate("Aggregator", "عدد القطع المطلوب:"))
        self.add_btn.setText(_translate("Aggregator", "اضافة"))
        self.calc_btn.setText(_translate("Aggregator", "حساب النتيجة"))
        item = self.aggregator_items_table.horizontalHeaderItem(0)
        item.setText(_translate("Aggregator", "المعرف"))
        item = self.aggregator_items_table.horizontalHeaderItem(1)
        item.setText(_translate("Aggregator", "الكود"))
        item = self.aggregator_items_table.horizontalHeaderItem(2)
        item.setText(_translate("Aggregator", "المنتج"))
        item = self.aggregator_items_table.horizontalHeaderItem(3)
        item.setText(_translate("Aggregator", "عدد القطع"))
        self.delete_btn.setText(_translate("Aggregator", "حذف"))
        self.clear_btn.setText(_translate("Aggregator", "حذف الكل"))
