# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_AddUser.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(300, 200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(300, 200))
        Dialog.setMaximumSize(QtCore.QSize(300, 200))
        Dialog.setLayoutDirection(QtCore.Qt.RightToLeft)
        Dialog.setSizeGripEnabled(False)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.username_label = QtWidgets.QLabel(self.groupBox_2)
        self.username_label.setObjectName("username_label")
        self.gridLayout.addWidget(self.username_label, 0, 0, 1, 1)
        self.username_input = QtWidgets.QLineEdit(self.groupBox_2)
        self.username_input.setMinimumSize(QtCore.QSize(100, 0))
        self.username_input.setMaximumSize(QtCore.QSize(200, 16777215))
        self.username_input.setObjectName("username_input")
        self.gridLayout.addWidget(self.username_input, 0, 1, 1, 1)
        self.password_label = QtWidgets.QLabel(self.groupBox_2)
        self.password_label.setObjectName("password_label")
        self.gridLayout.addWidget(self.password_label, 1, 0, 1, 1)
        self.password_input = QtWidgets.QLineEdit(self.groupBox_2)
        self.password_input.setMinimumSize(QtCore.QSize(100, 0))
        self.password_input.setMaximumSize(QtCore.QSize(200, 16777215))
        self.password_input.setObjectName("password_input")
        self.gridLayout.addWidget(self.password_input, 1, 1, 1, 1)
        self.password_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.password_btn.setMaximumSize(QtCore.QSize(20, 16777215))
        self.password_btn.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: black;\n"
"    font-size: 24px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 0, 0, 0.1);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 0.2);\n"
"}")
        self.password_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/eye_closed.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.password_btn.setIcon(icon)
        self.password_btn.setObjectName("password_btn")
        self.gridLayout.addWidget(self.password_btn, 1, 2, 1, 1)
        self.confirm_password_label = QtWidgets.QLabel(self.groupBox_2)
        self.confirm_password_label.setObjectName("confirm_password_label")
        self.gridLayout.addWidget(self.confirm_password_label, 2, 0, 1, 1)
        self.confirm_password_input = QtWidgets.QLineEdit(self.groupBox_2)
        self.confirm_password_input.setMinimumSize(QtCore.QSize(100, 0))
        self.confirm_password_input.setMaximumSize(QtCore.QSize(200, 16777215))
        self.confirm_password_input.setObjectName("confirm_password_input")
        self.gridLayout.addWidget(self.confirm_password_input, 2, 1, 1, 1)
        self.confirm_password_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.confirm_password_btn.setMaximumSize(QtCore.QSize(20, 16777215))
        self.confirm_password_btn.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: black;\n"
"    font-size: 24px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 0, 0, 0.1);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 0.2);\n"
"}")
        self.confirm_password_btn.setText("")
        self.confirm_password_btn.setIcon(icon)
        self.confirm_password_btn.setObjectName("confirm_password_btn")
        self.gridLayout.addWidget(self.confirm_password_btn, 2, 2, 1, 1)
        self.save_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.save_btn.setObjectName("save_btn")
        self.gridLayout.addWidget(self.save_btn, 3, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "إضافة مستخدم"))
        self.groupBox_2.setTitle(_translate("Dialog", "إضافة مستخدم جديد"))
        self.username_label.setText(_translate("Dialog", "الاسم:"))
        self.password_label.setText(_translate("Dialog", "كلمة السر:"))
        self.confirm_password_label.setText(_translate("Dialog", "تأكيد كلمة السر:"))
        self.save_btn.setText(_translate("Dialog", "حفظ"))
