# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_AddCostCenter.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddCostCenter(object):
    def setupUi(self, AddCostCenter):
        AddCostCenter.setObjectName("AddCostCenter")
        AddCostCenter.resize(439, 208)
        AddCostCenter.setMinimumSize(QtCore.QSize(300, 200))
        AddCostCenter.setMaximumSize(QtCore.QSize(500, 208))
        AddCostCenter.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.gridLayout_2 = QtWidgets.QGridLayout(AddCostCenter)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.notes_input = QtWidgets.QLineEdit(AddCostCenter)
        self.notes_input.setObjectName("notes_input")
        self.gridLayout_2.addWidget(self.notes_input, 4, 2, 1, 1)
        self.label_34 = QtWidgets.QLabel(AddCostCenter)
        self.label_34.setObjectName("label_34")
        self.gridLayout_2.addWidget(self.label_34, 1, 1, 1, 1)
        self.type_combobox = QtWidgets.QComboBox(AddCostCenter)
        self.type_combobox.setObjectName("type_combobox")
        self.gridLayout_2.addWidget(self.type_combobox, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(AddCostCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 1, 1, 1)
        self.name_input = QtWidgets.QLineEdit(AddCostCenter)
        self.name_input.setObjectName("name_input")
        self.gridLayout_2.addWidget(self.name_input, 0, 2, 1, 1)
        self.label_35 = QtWidgets.QLabel(AddCostCenter)
        self.label_35.setMinimumSize(QtCore.QSize(125, 0))
        self.label_35.setMaximumSize(QtCore.QSize(125, 16777215))
        self.label_35.setObjectName("label_35")
        self.gridLayout_2.addWidget(self.label_35, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(AddCostCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 4, 1, 1, 1)
        self.save_btn = QtWidgets.QPushButton(AddCostCenter)
        self.save_btn.setMinimumSize(QtCore.QSize(100, 0))
        self.save_btn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.save_btn.setObjectName("save_btn")
        self.gridLayout_2.addWidget(self.save_btn, 5, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(128, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 5, 2, 1, 1)
        self.parent_combobox = QtWidgets.QComboBox(AddCostCenter)
        self.parent_combobox.setEnabled(False)
        self.parent_combobox.setMinimumSize(QtCore.QSize(0, 0))
        self.parent_combobox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.parent_combobox.setObjectName("parent_combobox")
        self.gridLayout_2.addWidget(self.parent_combobox, 2, 2, 1, 1)
        self.select_parent_btn = QtWidgets.QPushButton(AddCostCenter)
        self.select_parent_btn.setObjectName("select_parent_btn")
        self.gridLayout_2.addWidget(self.select_parent_btn, 2, 3, 1, 1)

        self.retranslateUi(AddCostCenter)
        QtCore.QMetaObject.connectSlotsByName(AddCostCenter)

    def retranslateUi(self, AddCostCenter):
        _translate = QtCore.QCoreApplication.translate
        AddCostCenter.setWindowTitle(_translate("AddCostCenter", "مركز كلفة جديد"))
        self.label_34.setText(_translate("AddCostCenter", "النوع:"))
        self.label.setText(_translate("AddCostCenter", "اسم المركز:"))
        self.label_35.setText(_translate("AddCostCenter", "مركز الكلفة الرئيسي:"))
        self.label_6.setText(_translate("AddCostCenter", "ملاحظات:"))
        self.save_btn.setText(_translate("AddCostCenter", "حفظ"))
        self.select_parent_btn.setText(_translate("AddCostCenter", "...اختيار"))
