# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_AddEditFinancialStatement.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddEditFinancialStatement(object):
    def setupUi(self, AddEditFinancialStatement):
        AddEditFinancialStatement.setObjectName("AddEditFinancialStatement")
        AddEditFinancialStatement.resize(344, 232)
        self.gridLayout_2 = QtWidgets.QGridLayout(AddEditFinancialStatement)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(AddEditFinancialStatement)
        self.groupBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.save_btn = QtWidgets.QPushButton(self.groupBox)
        self.save_btn.setObjectName("save_btn")
        self.gridLayout.addWidget(self.save_btn, 5, 0, 1, 3)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.final_financial_statement_name = QtWidgets.QLineEdit(self.groupBox)
        self.final_financial_statement_name.setReadOnly(True)
        self.final_financial_statement_name.setObjectName("final_financial_statement_name")
        self.gridLayout.addWidget(self.final_financial_statement_name, 3, 1, 1, 1)
        self.edit_final_financial_statement_btn = QtWidgets.QToolButton(self.groupBox)
        self.edit_final_financial_statement_btn.setObjectName("edit_final_financial_statement_btn")
        self.gridLayout.addWidget(self.edit_final_financial_statement_btn, 3, 2, 1, 1)
        self.financial_statement_name = QtWidgets.QLineEdit(self.groupBox)
        self.financial_statement_name.setObjectName("financial_statement_name")
        self.gridLayout.addWidget(self.financial_statement_name, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(AddEditFinancialStatement)
        QtCore.QMetaObject.connectSlotsByName(AddEditFinancialStatement)

    def retranslateUi(self, AddEditFinancialStatement):
        _translate = QtCore.QCoreApplication.translate
        AddEditFinancialStatement.setWindowTitle(_translate("AddEditFinancialStatement", "إضافة قائمة مالية"))
        self.label_2.setText(_translate("AddEditFinancialStatement", "القائمة المالية الختامية:"))
        self.save_btn.setText(_translate("AddEditFinancialStatement", "حفظ"))
        self.label.setText(_translate("AddEditFinancialStatement", "اسم القائمة المالية:"))
        self.edit_final_financial_statement_btn.setText(_translate("AddEditFinancialStatement", "🔎"))
