# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_AuthenticateUser.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AuthenticateUser(object):
    def setupUi(self, AuthenticateUser):
        AuthenticateUser.setObjectName("AuthenticateUser")
        AuthenticateUser.resize(300, 150)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AuthenticateUser.sizePolicy().hasHeightForWidth())
        AuthenticateUser.setSizePolicy(sizePolicy)
        AuthenticateUser.setMinimumSize(QtCore.QSize(300, 100))
        AuthenticateUser.setMaximumSize(QtCore.QSize(300, 150))
        AuthenticateUser.setLayoutDirection(QtCore.Qt.RightToLeft)
        AuthenticateUser.setSizeGripEnabled(False)
        self.gridLayout_2 = QtWidgets.QGridLayout(AuthenticateUser)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(AuthenticateUser)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 150))
        self.groupBox_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.password_input = QtWidgets.QLineEdit(self.groupBox_2)
        self.password_input.setMinimumSize(QtCore.QSize(100, 0))
        self.password_input.setMaximumSize(QtCore.QSize(200, 16777215))
        self.password_input.setObjectName("password_input")
        self.gridLayout.addWidget(self.password_input, 1, 1, 1, 1)
        self.password_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.password_btn.setMaximumSize(QtCore.QSize(20, 16777215))
        self.password_btn.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: black;\n"
"    font-size: 24px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 0, 0, 0.1);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 0.2);\n"
"}")
        self.password_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/eye_closed.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.password_btn.setIcon(icon)
        self.password_btn.setObjectName("password_btn")
        self.gridLayout.addWidget(self.password_btn, 1, 2, 1, 1)
        self.username_label = QtWidgets.QLabel(self.groupBox_2)
        self.username_label.setObjectName("username_label")
        self.gridLayout.addWidget(self.username_label, 0, 0, 1, 1)
        self.password_label = QtWidgets.QLabel(self.groupBox_2)
        self.password_label.setObjectName("password_label")
        self.gridLayout.addWidget(self.password_label, 1, 0, 1, 1)
        self.login_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.login_btn.setObjectName("login_btn")
        self.gridLayout.addWidget(self.login_btn, 2, 1, 1, 2)
        self.user_combobox = QtWidgets.QComboBox(self.groupBox_2)
        self.user_combobox.setObjectName("user_combobox")
        self.gridLayout.addWidget(self.user_combobox, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 0, 1, 1)

        self.retranslateUi(AuthenticateUser)
        QtCore.QMetaObject.connectSlotsByName(AuthenticateUser)

    def retranslateUi(self, AuthenticateUser):
        _translate = QtCore.QCoreApplication.translate
        AuthenticateUser.setWindowTitle(_translate("AuthenticateUser", "تسجيل الدخول"))
        self.groupBox_2.setTitle(_translate("AuthenticateUser", "تسجيل دخول"))
        self.username_label.setText(_translate("AuthenticateUser", "الاسم:"))
        self.password_label.setText(_translate("AuthenticateUser", "كلمة السر:"))
        self.login_btn.setText(_translate("AuthenticateUser", "تسجيل دخول"))
