# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_AddMaterialToWarehouse.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddMaterialToWarehouse(object):
    def setupUi(self, AddMaterialToWarehouse):
        AddMaterialToWarehouse.setObjectName("AddMaterialToWarehouse")
        AddMaterialToWarehouse.resize(521, 218)
        AddMaterialToWarehouse.setMinimumSize(QtCore.QSize(521, 200))
        AddMaterialToWarehouse.setMaximumSize(QtCore.QSize(521, 400))
        self.gridLayout = QtWidgets.QGridLayout(AddMaterialToWarehouse)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(AddMaterialToWarehouse)
        self.groupBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.quantity_input = QtWidgets.QLineEdit(self.groupBox)
        self.quantity_input.setMinimumSize(QtCore.QSize(150, 0))
        self.quantity_input.setMaximumSize(QtCore.QSize(200, 16777215))
        self.quantity_input.setObjectName("quantity_input")
        self.gridLayout_2.addWidget(self.quantity_input, 2, 4, 1, 2)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 3, 1, 1)
        self.select_group_btn = QtWidgets.QPushButton(self.groupBox)
        self.select_group_btn.setObjectName("select_group_btn")
        self.gridLayout_2.addWidget(self.select_group_btn, 0, 5, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 6, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 4, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.expire_date_input = QtWidgets.QDateEdit(self.groupBox)
        self.expire_date_input.setObjectName("expire_date_input")
        self.gridLayout_2.addWidget(self.expire_date_input, 4, 4, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 3, 0, 1, 1)
        self.groups_combobox = QtWidgets.QComboBox(self.groupBox)
        self.groups_combobox.setMinimumSize(QtCore.QSize(100, 0))
        self.groups_combobox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groups_combobox.setStyleSheet("QComboBox {\n"
"        background-color: #fafafa;\n"
"        border: 1px solid lightgrey;        \n"
"        height: 22px;\n"
"        color: black;\n"
"    }\n"
"    QComboBox::drop-down {\n"
"        border: none;\n"
"    }")
        self.groups_combobox.setObjectName("groups_combobox")
        self.gridLayout_2.addWidget(self.groups_combobox, 0, 4, 1, 1)
        self.currency_combobox = QtWidgets.QComboBox(self.groupBox)
        self.currency_combobox.setMinimumSize(QtCore.QSize(100, 0))
        self.currency_combobox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.currency_combobox.setObjectName("currency_combobox")
        self.gridLayout_2.addWidget(self.currency_combobox, 3, 1, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 3, 1, 1)
        self.unit_combobox = QtWidgets.QComboBox(self.groupBox)
        self.unit_combobox.setMinimumSize(QtCore.QSize(100, 0))
        self.unit_combobox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.unit_combobox.setObjectName("unit_combobox")
        self.gridLayout_2.addWidget(self.unit_combobox, 2, 1, 1, 2)
        self.save_btn = QtWidgets.QPushButton(self.groupBox)
        self.save_btn.setObjectName("save_btn")
        self.gridLayout_2.addWidget(self.save_btn, 6, 5, 1, 1)
        self.price_input = QtWidgets.QLineEdit(self.groupBox)
        self.price_input.setObjectName("price_input")
        self.gridLayout_2.addWidget(self.price_input, 4, 1, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 4, 0, 1, 1)
        self.account_combobox = QtWidgets.QComboBox(self.groupBox)
        self.account_combobox.setMinimumSize(QtCore.QSize(100, 0))
        self.account_combobox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.account_combobox.setStyleSheet("QComboBox {\n"
"        background-color: #fafafa;\n"
"        border: 1px solid lightgrey;        \n"
"        height: 22px;\n"
"        color: black;\n"
"    }\n"
"    QComboBox::drop-down {\n"
"        border: none;\n"
"    }")
        self.account_combobox.setObjectName("account_combobox")
        self.gridLayout_2.addWidget(self.account_combobox, 6, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.production_date_input = QtWidgets.QDateEdit(self.groupBox)
        self.production_date_input.setObjectName("production_date_input")
        self.gridLayout_2.addWidget(self.production_date_input, 3, 4, 1, 2)
        self.select_account_btn = QtWidgets.QPushButton(self.groupBox)
        self.select_account_btn.setObjectName("select_account_btn")
        self.gridLayout_2.addWidget(self.select_account_btn, 6, 2, 1, 1)
        self.select_material_btn = QtWidgets.QPushButton(self.groupBox)
        self.select_material_btn.setObjectName("select_material_btn")
        self.gridLayout_2.addWidget(self.select_material_btn, 0, 2, 1, 1)
        self.materials_combobox = QtWidgets.QComboBox(self.groupBox)
        self.materials_combobox.setMinimumSize(QtCore.QSize(100, 0))
        self.materials_combobox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.materials_combobox.setStyleSheet("QComboBox {\n"
"        background-color: #fafafa;\n"
"        border: 1px solid lightgrey;        \n"
"        height: 22px;\n"
"        color: black;\n"
"    }\n"
"    QComboBox::drop-down {\n"
"        border: none;\n"
"    }")
        self.materials_combobox.setObjectName("materials_combobox")
        self.gridLayout_2.addWidget(self.materials_combobox, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)

        self.retranslateUi(AddMaterialToWarehouse)
        QtCore.QMetaObject.connectSlotsByName(AddMaterialToWarehouse)

    def retranslateUi(self, AddMaterialToWarehouse):
        _translate = QtCore.QCoreApplication.translate
        AddMaterialToWarehouse.setWindowTitle(_translate("AddMaterialToWarehouse", "إضافة مادة إلى المستودع"))
        self.label.setText(_translate("AddMaterialToWarehouse", "المجموعة:"))
        self.select_group_btn.setText(_translate("AddMaterialToWarehouse", "...اختيار"))
        self.label_9.setText(_translate("AddMaterialToWarehouse", "الحساب:"))
        self.label_6.setText(_translate("AddMaterialToWarehouse", "تاريخ الانتهاء:"))
        self.label_2.setText(_translate("AddMaterialToWarehouse", "الكمية:"))
        self.label_4.setText(_translate("AddMaterialToWarehouse", "الواحدة:"))
        self.label_7.setText(_translate("AddMaterialToWarehouse", "العملة:"))
        self.label_5.setText(_translate("AddMaterialToWarehouse", "تاريخ الانتاج:"))
        self.save_btn.setText(_translate("AddMaterialToWarehouse", "حفظ"))
        self.label_8.setText(_translate("AddMaterialToWarehouse", "السعر:"))
        self.label_3.setText(_translate("AddMaterialToWarehouse", "المادة:"))
        self.select_account_btn.setText(_translate("AddMaterialToWarehouse", "...اختيار"))
        self.select_material_btn.setText(_translate("AddMaterialToWarehouse", "...اختيار"))
