# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_AggregatorResult.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AggregatorResult(object):
    def setupUi(self, AggregatorResult):
        AggregatorResult.setObjectName("AggregatorResult")
        AggregatorResult.resize(1211, 628)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("graphics/icon.xpm"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AggregatorResult.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(AggregatorResult)
        self.gridLayout.setObjectName("gridLayout")
        self.aggregator_result_table = QtWidgets.QTableWidget(AggregatorResult)
        self.aggregator_result_table.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.aggregator_result_table.setObjectName("aggregator_result_table")
        self.aggregator_result_table.setColumnCount(2)
        self.aggregator_result_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.aggregator_result_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.aggregator_result_table.setHorizontalHeaderItem(1, item)
        self.gridLayout.addWidget(self.aggregator_result_table, 0, 0, 1, 1)
        self.export_btn = QtWidgets.QPushButton(AggregatorResult)
        self.export_btn.setMaximumSize(QtCore.QSize(80, 16777215))
        self.export_btn.setObjectName("export_btn")
        self.gridLayout.addWidget(self.export_btn, 1, 0, 1, 1)

        self.retranslateUi(AggregatorResult)
        QtCore.QMetaObject.connectSlotsByName(AggregatorResult)

    def retranslateUi(self, AggregatorResult):
        _translate = QtCore.QCoreApplication.translate
        AggregatorResult.setWindowTitle(_translate("AggregatorResult", "النتيجة"))
        AggregatorResult.setAccessibleName(_translate("AggregatorResult", "SimplePlanResult"))
        item = self.aggregator_result_table.horizontalHeaderItem(0)
        item.setText(_translate("AggregatorResult", "المادة الأولية"))
        item = self.aggregator_result_table.horizontalHeaderItem(1)
        item.setText(_translate("AggregatorResult", "الكمية المطلوبة"))
        self.export_btn.setText(_translate("AggregatorResult", "تصدير"))
