# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Accounts.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Accounts(object):
    def setupUi(self, Accounts):
        Accounts.setObjectName("Accounts")
        Accounts.setWindowModality(QtCore.Qt.WindowModal)
        Accounts.resize(578, 488)
        Accounts.setLayoutDirection(QtCore.Qt.RightToLeft)
        Accounts.setModal(True)
        self.gridLayout_3 = QtWidgets.QGridLayout(Accounts)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.search_group = QtWidgets.QGroupBox(Accounts)
        self.search_group.setTitle("")
        self.search_group.setObjectName("search_group")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.search_group)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.search_box = QtWidgets.QLineEdit(self.search_group)
        self.search_box.setClearButtonEnabled(True)
        self.search_box.setObjectName("search_box")
        self.horizontalLayout.addWidget(self.search_box)
        self.gridLayout_3.addWidget(self.search_group, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Accounts)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.accounts_tree = QtWidgets.QTreeWidget(self.groupBox)
        self.accounts_tree.setObjectName("accounts_tree")
        self.gridLayout_2.addWidget(self.accounts_tree, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Accounts)
        self.groupBox_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.add_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.add_btn.setObjectName("add_btn")
        self.gridLayout.addWidget(self.add_btn, 0, 0, 1, 1)
        self.delete_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.delete_btn.setObjectName("delete_btn")
        self.gridLayout.addWidget(self.delete_btn, 0, 2, 1, 1)
        self.edit_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.edit_btn.setObjectName("edit_btn")
        self.gridLayout.addWidget(self.edit_btn, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 2, 0, 1, 1)

        self.retranslateUi(Accounts)
        QtCore.QMetaObject.connectSlotsByName(Accounts)

    def retranslateUi(self, Accounts):
        _translate = QtCore.QCoreApplication.translate
        Accounts.setWindowTitle(_translate("Accounts", "الحسابات"))
        self.search_box.setPlaceholderText(_translate("Accounts", "ابحث عن حساب..."))
        self.accounts_tree.headerItem().setText(0, _translate("Accounts", "الرمز"))
        self.accounts_tree.headerItem().setText(1, _translate("Accounts", "الحساب"))
        self.accounts_tree.headerItem().setText(2, _translate("Accounts", "المعرف"))
        self.add_btn.setText(_translate("Accounts", "إضافة حساب"))
        self.delete_btn.setText(_translate("Accounts", "...حذف"))
        self.edit_btn.setText(_translate("Accounts", "...تعديل معلومات الحساب"))
