# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_AddGroup.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddGroup(object):
    def setupUi(self, AddGroup):
        AddGroup.setObjectName("AddGroup")
        AddGroup.resize(350, 180)
        AddGroup.setMinimumSize(QtCore.QSize(350, 180))
        AddGroup.setMaximumSize(QtCore.QSize(350, 180))
        AddGroup.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.gridLayout = QtWidgets.QGridLayout(AddGroup)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(AddGroup)
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.name_input = QtWidgets.QLineEdit(self.groupBox)
        self.name_input.setObjectName("name_input")
        self.gridLayout_2.addWidget(self.name_input, 0, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 2, 1, 1)
        self.select_parent_btn = QtWidgets.QPushButton(self.groupBox)
        self.select_parent_btn.setObjectName("select_parent_btn")
        self.gridLayout_2.addWidget(self.select_parent_btn, 1, 0, 1, 1)
        self.parent_combobox = QtWidgets.QComboBox(self.groupBox)
        self.parent_combobox.setObjectName("parent_combobox")
        self.gridLayout_2.addWidget(self.parent_combobox, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 2, 1, 1)
        self.save_btn = QtWidgets.QPushButton(self.groupBox)
        self.save_btn.setObjectName("save_btn")
        self.gridLayout_2.addWidget(self.save_btn, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(AddGroup)
        QtCore.QMetaObject.connectSlotsByName(AddGroup)

    def retranslateUi(self, AddGroup):
        _translate = QtCore.QCoreApplication.translate
        AddGroup.setWindowTitle(_translate("AddGroup", "إضافة مجموعة جديدة"))
        self.label.setText(_translate("AddGroup", "اسم المجموعة:"))
        self.select_parent_btn.setText(_translate("AddGroup", "...اختيار"))
        self.label_2.setText(_translate("AddGroup", "المجموعة الأب:"))
        self.save_btn.setText(_translate("AddGroup", "حفظ"))
