# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_About.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_About(object):
    def setupUi(self, About):
        About.setObjectName("About")
        About.setWindowModality(QtCore.Qt.WindowModal)
        About.resize(631, 283)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("graphics/icon.xpm"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        About.setWindowIcon(icon)
        About.setModal(True)
        self.about_version = QtWidgets.QLabel(About)
        self.about_version.setGeometry(QtCore.QRect(300, 150, 101, 21))
        self.about_version.setObjectName("about_version")
        self.about_label = QtWidgets.QLabel(About)
        self.about_label.setGeometry(QtCore.QRect(300, 170, 311, 21))
        self.about_label.setObjectName("about_label")
        self.about_label_2 = QtWidgets.QLabel(About)
        self.about_label_2.setGeometry(QtCore.QRect(300, 190, 131, 16))
        self.about_label_2.setObjectName("about_label_2")
        self.label_4 = QtWidgets.QLabel(About)
        self.label_4.setGeometry(QtCore.QRect(50, 30, 241, 241))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("graphics/about.jpg"))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(About)
        QtCore.QMetaObject.connectSlotsByName(About)

    def retranslateUi(self, About):
        _translate = QtCore.QCoreApplication.translate
        About.setWindowTitle(_translate("About", "حول البرنامج"))
        self.about_version.setText(_translate("About", "Epsilon V"))
        self.about_label.setText(_translate("About", "Developed By Hussain Biedouh on behalf of Golden Med Pharma"))
        self.about_label_2.setText(_translate("About", "Golden Med Pharma ©"))
