# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_ClientEdit.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ClientEdit(object):
    def setupUi(self, ClientEdit):
        ClientEdit.setObjectName("ClientEdit")
        ClientEdit.resize(506, 358)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("graphics/icon.xpm"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ClientEdit.setWindowIcon(icon)
        self.gridLayout_2 = QtWidgets.QGridLayout(ClientEdit)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(ClientEdit)
        self.groupBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.governorate_input = QtWidgets.QLineEdit(self.groupBox)
        self.governorate_input.setObjectName("governorate_input")
        self.gridLayout.addWidget(self.governorate_input, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 3, 1, 1)
        self.address_input = QtWidgets.QLineEdit(self.groupBox)
        self.address_input.setObjectName("address_input")
        self.gridLayout.addWidget(self.address_input, 3, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.save_btn = QtWidgets.QPushButton(self.groupBox)
        self.save_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.save_btn.setObjectName("save_btn")
        self.gridLayout.addWidget(self.save_btn, 5, 4, 1, 1)
        self.phone1_input = QtWidgets.QLineEdit(self.groupBox)
        self.phone1_input.setObjectName("phone1_input")
        self.gridLayout.addWidget(self.phone1_input, 0, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 1, 1, 1)
        self.phone2_input = QtWidgets.QLineEdit(self.groupBox)
        self.phone2_input.setObjectName("phone2_input")
        self.gridLayout.addWidget(self.phone2_input, 2, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 1, 1, 1)
        self.email_input = QtWidgets.QLineEdit(self.groupBox)
        self.email_input.setObjectName("email_input")
        self.gridLayout.addWidget(self.email_input, 4, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 3, 1, 1)
        self.phone3_input = QtWidgets.QLineEdit(self.groupBox)
        self.phone3_input.setObjectName("phone3_input")
        self.gridLayout.addWidget(self.phone3_input, 3, 4, 1, 1)
        self.phone4_input = QtWidgets.QLineEdit(self.groupBox)
        self.phone4_input.setText("")
        self.phone4_input.setObjectName("phone4_input")
        self.gridLayout.addWidget(self.phone4_input, 4, 4, 1, 1)
        self.name_input = QtWidgets.QLineEdit(self.groupBox)
        self.name_input.setObjectName("name_input")
        self.gridLayout.addWidget(self.name_input, 0, 2, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(ClientEdit)
        QtCore.QMetaObject.connectSlotsByName(ClientEdit)

    def retranslateUi(self, ClientEdit):
        _translate = QtCore.QCoreApplication.translate
        ClientEdit.setWindowTitle(_translate("ClientEdit", "تعديل بيانات زبون"))
        self.groupBox.setTitle(_translate("ClientEdit", "بيانات الزبون"))
        self.label_4.setText(_translate("ClientEdit", "هاتف 1:"))
        self.label_5.setText(_translate("ClientEdit", "هاتف 2:"))
        self.label.setText(_translate("ClientEdit", "الاسم:"))
        self.save_btn.setText(_translate("ClientEdit", "حفظ"))
        self.label_2.setText(_translate("ClientEdit", "المحافظة:"))
        self.label_7.setText(_translate("ClientEdit", "هاتف 4:"))
        self.label_3.setText(_translate("ClientEdit", "العنوان التفصيلي:"))
        self.label_8.setText(_translate("ClientEdit", "البريد الالكتروني:"))
        self.label_6.setText(_translate("ClientEdit", "هاتف 3:"))
