# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Composition.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Composition(object):
    def setupUi(self, Composition):
        Composition.setObjectName("Composition")
        Composition.resize(450, 492)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("graphics/icon.xpm"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Composition.setWindowIcon(icon)
        Composition.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox = QtWidgets.QGroupBox(Composition)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 431, 71))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.add_btn = QtWidgets.QPushButton(self.groupBox)
        self.add_btn.setGeometry(QtCore.QRect(20, 40, 75, 23))
        self.add_btn.setObjectName("add_btn")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(350, 10, 61, 16))
        self.label.setObjectName("label")
        self.materials_combobox = QtWidgets.QComboBox(self.groupBox)
        self.materials_combobox.setGeometry(QtCore.QRect(110, 10, 231, 20))
        self.materials_combobox.setObjectName("materials_combobox")
        self.quantity_required = QtWidgets.QLineEdit(self.groupBox)
        self.quantity_required.setGeometry(QtCore.QRect(310, 40, 113, 20))
        self.quantity_required.setObjectName("quantity_required")
        self.unit = QtWidgets.QLineEdit(self.groupBox)
        self.unit.setEnabled(False)
        self.unit.setGeometry(QtCore.QRect(190, 40, 113, 20))
        self.unit.setObjectName("unit")
        self.unit_combobox = QtWidgets.QComboBox(self.groupBox)
        self.unit_combobox.setEnabled(False)
        self.unit_combobox.setGeometry(QtCore.QRect(110, 40, 69, 22))
        self.unit_combobox.setObjectName("unit_combobox")
        self.unit_combobox.addItem("")
        self.unit_combobox.addItem("")
        self.unit_combobox.addItem("")
        self.groupBox_2 = QtWidgets.QGroupBox(Composition)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 90, 431, 341))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.materials_table = QtWidgets.QTableWidget(self.groupBox_2)
        self.materials_table.setGeometry(QtCore.QRect(10, 10, 411, 351))
        self.materials_table.setObjectName("materials_table")
        self.materials_table.setColumnCount(5)
        self.materials_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.materials_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.materials_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.materials_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.materials_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.materials_table.setHorizontalHeaderItem(4, item)
        self.groupBox_3 = QtWidgets.QGroupBox(Composition)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 440, 431, 41))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.delete_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.delete_btn.setGeometry(QtCore.QRect(330, 10, 75, 23))
        self.delete_btn.setObjectName("delete_btn")

        self.retranslateUi(Composition)
        QtCore.QMetaObject.connectSlotsByName(Composition)

    def retranslateUi(self, Composition):
        _translate = QtCore.QCoreApplication.translate
        Composition.setWindowTitle(_translate("Composition", "التركيب"))
        self.add_btn.setText(_translate("Composition", "إضافة"))
        self.label.setText(_translate("Composition", "المواد الأولية:"))
        self.unit_combobox.setItemText(0, _translate("Composition", "كغ"))
        self.unit_combobox.setItemText(1, _translate("Composition", "ليتر"))
        self.unit_combobox.setItemText(2, _translate("Composition", "قطعة"))
        item = self.materials_table.horizontalHeaderItem(0)
        item.setText(_translate("Composition", "#"))
        item = self.materials_table.horizontalHeaderItem(1)
        item.setText(_translate("Composition", "المادة"))
        item = self.materials_table.horizontalHeaderItem(2)
        item.setText(_translate("Composition", "الكمية"))
        item = self.materials_table.horizontalHeaderItem(3)
        item.setText(_translate("Composition", "الواحدة"))
        self.delete_btn.setText(_translate("Composition", "حذف"))
