# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Configuration.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Configuration(object):
    def setupUi(self, Configuration):
        Configuration.setObjectName("Configuration")
        Configuration.setWindowModality(QtCore.Qt.WindowModal)
        Configuration.resize(300, 200)
        Configuration.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.gridLayout_4 = QtWidgets.QGridLayout(Configuration)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox = QtWidgets.QGroupBox(Configuration)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ok_button = QtWidgets.QPushButton(self.groupBox)
        self.ok_button.setObjectName("ok_button")
        self.gridLayout_3.addWidget(self.ok_button, 5, 1, 1, 1)
        self.manuals_combobox = QtWidgets.QComboBox(self.groupBox)
        self.manuals_combobox.setObjectName("manuals_combobox")
        self.gridLayout_3.addWidget(self.manuals_combobox, 3, 1, 1, 1)
        self.perpetual_radio = QtWidgets.QRadioButton(self.groupBox)
        self.perpetual_radio.setObjectName("perpetual_radio")
        self.gridLayout_3.addWidget(self.perpetual_radio, 0, 1, 1, 1)
        self.info_label_2 = QtWidgets.QLabel(self.groupBox)
        self.info_label_2.setWordWrap(True)
        self.info_label_2.setObjectName("info_label_2")
        self.gridLayout_3.addWidget(self.info_label_2, 3, 0, 1, 1)
        self.info_label = QtWidgets.QLabel(self.groupBox)
        self.info_label.setWordWrap(True)
        self.info_label.setObjectName("info_label")
        self.gridLayout_3.addWidget(self.info_label, 0, 0, 1, 1)
        self.periodic_radio = QtWidgets.QRadioButton(self.groupBox)
        self.periodic_radio.setChecked(True)
        self.periodic_radio.setObjectName("periodic_radio")
        self.gridLayout_3.addWidget(self.periodic_radio, 1, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Configuration)
        QtCore.QMetaObject.connectSlotsByName(Configuration)

    def retranslateUi(self, Configuration):
        _translate = QtCore.QCoreApplication.translate
        Configuration.setWindowTitle(_translate("Configuration", "نوع المخزون"))
        self.groupBox.setTitle(_translate("Configuration", "الجرد"))
        self.ok_button.setText(_translate("Configuration", "موافق"))
        self.perpetual_radio.setText(_translate("Configuration", "جرد مستمر"))
        self.info_label_2.setText(_translate("Configuration", "اختر الدليل المحاسبي:"))
        self.info_label.setText(_translate("Configuration", "اختر نوع المخزون:"))
        self.periodic_radio.setText(_translate("Configuration", "جرد دوري"))
