# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Course_View.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Course_View(object):
    def setupUi(self, Course_View):
        Course_View.setObjectName("Course_View")
        Course_View.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Course_View)
        self.gridLayout.setObjectName("gridLayout")
        self.dire = QtWidgets.QGroupBox(Course_View)
        self.dire.setMinimumSize(QtCore.QSize(350, 0))
        self.dire.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.dire.setTitle("")
        self.dire.setObjectName("dire")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.dire)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.course_date_input = QtWidgets.QDateEdit(self.dire)
        self.course_date_input.setObjectName("course_date_input")
        self.gridLayout_26.addWidget(self.course_date_input, 10, 1, 1, 2)
        self.name_label_2 = QtWidgets.QLabel(self.dire)
        self.name_label_2.setObjectName("name_label_2")
        self.gridLayout_26.addWidget(self.name_label_2, 0, 0, 1, 1)
        self.department_label_2 = QtWidgets.QLabel(self.dire)
        self.department_label_2.setObjectName("department_label_2")
        self.gridLayout_26.addWidget(self.department_label_2, 1, 0, 1, 1)
        self.job_title_label_2 = QtWidgets.QLabel(self.dire)
        self.job_title_label_2.setObjectName("job_title_label_2")
        self.gridLayout_26.addWidget(self.job_title_label_2, 2, 0, 1, 1)
        self.course_costs_account_combobox = QtWidgets.QComboBox(self.dire)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.course_costs_account_combobox.sizePolicy().hasHeightForWidth())
        self.course_costs_account_combobox.setSizePolicy(sizePolicy)
        self.course_costs_account_combobox.setStyleSheet("QComboBox {\n"
"        background-color: #fafafa;\n"
"        border: 1px solid lightgrey;        \n"
"        height: 22px;\n"
"        color: black;\n"
"    }\n"
"    QComboBox::drop-down {\n"
"        border: none;\n"
"    }")
        self.course_costs_account_combobox.setObjectName("course_costs_account_combobox")
        self.gridLayout_26.addWidget(self.course_costs_account_combobox, 4, 1, 1, 1)
        self.job_title_label_3 = QtWidgets.QLabel(self.dire)
        self.job_title_label_3.setObjectName("job_title_label_3")
        self.gridLayout_26.addWidget(self.job_title_label_3, 4, 0, 1, 1)
        self.course_providor_input = QtWidgets.QLineEdit(self.dire)
        self.course_providor_input.setObjectName("course_providor_input")
        self.gridLayout_26.addWidget(self.course_providor_input, 1, 1, 1, 2)
        self.course_save_btn = QtWidgets.QPushButton(self.dire)
        self.course_save_btn.setObjectName("course_save_btn")
        self.gridLayout_26.addWidget(self.course_save_btn, 12, 2, 1, 1)
        self.email_label_3 = QtWidgets.QLabel(self.dire)
        self.email_label_3.setObjectName("email_label_3")
        self.gridLayout_26.addWidget(self.email_label_3, 11, 0, 1, 1)
        self.course_place_input = QtWidgets.QLineEdit(self.dire)
        self.course_place_input.setObjectName("course_place_input")
        self.gridLayout_26.addWidget(self.course_place_input, 11, 1, 1, 2)
        self.email_label_2 = QtWidgets.QLabel(self.dire)
        self.email_label_2.setObjectName("email_label_2")
        self.gridLayout_26.addWidget(self.email_label_2, 10, 0, 1, 1)
        self.course_name_input = QtWidgets.QLineEdit(self.dire)
        self.course_name_input.setObjectName("course_name_input")
        self.gridLayout_26.addWidget(self.course_name_input, 0, 1, 1, 2)
        self.course_cost_input = QtWidgets.QLineEdit(self.dire)
        self.course_cost_input.setObjectName("course_cost_input")
        self.gridLayout_26.addWidget(self.course_cost_input, 2, 1, 1, 1)
        self.course_cost_currency_combobox = QtWidgets.QComboBox(self.dire)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.course_cost_currency_combobox.sizePolicy().hasHeightForWidth())
        self.course_cost_currency_combobox.setSizePolicy(sizePolicy)
        self.course_cost_currency_combobox.setObjectName("course_cost_currency_combobox")
        self.gridLayout_26.addWidget(self.course_cost_currency_combobox, 2, 2, 1, 1)
        self.course_costs_opposite_account_combobox = QtWidgets.QComboBox(self.dire)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.course_costs_opposite_account_combobox.sizePolicy().hasHeightForWidth())
        self.course_costs_opposite_account_combobox.setSizePolicy(sizePolicy)
        self.course_costs_opposite_account_combobox.setStyleSheet("QComboBox {\n"
"        background-color: #fafafa;\n"
"        border: 1px solid lightgrey;        \n"
"        height: 22px;\n"
"        color: black;\n"
"    }\n"
"    QComboBox::drop-down {\n"
"        border: none;\n"
"    }")
        self.course_costs_opposite_account_combobox.setObjectName("course_costs_opposite_account_combobox")
        self.gridLayout_26.addWidget(self.course_costs_opposite_account_combobox, 6, 1, 1, 1)
        self.job_title_label_4 = QtWidgets.QLabel(self.dire)
        self.job_title_label_4.setObjectName("job_title_label_4")
        self.gridLayout_26.addWidget(self.job_title_label_4, 6, 0, 1, 1)
        self.select_course_costs_opposite_account_btn = QtWidgets.QToolButton(self.dire)
        self.select_course_costs_opposite_account_btn.setObjectName("select_course_costs_opposite_account_btn")
        self.gridLayout_26.addWidget(self.select_course_costs_opposite_account_btn, 6, 2, 1, 1)
        self.select_course_costs_account_btn = QtWidgets.QToolButton(self.dire)
        self.select_course_costs_account_btn.setObjectName("select_course_costs_account_btn")
        self.gridLayout_26.addWidget(self.select_course_costs_account_btn, 4, 2, 1, 1)
        self.gridLayout.addWidget(self.dire, 0, 0, 1, 1)

        self.retranslateUi(Course_View)
        QtCore.QMetaObject.connectSlotsByName(Course_View)

    def retranslateUi(self, Course_View):
        _translate = QtCore.QCoreApplication.translate
        Course_View.setWindowTitle(_translate("Course_View", "إضافة/تعديل دورة تدريبية"))
        self.name_label_2.setText(_translate("Course_View", "الاسم:"))
        self.department_label_2.setText(_translate("Course_View", "المقدم:"))
        self.job_title_label_2.setText(_translate("Course_View", "الكلفة:"))
        self.job_title_label_3.setText(_translate("Course_View", "الحساب:"))
        self.course_save_btn.setText(_translate("Course_View", "حفظ"))
        self.email_label_3.setText(_translate("Course_View", "المكان:"))
        self.email_label_2.setText(_translate("Course_View", "التاريخ:"))
        self.job_title_label_4.setText(_translate("Course_View", "الحساب المقابل:"))
        self.select_course_costs_opposite_account_btn.setText(_translate("Course_View", "🔎"))
        self.select_course_costs_account_btn.setText(_translate("Course_View", "🔎"))
