# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_CostCentersReport.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CostCentersReport(object):
    def setupUi(self, CostCentersReport):
        CostCentersReport.setObjectName("CostCentersReport")
        CostCentersReport.setWindowModality(QtCore.Qt.WindowModal)
        CostCentersReport.resize(1535, 901)
        CostCentersReport.setMinimumSize(QtCore.QSize(1535, 841))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/dispatch_order.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CostCentersReport.setWindowIcon(icon)
        CostCentersReport.setLayoutDirection(QtCore.Qt.RightToLeft)
        CostCentersReport.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(CostCentersReport)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_10 = QtWidgets.QGroupBox(CostCentersReport)
        self.groupBox_10.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_4 = QtWidgets.QLabel(self.groupBox_10)
        self.label_4.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_4.setObjectName("label_4")
        self.gridLayout_10.addWidget(self.label_4, 0, 0, 1, 1)
        self.from_date_input = QtWidgets.QDateEdit(self.groupBox_10)
        self.from_date_input.setCalendarPopup(True)
        self.from_date_input.setObjectName("from_date_input")
        self.gridLayout_10.addWidget(self.from_date_input, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_10)
        self.label_5.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_5.setObjectName("label_5")
        self.gridLayout_10.addWidget(self.label_5, 1, 0, 1, 1)
        self.to_date_input = QtWidgets.QDateEdit(self.groupBox_10)
        self.to_date_input.setCalendarPopup(True)
        self.to_date_input.setObjectName("to_date_input")
        self.gridLayout_10.addWidget(self.to_date_input, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_10, 0, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(CostCentersReport)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.source_period_start_material_checkbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.source_period_start_material_checkbox.setChecked(True)
        self.source_period_start_material_checkbox.setObjectName("source_period_start_material_checkbox")
        self.gridLayout_3.addWidget(self.source_period_start_material_checkbox, 0, 0, 1, 1)
        self.source_journal_checkbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.source_journal_checkbox.setChecked(True)
        self.source_journal_checkbox.setObjectName("source_journal_checkbox")
        self.gridLayout_3.addWidget(self.source_journal_checkbox, 1, 0, 1, 1)
        self.select_invoices_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.select_invoices_btn.setObjectName("select_invoices_btn")
        self.gridLayout_3.addWidget(self.select_invoices_btn, 2, 1, 1, 1)
        self.source_period_start_checkbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.source_period_start_checkbox.setChecked(True)
        self.source_period_start_checkbox.setObjectName("source_period_start_checkbox")
        self.gridLayout_3.addWidget(self.source_period_start_checkbox, 2, 0, 1, 1)
        self.source_manufacture_checkbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.source_manufacture_checkbox.setChecked(True)
        self.source_manufacture_checkbox.setObjectName("source_manufacture_checkbox")
        self.gridLayout_3.addWidget(self.source_manufacture_checkbox, 0, 1, 1, 1)
        self.source_loans_checkbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.source_loans_checkbox.setChecked(True)
        self.source_loans_checkbox.setObjectName("source_loans_checkbox")
        self.gridLayout_3.addWidget(self.source_loans_checkbox, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 0, 2, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(CostCentersReport)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 150))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_7.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.creditor_sum_table = QtWidgets.QTableWidget(self.groupBox_3)
        self.creditor_sum_table.setStyleSheet("QScrollBar:vertical {\n"
"    background-color: #f1f1f1;\n"
"    width: 12px;\n"
"    margin: 12px 0 12px 0;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: #888;\n"
"    min-height: 20px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background-color: #555;\n"
"}\n"
"\n"
"QTableWidget{background-color:rgb(224, 250, 255)}")
        self.creditor_sum_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.creditor_sum_table.setAlternatingRowColors(True)
        self.creditor_sum_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.creditor_sum_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.creditor_sum_table.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.creditor_sum_table.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.creditor_sum_table.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.creditor_sum_table.setObjectName("creditor_sum_table")
        self.creditor_sum_table.setColumnCount(3)
        self.creditor_sum_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.creditor_sum_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.creditor_sum_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.creditor_sum_table.setHorizontalHeaderItem(2, item)
        self.creditor_sum_table.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_7.addWidget(self.creditor_sum_table, 0, 0, 1, 1)
        self.debtor_sum_table = QtWidgets.QTableWidget(self.groupBox_3)
        self.debtor_sum_table.setStyleSheet("QScrollBar:vertical {\n"
"    background-color: #f1f1f1;\n"
"    width: 12px;\n"
"    margin: 12px 0 12px 0;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: #888;\n"
"    min-height: 20px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background-color: #555;\n"
"}\n"
"\n"
"QTableWidget{background-color:rgb(224, 250, 255)}")
        self.debtor_sum_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.debtor_sum_table.setAlternatingRowColors(True)
        self.debtor_sum_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.debtor_sum_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.debtor_sum_table.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.debtor_sum_table.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.debtor_sum_table.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.debtor_sum_table.setObjectName("debtor_sum_table")
        self.debtor_sum_table.setColumnCount(3)
        self.debtor_sum_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.debtor_sum_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.debtor_sum_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.debtor_sum_table.setHorizontalHeaderItem(2, item)
        self.debtor_sum_table.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_7.addWidget(self.debtor_sum_table, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 6, 0, 1, 4)
        self.groupBox_6 = QtWidgets.QGroupBox(CostCentersReport)
        self.groupBox_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_5.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label = QtWidgets.QLabel(self.groupBox_6)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_6)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 1, 1, 1, 1)
        self.creditor_accounts_tree = QtWidgets.QTreeWidget(self.groupBox_6)
        self.creditor_accounts_tree.setStyleSheet("QScrollBar:vertical {\n"
"    background-color: #f1f1f1;\n"
"    width: 12px;\n"
"    margin: 12px 0 12px 0;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: #888;\n"
"    min-height: 20px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background-color: #555;\n"
"}\n"
"\n"
"QTreeWidget{background-color:rgb(252, 255, 210);}")
        self.creditor_accounts_tree.setObjectName("creditor_accounts_tree")
        self.creditor_accounts_tree.headerItem().setTextAlignment(0, QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.creditor_accounts_tree.headerItem().setTextAlignment(1, QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.creditor_accounts_tree.headerItem().setText(2, "معرف الحساب")
        self.creditor_accounts_tree.headerItem().setTextAlignment(2, QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.creditor_accounts_tree.headerItem().setTextAlignment(3, QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.creditor_accounts_tree.headerItem().setTextAlignment(4, QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.gridLayout_5.addWidget(self.creditor_accounts_tree, 2, 0, 1, 1)
        self.debtor_accounts_tree = QtWidgets.QTreeWidget(self.groupBox_6)
        self.debtor_accounts_tree.setStyleSheet("QScrollBar:vertical {\n"
"    background-color: #f1f1f1;\n"
"    width: 12px;\n"
"    margin: 12px 0 12px 0;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: #888;\n"
"    min-height: 20px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background-color: #555;\n"
"}\n"
"\n"
"QTreeWidget{background-color:rgb(252, 255, 210);}")
        self.debtor_accounts_tree.setObjectName("debtor_accounts_tree")
        self.debtor_accounts_tree.headerItem().setTextAlignment(0, QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.debtor_accounts_tree.headerItem().setTextAlignment(1, QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.debtor_accounts_tree.headerItem().setText(2, "معرف الحساب")
        self.debtor_accounts_tree.headerItem().setTextAlignment(2, QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.debtor_accounts_tree.headerItem().setTextAlignment(3, QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.debtor_accounts_tree.headerItem().setTextAlignment(4, QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.gridLayout_5.addWidget(self.debtor_accounts_tree, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_6, 5, 0, 1, 4)
        self.groupBox_8 = QtWidgets.QGroupBox(CostCentersReport)
        self.groupBox_8.setMinimumSize(QtCore.QSize(0, 121))
        self.groupBox_8.setTitle("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.unified_currency_radio = QtWidgets.QRadioButton(self.groupBox_8)
        self.unified_currency_radio.setMaximumSize(QtCore.QSize(150, 16777215))
        self.unified_currency_radio.setChecked(False)
        self.unified_currency_radio.setObjectName("unified_currency_radio")
        self.gridLayout_9.addWidget(self.unified_currency_radio, 1, 0, 1, 1)
        self.currency_combobox = QtWidgets.QComboBox(self.groupBox_8)
        self.currency_combobox.setEnabled(True)
        self.currency_combobox.setObjectName("currency_combobox")
        self.gridLayout_9.addWidget(self.currency_combobox, 1, 1, 1, 1)
        self.distinct_currency_radio = QtWidgets.QRadioButton(self.groupBox_8)
        self.distinct_currency_radio.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.distinct_currency_radio.setChecked(True)
        self.distinct_currency_radio.setObjectName("distinct_currency_radio")
        self.gridLayout_9.addWidget(self.distinct_currency_radio, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_8, 2, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(CostCentersReport)
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 150))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_6.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.result_win_table = QtWidgets.QTableWidget(self.groupBox_4)
        self.result_win_table.setStyleSheet("QScrollBar:vertical {\n"
"    background-color: #f1f1f1;\n"
"    width: 12px;\n"
"    margin: 12px 0 12px 0;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: #888;\n"
"    min-height: 20px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background-color: #555;\n"
"}\n"
"\n"
"QTableWidget{background-color:rgb(214, 255, 225)}")
        self.result_win_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.result_win_table.setAlternatingRowColors(True)
        self.result_win_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.result_win_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.result_win_table.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.result_win_table.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.result_win_table.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.result_win_table.setObjectName("result_win_table")
        self.result_win_table.setColumnCount(3)
        self.result_win_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.result_win_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.result_win_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.result_win_table.setHorizontalHeaderItem(2, item)
        self.result_win_table.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_6.addWidget(self.result_win_table, 0, 0, 1, 1)
        self.result_loss_table = QtWidgets.QTableWidget(self.groupBox_4)
        self.result_loss_table.setStyleSheet("QScrollBar:vertical {\n"
"    background-color: #f1f1f1;\n"
"    width: 12px;\n"
"    margin: 12px 0 12px 0;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: #888;\n"
"    min-height: 20px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background-color: #555;\n"
"}\n"
"\n"
"QTableWidget{background-color:rgb(214, 255, 225)}")
        self.result_loss_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.result_loss_table.setAlternatingRowColors(True)
        self.result_loss_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.result_loss_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.result_loss_table.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.result_loss_table.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.result_loss_table.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.result_loss_table.setObjectName("result_loss_table")
        self.result_loss_table.setColumnCount(3)
        self.result_loss_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.result_loss_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.result_loss_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.result_loss_table.setHorizontalHeaderItem(2, item)
        self.result_loss_table.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_6.addWidget(self.result_loss_table, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_4, 7, 0, 1, 4)
        self.groupBox_7 = QtWidgets.QGroupBox(CostCentersReport)
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.distinct_exchange_date_radio = QtWidgets.QRadioButton(self.groupBox_7)
        self.distinct_exchange_date_radio.setObjectName("distinct_exchange_date_radio")
        self.gridLayout_8.addWidget(self.distinct_exchange_date_radio, 1, 0, 1, 2)
        self.unified_exchange_date_radio = QtWidgets.QRadioButton(self.groupBox_7)
        self.unified_exchange_date_radio.setChecked(True)
        self.unified_exchange_date_radio.setObjectName("unified_exchange_date_radio")
        self.gridLayout_8.addWidget(self.unified_exchange_date_radio, 0, 0, 1, 1)
        self.exchange_date_input = QtWidgets.QDateEdit(self.groupBox_7)
        self.exchange_date_input.setObjectName("exchange_date_input")
        self.gridLayout_8.addWidget(self.exchange_date_input, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_7, 2, 2, 1, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(CostCentersReport)
        self.groupBox_9.setMaximumSize(QtCore.QSize(700, 16777215))
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cost_centers_tree = QtWidgets.QTreeWidget(self.groupBox_9)
        self.cost_centers_tree.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cost_centers_tree.setObjectName("cost_centers_tree")
        self.cost_centers_tree.header().setStretchLastSection(True)
        self.gridLayout_2.addWidget(self.cost_centers_tree, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_9, 0, 0, 3, 1)
        self.calculate_btn = QtWidgets.QPushButton(CostCentersReport)
        self.calculate_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.calculate_btn.setObjectName("calculate_btn")
        self.gridLayout.addWidget(self.calculate_btn, 2, 3, 1, 1)

        self.retranslateUi(CostCentersReport)
        QtCore.QMetaObject.connectSlotsByName(CostCentersReport)

    def retranslateUi(self, CostCentersReport):
        _translate = QtCore.QCoreApplication.translate
        CostCentersReport.setWindowTitle(_translate("CostCentersReport", "تقارير مراكز كلفة"))
        self.groupBox_10.setTitle(_translate("CostCentersReport", "التواريخ"))
        self.label_4.setText(_translate("CostCentersReport", "من:"))
        self.from_date_input.setDisplayFormat(_translate("CostCentersReport", "d/M/yyyy"))
        self.label_5.setText(_translate("CostCentersReport", "إلى:"))
        self.to_date_input.setDisplayFormat(_translate("CostCentersReport", "d/M/yyyy"))
        self.groupBox_2.setTitle(_translate("CostCentersReport", "المصادر"))
        self.source_period_start_material_checkbox.setText(_translate("CostCentersReport", "بضاعة أول المدة"))
        self.source_journal_checkbox.setText(_translate("CostCentersReport", "سندات القيد"))
        self.select_invoices_btn.setText(_translate("CostCentersReport", "...فواتير"))
        self.source_period_start_checkbox.setText(_translate("CostCentersReport", "القيود الافتتاحية"))
        self.source_manufacture_checkbox.setText(_translate("CostCentersReport", " عمليات التصنيع"))
        self.source_loans_checkbox.setText(_translate("CostCentersReport", "القروض"))
        self.groupBox_3.setTitle(_translate("CostCentersReport", "المجموع"))
        item = self.creditor_sum_table.horizontalHeaderItem(0)
        item.setText(_translate("CostCentersReport", "معرف العملة"))
        item = self.creditor_sum_table.horizontalHeaderItem(1)
        item.setText(_translate("CostCentersReport", "العملة"))
        item = self.creditor_sum_table.horizontalHeaderItem(2)
        item.setText(_translate("CostCentersReport", "القيمة"))
        item = self.debtor_sum_table.horizontalHeaderItem(0)
        item.setText(_translate("CostCentersReport", "معرف العملة"))
        item = self.debtor_sum_table.horizontalHeaderItem(1)
        item.setText(_translate("CostCentersReport", "العملة"))
        item = self.debtor_sum_table.horizontalHeaderItem(2)
        item.setText(_translate("CostCentersReport", "القيمة"))
        self.groupBox_6.setTitle(_translate("CostCentersReport", "التفصيل"))
        self.label.setText(_translate("CostCentersReport", "دائن"))
        self.label_2.setText(_translate("CostCentersReport", "مدين"))
        self.creditor_accounts_tree.headerItem().setText(0, _translate("CostCentersReport", "معرف العملة"))
        self.creditor_accounts_tree.headerItem().setText(1, _translate("CostCentersReport", "العملة"))
        self.creditor_accounts_tree.headerItem().setText(3, _translate("CostCentersReport", "الحساب"))
        self.creditor_accounts_tree.headerItem().setText(4, _translate("CostCentersReport", "القيمة"))
        self.creditor_accounts_tree.headerItem().setText(5, _translate("CostCentersReport", "البيان"))
        self.debtor_accounts_tree.headerItem().setText(0, _translate("CostCentersReport", "معرف العملة"))
        self.debtor_accounts_tree.headerItem().setText(1, _translate("CostCentersReport", "العملة"))
        self.debtor_accounts_tree.headerItem().setText(3, _translate("CostCentersReport", "الحساب"))
        self.debtor_accounts_tree.headerItem().setText(4, _translate("CostCentersReport", "القيمة"))
        self.debtor_accounts_tree.headerItem().setText(5, _translate("CostCentersReport", "البيان"))
        self.unified_currency_radio.setText(_translate("CostCentersReport", "استخدام عملة واحدة"))
        self.distinct_currency_radio.setText(_translate("CostCentersReport", "حساب كل عملة  على حدى"))
        self.groupBox_4.setTitle(_translate("CostCentersReport", "الربح"))
        item = self.result_win_table.horizontalHeaderItem(0)
        item.setText(_translate("CostCentersReport", "معرف العملة"))
        item = self.result_win_table.horizontalHeaderItem(1)
        item.setText(_translate("CostCentersReport", "العملة"))
        item = self.result_win_table.horizontalHeaderItem(2)
        item.setText(_translate("CostCentersReport", "القيمة"))
        item = self.result_loss_table.horizontalHeaderItem(0)
        item.setText(_translate("CostCentersReport", "معرف العملة"))
        item = self.result_loss_table.horizontalHeaderItem(1)
        item.setText(_translate("CostCentersReport", "العملة"))
        item = self.result_loss_table.horizontalHeaderItem(2)
        item.setText(_translate("CostCentersReport", "القيمة"))
        self.distinct_exchange_date_radio.setText(_translate("CostCentersReport", "اعتماد التاريخ الخاص بكل سجل قيد كتاريخ لتعادل العملة"))
        self.unified_exchange_date_radio.setText(_translate("CostCentersReport", ":اعتماد تعادل العملة في التاريخ التالي"))
        self.groupBox_9.setTitle(_translate("CostCentersReport", "مركز الكلفة"))
        self.cost_centers_tree.headerItem().setText(0, _translate("CostCentersReport", "اسم مركز الكلفة"))
        self.cost_centers_tree.headerItem().setText(1, _translate("CostCentersReport", "معرف مركز الكلفة"))
        self.calculate_btn.setText(_translate("CostCentersReport", "حساب"))
