# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_DatabaseNew.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DatabaseNew(object):
    def setupUi(self, DatabaseNew):
        DatabaseNew.setObjectName("DatabaseNew")
        DatabaseNew.resize(408, 77)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("graphics/icon.xpm"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DatabaseNew.setWindowIcon(icon)
        DatabaseNew.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.gridLayout = QtWidgets.QGridLayout(DatabaseNew)
        self.gridLayout.setObjectName("gridLayout")
        self.db_name_input = QtWidgets.QLineEdit(DatabaseNew)
        self.db_name_input.setObjectName("db_name_input")
        self.gridLayout.addWidget(self.db_name_input, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(DatabaseNew)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.create_btn = QtWidgets.QPushButton(DatabaseNew)
        self.create_btn.setObjectName("create_btn")
        self.gridLayout.addWidget(self.create_btn, 0, 3, 1, 1)

        self.retranslateUi(DatabaseNew)
        QtCore.QMetaObject.connectSlotsByName(DatabaseNew)

    def retranslateUi(self, DatabaseNew):
        _translate = QtCore.QCoreApplication.translate
        DatabaseNew.setWindowTitle(_translate("DatabaseNew", "إنشاء قاعدة بيانات جديدة"))
        self.label.setText(_translate("DatabaseNew", "اسم قاعدة البيانات:"))
        self.create_btn.setText(_translate("DatabaseNew", "إنشاء"))
