# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_DatabaseSettings.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DatabaseSettings(object):
    def setupUi(self, DatabaseSettings):
        DatabaseSettings.setObjectName("DatabaseSettings")
        DatabaseSettings.resize(496, 376)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/connect_to_database.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DatabaseSettings.setWindowIcon(icon)
        DatabaseSettings.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.gridLayout = QtWidgets.QGridLayout(DatabaseSettings)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(DatabaseSettings)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.username_input = QtWidgets.QLineEdit(DatabaseSettings)
        self.username_input.setObjectName("username_input")
        self.gridLayout.addWidget(self.username_input, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(DatabaseSettings)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.new_db_btn = QtWidgets.QPushButton(DatabaseSettings)
        self.new_db_btn.setObjectName("new_db_btn")
        self.gridLayout.addWidget(self.new_db_btn, 8, 7, 1, 2)
        self.connect_db_btn = QtWidgets.QPushButton(DatabaseSettings)
        self.connect_db_btn.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:1.863, fx:0.5, fy:0.5, stop:0 rgba(0, 183, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color:rgb(255, 255, 255);")
        self.connect_db_btn.setObjectName("connect_db_btn")
        self.gridLayout.addWidget(self.connect_db_btn, 8, 1, 1, 1)
        self.delete_db_btn = QtWidgets.QPushButton(DatabaseSettings)
        self.delete_db_btn.setStyleSheet("background-color:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:1.863, fx:0.5, fy:0.5, stop:0 rgba(255, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(255, 255, 255);")
        self.delete_db_btn.setObjectName("delete_db_btn")
        self.gridLayout.addWidget(self.delete_db_btn, 8, 3, 1, 1)
        self.databases_list = QtWidgets.QListWidget(DatabaseSettings)
        self.databases_list.setObjectName("databases_list")
        self.gridLayout.addWidget(self.databases_list, 6, 1, 2, 8)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 8, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 200, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 7, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 8, 6, 1, 1)
        self.label_4 = QtWidgets.QLabel(DatabaseSettings)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(DatabaseSettings)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.password_input = QtWidgets.QLineEdit(DatabaseSettings)
        self.password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_input.setObjectName("password_input")
        self.gridLayout.addWidget(self.password_input, 4, 1, 1, 1)
        self.port_input = QtWidgets.QLineEdit(DatabaseSettings)
        self.port_input.setObjectName("port_input")
        self.gridLayout.addWidget(self.port_input, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(DatabaseSettings)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)
        self.server_input = QtWidgets.QLineEdit(DatabaseSettings)
        self.server_input.setObjectName("server_input")
        self.gridLayout.addWidget(self.server_input, 0, 1, 1, 1)
        self.connect_btn = QtWidgets.QPushButton(DatabaseSettings)
        self.connect_btn.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.connect_btn.setObjectName("connect_btn")
        self.gridLayout.addWidget(self.connect_btn, 5, 1, 1, 1)
        self.password_btn = QtWidgets.QPushButton(DatabaseSettings)
        self.password_btn.setMaximumSize(QtCore.QSize(20, 16777215))
        self.password_btn.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: black;\n"
"    font-size: 24px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 0, 0, 0.1);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 0.2);\n"
"}")
        self.password_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/eye_closed.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.password_btn.setIcon(icon1)
        self.password_btn.setObjectName("password_btn")
        self.gridLayout.addWidget(self.password_btn, 4, 3, 1, 1)

        self.retranslateUi(DatabaseSettings)
        QtCore.QMetaObject.connectSlotsByName(DatabaseSettings)

    def retranslateUi(self, DatabaseSettings):
        _translate = QtCore.QCoreApplication.translate
        # DatabaseSettings.setWindowTitle(_translate("DatabaseSettings", "الاتصال بقاعدة بيانات بعيدة"))
        self.label_2.setText(_translate("DatabaseSettings", "المنفذ:"))
        self.username_input.setText(_translate("DatabaseSettings", "root"))
        self.label.setText(_translate("DatabaseSettings", "المخدم:"))
        self.new_db_btn.setText(_translate("DatabaseSettings", "قاعدة بيانات جديدة"))
        self.connect_db_btn.setText(_translate("DatabaseSettings", "اتصال"))
        self.delete_db_btn.setText(_translate("DatabaseSettings", "حذف"))
        self.label_4.setText(_translate("DatabaseSettings", "كلمة المرور:"))
        self.label_3.setText(_translate("DatabaseSettings", "اسم المستخدم:"))
        self.password_input.setText(_translate("DatabaseSettings", "root"))
        self.port_input.setText(_translate("DatabaseSettings", "3306"))
        self.label_5.setText(_translate("DatabaseSettings", "قواعد البيانات:"))
        self.server_input.setText(_translate("DatabaseSettings", "localhost"))
        self.connect_btn.setText(_translate("DatabaseSettings", "اتصال بالمخدم"))
