# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_DataPicker.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DataPicker(object):
    def setupUi(self, DataPicker):
        DataPicker.setObjectName("DataPicker")
        DataPicker.resize(831, 520)
        DataPicker.setMinimumSize(QtCore.QSize(645, 503))
        self.gridLayout_2 = QtWidgets.QGridLayout(DataPicker)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cancel_btn = QtWidgets.QPushButton(DataPicker)
        self.cancel_btn.setObjectName("cancel_btn")
        self.gridLayout_2.addWidget(self.cancel_btn, 2, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(DataPicker)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 68))
        self.groupBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.search_input = QtWidgets.QLineEdit(self.groupBox)
        self.search_input.setObjectName("search_input")
        self.horizontalLayout.addWidget(self.search_input)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 4)
        spacerItem = QtWidgets.QSpacerItem(558, 25, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 2, 2, 1, 2)
        self.save_btn = QtWidgets.QPushButton(DataPicker)
        self.save_btn.setObjectName("save_btn")
        self.gridLayout_2.addWidget(self.save_btn, 2, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(DataPicker)
        self.groupBox_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.result_table = QtWidgets.QTableWidget(self.groupBox_2)
        self.result_table.setObjectName("result_table")
        self.result_table.setColumnCount(0)
        self.result_table.setRowCount(0)
        self.horizontalLayout_2.addWidget(self.result_table)
        self.linked_table = QtWidgets.QTableWidget(self.groupBox_2)
        self.linked_table.setObjectName("linked_table")
        self.linked_table.setColumnCount(0)
        self.linked_table.setRowCount(0)
        self.horizontalLayout_2.addWidget(self.linked_table)
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 0, 1, 4)

        self.retranslateUi(DataPicker)
        QtCore.QMetaObject.connectSlotsByName(DataPicker)

    def retranslateUi(self, DataPicker):
        _translate = QtCore.QCoreApplication.translate
        DataPicker.setWindowTitle(_translate("DataPicker", "Data Picker"))
        self.cancel_btn.setText(_translate("DataPicker", "الغاء"))
        self.groupBox.setTitle(_translate("DataPicker", "البحث"))
        self.save_btn.setText(_translate("DataPicker", "حفظ"))
