# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_DamagedMaterial_Report.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DamagedMaterial_Report(object):
    def setupUi(self, DamagedMaterial_Report):
        DamagedMaterial_Report.setObjectName("DamagedMaterial_Report")
        DamagedMaterial_Report.setWindowModality(QtCore.Qt.WindowModal)
        DamagedMaterial_Report.resize(1238, 538)
        DamagedMaterial_Report.setLayoutDirection(QtCore.Qt.RightToLeft)
        DamagedMaterial_Report.setModal(True)
        self.gridLayout_2 = QtWidgets.QGridLayout(DamagedMaterial_Report)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_3 = QtWidgets.QGroupBox(DamagedMaterial_Report)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.clients_table = QtWidgets.QTableWidget(self.groupBox_3)
        self.clients_table.setObjectName("clients_table")
        self.clients_table.setColumnCount(3)
        self.clients_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.clients_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.clients_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.clients_table.setHorizontalHeaderItem(2, item)
        self.gridLayout_3.addWidget(self.clients_table, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_3, 1, 0, 1, 2)
        self.export_btn = QtWidgets.QPushButton(DamagedMaterial_Report)
        self.export_btn.setMaximumSize(QtCore.QSize(1677750, 16777215))
        self.export_btn.setObjectName("export_btn")
        self.gridLayout_2.addWidget(self.export_btn, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(1136, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 2, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(DamagedMaterial_Report)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem1 = QtWidgets.QSpacerItem(764, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 7, 1, 1)
        self.material_combobox = QtWidgets.QComboBox(self.groupBox)
        self.material_combobox.setStyleSheet("QComboBox {\n"
"        background-color: #fafafa;\n"
"        border: 1px solid lightgrey;        \n"
"        height: 22px;\n"
"        color: black;\n"
"    }\n"
"    QComboBox::drop-down {\n"
"        border: none;\n"
"    }")
        self.material_combobox.setObjectName("material_combobox")
        self.gridLayout.addWidget(self.material_combobox, 0, 1, 1, 1)
        self.select_material_btn = QtWidgets.QToolButton(self.groupBox)
        self.select_material_btn.setObjectName("select_material_btn")
        self.gridLayout.addWidget(self.select_material_btn, 0, 2, 1, 1)
        self.manufacture_combobox = QtWidgets.QComboBox(self.groupBox)
        self.manufacture_combobox.setMinimumSize(QtCore.QSize(100, 0))
        self.manufacture_combobox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.manufacture_combobox.setStyleSheet("QComboBox {\n"
"        background-color: #fafafa;\n"
"        border: 1px solid lightgrey;        \n"
"        height: 22px;\n"
"        color: black;\n"
"    }\n"
"    QComboBox::drop-down {\n"
"        border: none;\n"
"    }")
        self.manufacture_combobox.setObjectName("manufacture_combobox")
        self.gridLayout.addWidget(self.manufacture_combobox, 0, 4, 1, 1)
        self.select_manufacture_btn = QtWidgets.QToolButton(self.groupBox)
        self.select_manufacture_btn.setObjectName("select_manufacture_btn")
        self.gridLayout.addWidget(self.select_manufacture_btn, 0, 5, 1, 1)
        self.calc_btn = QtWidgets.QPushButton(self.groupBox)
        self.calc_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.calc_btn.setObjectName("calc_btn")
        self.gridLayout.addWidget(self.calc_btn, 0, 6, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 3, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 2)

        self.retranslateUi(DamagedMaterial_Report)
        QtCore.QMetaObject.connectSlotsByName(DamagedMaterial_Report)

    def retranslateUi(self, DamagedMaterial_Report):
        _translate = QtCore.QCoreApplication.translate
        DamagedMaterial_Report.setWindowTitle(_translate("DamagedMaterial_Report", "تقرير هدف المبيعات"))
        item = self.clients_table.horizontalHeaderItem(0)
        item.setText(_translate("DamagedMaterial_Report", "القسم"))
        item = self.clients_table.horizontalHeaderItem(1)
        item.setText(_translate("DamagedMaterial_Report", "المبلغ"))
        item = self.clients_table.horizontalHeaderItem(2)
        item.setText(_translate("DamagedMaterial_Report", "المتوسط"))
        self.export_btn.setText(_translate("DamagedMaterial_Report", "تصدير"))
        self.select_material_btn.setText(_translate("DamagedMaterial_Report", "🔎"))
        self.select_manufacture_btn.setText(_translate("DamagedMaterial_Report", "🔎"))
        self.calc_btn.setText(_translate("DamagedMaterial_Report", "عرض"))
        self.label_2.setText(_translate("DamagedMaterial_Report", "المادة:"))
        self.label_3.setText(_translate("DamagedMaterial_Report", "عملية التصنيع:"))
