# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_DBPassword.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DBPassword(object):
    def setupUi(self, DBPassword):
        DBPassword.setObjectName("DBPassword")
        DBPassword.setWindowModality(QtCore.Qt.WindowModal)
        DBPassword.resize(391, 138)
        DBPassword.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.gridLayout = QtWidgets.QGridLayout(DBPassword)
        self.gridLayout.setObjectName("gridLayout")
        self.password_input = QtWidgets.QLineEdit(DBPassword)
        self.password_input.setObjectName("password_input")
        self.gridLayout.addWidget(self.password_input, 2, 0, 1, 1)
        self.password_toggle = QtWidgets.QPushButton(DBPassword)
        self.password_toggle.setMaximumSize(QtCore.QSize(20, 16777215))
        self.password_toggle.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: black;\n"
"    font-size: 24px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 0, 0, 0.1);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 0.2);\n"
"}")
        self.password_toggle.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/eye_closed.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.password_toggle.setIcon(icon)
        self.password_toggle.setObjectName("password_toggle")
        self.gridLayout.addWidget(self.password_toggle, 2, 1, 1, 1)
        self.save_btn = QtWidgets.QPushButton(DBPassword)
        self.save_btn.setObjectName("save_btn")
        self.gridLayout.addWidget(self.save_btn, 4, 0, 1, 1)
        self.info_label = QtWidgets.QLabel(DBPassword)
        self.info_label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.info_label.setObjectName("info_label")
        self.gridLayout.addWidget(self.info_label, 1, 0, 1, 1)

        self.retranslateUi(DBPassword)
        QtCore.QMetaObject.connectSlotsByName(DBPassword)

    def retranslateUi(self, DBPassword):
        _translate = QtCore.QCoreApplication.translate
        DBPassword.setWindowTitle(_translate("DBPassword", "تغيير كلمة المرور"))
        self.save_btn.setText(_translate("DBPassword", "موافق"))
        self.info_label.setText(_translate("DBPassword", "تم إنشاء مستخدم مالك لقاعدة البيانات, الرجاء ادخال كلمة مرور"))
