# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_DatabaseBackup.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DatabaseBackupRestore(object):
    def setupUi(self, DatabaseBackupRestore):
        DatabaseBackupRestore.setObjectName("DatabaseBackupRestore")
        DatabaseBackupRestore.resize(394, 267)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("graphics/icon.xpm"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DatabaseBackupRestore.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(DatabaseBackupRestore)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(DatabaseBackupRestore)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 80))
        self.groupBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.backup_btn = QtWidgets.QPushButton(self.groupBox)
        self.backup_btn.setMaximumSize(QtCore.QSize(250, 29))
        self.backup_btn.setObjectName("backup_btn")
        self.gridLayout_2.addWidget(self.backup_btn, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(DatabaseBackupRestore)
        self.groupBox_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.restorefilepath_input = QtWidgets.QLineEdit(self.groupBox_2)
        self.restorefilepath_input.setEnabled(True)
        self.restorefilepath_input.setObjectName("restorefilepath_input")
        self.gridLayout_3.addWidget(self.restorefilepath_input, 0, 2, 1, 1)
        self.restore_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.restore_btn.setObjectName("restore_btn")
        self.gridLayout_3.addWidget(self.restore_btn, 0, 4, 1, 1)
        self.filepick_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.filepick_btn.setObjectName("filepick_btn")
        self.gridLayout_3.addWidget(self.filepick_btn, 0, 3, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(DatabaseBackupRestore)
        self.groupBox_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.mysqlpath_input = QtWidgets.QLineEdit(self.groupBox_3)
        self.mysqlpath_input.setEnabled(True)
        self.mysqlpath_input.setObjectName("mysqlpath_input")
        self.gridLayout_4.addWidget(self.mysqlpath_input, 0, 1, 1, 1)
        self.mysqlpath_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.mysqlpath_btn.setObjectName("mysqlpath_btn")
        self.gridLayout_4.addWidget(self.mysqlpath_btn, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 2, 0, 1, 1)

        self.retranslateUi(DatabaseBackupRestore)
        QtCore.QMetaObject.connectSlotsByName(DatabaseBackupRestore)

    def retranslateUi(self, DatabaseBackupRestore):
        _translate = QtCore.QCoreApplication.translate
        # DatabaseBackupRestore.setWindowTitle(_translate("DatabaseBackupRestore", "النسخ الاحتياطي والاستعادة لقاعدة البيانات"))
        self.groupBox.setTitle(_translate("DatabaseBackupRestore", "نسخ"))
        self.backup_btn.setText(_translate("DatabaseBackupRestore", "حفظ نسخة احتياطية من قاعدة البيانات"))
        self.groupBox_2.setTitle(_translate("DatabaseBackupRestore", "استعادة"))
        self.restore_btn.setText(_translate("DatabaseBackupRestore", "استعادة"))
        self.filepick_btn.setText(_translate("DatabaseBackupRestore", "...اختيار ملف"))
        self.groupBox_3.setTitle(_translate("DatabaseBackupRestore", "الضبط"))
        self.mysqlpath_btn.setText(_translate("DatabaseBackupRestore", "تحديد المسار"))
        self.label.setText(_translate("DatabaseBackupRestore", "مسار SQL:"))
