# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_ExpensesSettings.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ExpensesSettings(object):
    def setupUi(self, ExpensesSettings):
        ExpensesSettings.setObjectName("ExpensesSettings")
        ExpensesSettings.resize(529, 392)
        ExpensesSettings.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.gridLayout = QtWidgets.QGridLayout(ExpensesSettings)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(ExpensesSettings)
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.expenses_types_table = QtWidgets.QTableWidget(ExpensesSettings)
        self.expenses_types_table.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.expenses_types_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.expenses_types_table.setProperty("showDropIndicator", False)
        self.expenses_types_table.setDragEnabled(False)
        self.expenses_types_table.setDragDropOverwriteMode(False)
        self.expenses_types_table.setAlternatingRowColors(True)
        self.expenses_types_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.expenses_types_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.expenses_types_table.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.expenses_types_table.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.expenses_types_table.setObjectName("expenses_types_table")
        self.expenses_types_table.setColumnCount(7)
        self.expenses_types_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.expenses_types_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.expenses_types_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.expenses_types_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.expenses_types_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.expenses_types_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.expenses_types_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.expenses_types_table.setHorizontalHeaderItem(6, item)
        self.expenses_types_table.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.expenses_types_table, 6, 0, 1, 5)
        self.label_3 = QtWidgets.QLabel(ExpensesSettings)
        self.label_3.setMaximumSize(QtCore.QSize(99999, 16777215))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(131, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 7, 1, 1, 2)
        self.delete_expense_btn = QtWidgets.QPushButton(ExpensesSettings)
        self.delete_expense_btn.setObjectName("delete_expense_btn")
        self.gridLayout.addWidget(self.delete_expense_btn, 7, 4, 1, 1)
        self.opposite_accounts_combobox = QtWidgets.QComboBox(ExpensesSettings)
        self.opposite_accounts_combobox.setStyleSheet("QComboBox {\n"
"        background-color: #fafafa;\n"
"        border: 1px solid lightgrey;        \n"
"        height: 22px;\n"
"        color: black;\n"
"    }\n"
"    QComboBox::drop-down {\n"
"        border: none;\n"
"    }")
        self.opposite_accounts_combobox.setObjectName("opposite_accounts_combobox")
        self.gridLayout.addWidget(self.opposite_accounts_combobox, 4, 2, 1, 1)
        self.name_input = QtWidgets.QLineEdit(ExpensesSettings)
        self.name_input.setObjectName("name_input")
        self.gridLayout.addWidget(self.name_input, 1, 2, 1, 1)
        self.calculated_in_manufacture_checkbox = QtWidgets.QCheckBox(ExpensesSettings)
        self.calculated_in_manufacture_checkbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.calculated_in_manufacture_checkbox.setObjectName("calculated_in_manufacture_checkbox")
        self.gridLayout.addWidget(self.calculated_in_manufacture_checkbox, 5, 0, 1, 1)
        self.accounts_combobox = QtWidgets.QComboBox(ExpensesSettings)
        self.accounts_combobox.setStyleSheet("QComboBox {\n"
"        background-color: #fafafa;\n"
"        border: 1px solid lightgrey;        \n"
"        height: 22px;\n"
"        color: black;\n"
"    }\n"
"    QComboBox::drop-down {\n"
"        border: none;\n"
"    }")
        self.accounts_combobox.setObjectName("accounts_combobox")
        self.gridLayout.addWidget(self.accounts_combobox, 2, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(ExpensesSettings)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.select_accounts_btn = QtWidgets.QToolButton(ExpensesSettings)
        self.select_accounts_btn.setObjectName("select_accounts_btn")
        self.gridLayout.addWidget(self.select_accounts_btn, 2, 3, 1, 1)
        self.select_opposite_accounts_btn = QtWidgets.QToolButton(ExpensesSettings)
        self.select_opposite_accounts_btn.setObjectName("select_opposite_accounts_btn")
        self.gridLayout.addWidget(self.select_opposite_accounts_btn, 4, 3, 1, 1)
        self.add_expense_btn = QtWidgets.QPushButton(ExpensesSettings)
        self.add_expense_btn.setObjectName("add_expense_btn")
        self.gridLayout.addWidget(self.add_expense_btn, 5, 4, 1, 1)

        self.retranslateUi(ExpensesSettings)
        QtCore.QMetaObject.connectSlotsByName(ExpensesSettings)

    def retranslateUi(self, ExpensesSettings):
        _translate = QtCore.QCoreApplication.translate
        ExpensesSettings.setWindowTitle(_translate("ExpensesSettings", "أنواع المصاريف"))
        self.label.setText(_translate("ExpensesSettings", "اسم المصروف:"))
        item = self.expenses_types_table.horizontalHeaderItem(0)
        item.setText(_translate("ExpensesSettings", "المعرف"))
        item = self.expenses_types_table.horizontalHeaderItem(1)
        item.setText(_translate("ExpensesSettings", "الاسم"))
        item = self.expenses_types_table.horizontalHeaderItem(2)
        item.setText(_translate("ExpensesSettings", "معرف الحساب"))
        item = self.expenses_types_table.horizontalHeaderItem(3)
        item.setText(_translate("ExpensesSettings", "الحساب"))
        item = self.expenses_types_table.horizontalHeaderItem(4)
        item.setText(_translate("ExpensesSettings", "معرف الحساب المقابل"))
        item = self.expenses_types_table.horizontalHeaderItem(5)
        item.setText(_translate("ExpensesSettings", "الحساب المقابل"))
        item = self.expenses_types_table.horizontalHeaderItem(6)
        item.setText(_translate("ExpensesSettings", "يدخل في مصاريف التصنيع"))
        self.label_3.setText(_translate("ExpensesSettings", "الحساب المقابل الافتراضي:"))
        self.delete_expense_btn.setText(_translate("ExpensesSettings", "حذف"))
        self.calculated_in_manufacture_checkbox.setText(_translate("ExpensesSettings", "يدخل في مصاريف التصنيع"))
        self.label_2.setText(_translate("ExpensesSettings", "الحساب الافتراضي:"))
        self.select_accounts_btn.setText(_translate("ExpensesSettings", "..."))
        self.select_opposite_accounts_btn.setText(_translate("ExpensesSettings", "..."))
        self.add_expense_btn.setText(_translate("ExpensesSettings", "إضافة"))
