# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_EditFinancialStatementBlock.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditFinancialStatementBlock(object):
    def setupUi(self, EditFinancialStatementBlock):
        EditFinancialStatementBlock.setObjectName("EditFinancialStatementBlock")
        EditFinancialStatementBlock.resize(350, 180)
        EditFinancialStatementBlock.setMinimumSize(QtCore.QSize(350, 180))
        EditFinancialStatementBlock.setMaximumSize(QtCore.QSize(350, 180))
        EditFinancialStatementBlock.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.gridLayout = QtWidgets.QGridLayout(EditFinancialStatementBlock)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(EditFinancialStatementBlock)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.block_name = QtWidgets.QLineEdit(self.groupBox)
        self.block_name.setObjectName("block_name")
        self.gridLayout_2.addWidget(self.block_name, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.save_btn = QtWidgets.QPushButton(self.groupBox)
        self.save_btn.setObjectName("save_btn")
        self.gridLayout_2.addWidget(self.save_btn, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(EditFinancialStatementBlock)
        QtCore.QMetaObject.connectSlotsByName(EditFinancialStatementBlock)

    def retranslateUi(self, EditFinancialStatementBlock):
        _translate = QtCore.QCoreApplication.translate
        EditFinancialStatementBlock.setWindowTitle(_translate("EditFinancialStatementBlock", "تعديل تبويب القائمة المالية"))
        self.label.setText(_translate("EditFinancialStatementBlock", "اسم التبويب:"))
        self.save_btn.setText(_translate("EditFinancialStatementBlock", "حفظ"))
