# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_EditMaterialInWarehouse.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditMaterialInWarehouse(object):
    def setupUi(self, EditMaterialInWarehouse):
        EditMaterialInWarehouse.setObjectName("EditMaterialInWarehouse")
        EditMaterialInWarehouse.resize(400, 150)
        EditMaterialInWarehouse.setMinimumSize(QtCore.QSize(400, 150))
        EditMaterialInWarehouse.setMaximumSize(QtCore.QSize(400, 200))
        self.gridLayout_2 = QtWidgets.QGridLayout(EditMaterialInWarehouse)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(EditMaterialInWarehouse)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 1, 1, 1)
        self.quantity_input = QtWidgets.QLineEdit(self.groupBox)
        self.quantity_input.setObjectName("quantity_input")
        self.gridLayout.addWidget(self.quantity_input, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.units_combobox = QtWidgets.QComboBox(self.groupBox)
        self.units_combobox.setObjectName("units_combobox")
        self.gridLayout.addWidget(self.units_combobox, 2, 0, 1, 1)
        self.name_input = QtWidgets.QLineEdit(self.groupBox)
        self.name_input.setEnabled(False)
        self.name_input.setObjectName("name_input")
        self.gridLayout.addWidget(self.name_input, 0, 0, 1, 1)
        self.save_btn = QtWidgets.QPushButton(self.groupBox)
        self.save_btn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.save_btn.setObjectName("save_btn")
        self.gridLayout.addWidget(self.save_btn, 3, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(EditMaterialInWarehouse)
        QtCore.QMetaObject.connectSlotsByName(EditMaterialInWarehouse)

    def retranslateUi(self, EditMaterialInWarehouse):
        _translate = QtCore.QCoreApplication.translate
        EditMaterialInWarehouse.setWindowTitle(_translate("EditMaterialInWarehouse", "تعديل مادة مستودع"))
        self.label_5.setText(_translate("EditMaterialInWarehouse", "الواحدة:"))
        self.label_2.setText(_translate("EditMaterialInWarehouse", "الكمية:"))
        self.label.setText(_translate("EditMaterialInWarehouse", "المادة:"))
        self.save_btn.setText(_translate("EditMaterialInWarehouse", "حفظ"))
