# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Groups.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Groups(object):
    def setupUi(self, Groups):
        Groups.setObjectName("Groups")
        Groups.setWindowModality(QtCore.Qt.WindowModal)
        Groups.resize(578, 488)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/set_parent.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Groups.setWindowIcon(icon)
        Groups.setLayoutDirection(QtCore.Qt.RightToLeft)
        Groups.setStyleSheet(" QPushButton {\n"
"        background-color: red;\n"
"        color: white;\n"
"        border-radius: 4px;\n"
"        padding: 8px 16px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #1565C0;\n"
"    }\n"
"    QPushButton:pressed {\n"
"        background-color: #0D47A1;\n"
"    }")
        Groups.setModal(True)
        self.gridLayout_3 = QtWidgets.QGridLayout(Groups)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox = QtWidgets.QGroupBox(Groups)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groups_tree = QtWidgets.QTreeWidget(self.groupBox)
        self.groups_tree.setObjectName("groups_tree")
        self.gridLayout_2.addWidget(self.groups_tree, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Groups)
        self.groupBox_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.add_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.add_btn.setObjectName("add_btn")
        self.gridLayout.addWidget(self.add_btn, 0, 0, 1, 1)
        self.delete_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.delete_btn.setObjectName("delete_btn")
        self.gridLayout.addWidget(self.delete_btn, 0, 2, 1, 1)
        self.edit_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.edit_btn.setObjectName("edit_btn")
        self.gridLayout.addWidget(self.edit_btn, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 1, 0, 1, 1)

        self.retranslateUi(Groups)
        QtCore.QMetaObject.connectSlotsByName(Groups)

    def retranslateUi(self, Groups):
        _translate = QtCore.QCoreApplication.translate
        # Groups.setWindowTitle(_translate("Groups", "المجموعات"))
        self.groups_tree.headerItem().setText(0, _translate("Groups", "الرمز"))
        self.groups_tree.headerItem().setText(1, _translate("Groups", "الحساب"))
        self.groups_tree.headerItem().setText(2, _translate("Groups", "المعرف"))
        self.add_btn.setText(_translate("Groups", "إضافة مجموعة"))
        self.delete_btn.setText(_translate("Groups", "...حذف"))
        self.edit_btn.setText(_translate("Groups", "...تعديل معلومات المجموعة"))
