# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_GroupEdit.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GroupEdit(object):
    def setupUi(self, GroupEdit):
        GroupEdit.setObjectName("GroupEdit")
        GroupEdit.resize(369, 271)
        GroupEdit.setMinimumSize(QtCore.QSize(300, 200))
        GroupEdit.setMaximumSize(QtCore.QSize(600, 400))
        GroupEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.gridLayout = QtWidgets.QGridLayout(GroupEdit)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(GroupEdit)
        self.groupBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 3, 0, 1, 1)
        self.save_btn = QtWidgets.QPushButton(self.groupBox)
        self.save_btn.setObjectName("save_btn")
        self.gridLayout_2.addWidget(self.save_btn, 4, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.date_input = QtWidgets.QLineEdit(self.groupBox)
        self.date_input.setEnabled(False)
        self.date_input.setObjectName("date_input")
        self.gridLayout_2.addWidget(self.date_input, 3, 1, 1, 2)
        self.name_input = QtWidgets.QLineEdit(self.groupBox)
        self.name_input.setObjectName("name_input")
        self.gridLayout_2.addWidget(self.name_input, 0, 1, 1, 2)
        self.parent_combobox = QtWidgets.QComboBox(self.groupBox)
        self.parent_combobox.setObjectName("parent_combobox")
        self.gridLayout_2.addWidget(self.parent_combobox, 2, 1, 1, 1)
        self.select_parent_btn = QtWidgets.QToolButton(self.groupBox)
        self.select_parent_btn.setObjectName("select_parent_btn")
        self.gridLayout_2.addWidget(self.select_parent_btn, 2, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(GroupEdit)
        QtCore.QMetaObject.connectSlotsByName(GroupEdit)

    def retranslateUi(self, GroupEdit):
        _translate = QtCore.QCoreApplication.translate
        GroupEdit.setWindowTitle(_translate("GroupEdit", "تعديل معلومات المجموعة"))
        self.label_3.setText(_translate("GroupEdit", "تاريخ الإنشاء"))
        self.save_btn.setText(_translate("GroupEdit", "حفظ"))
        self.label.setText(_translate("GroupEdit", "اسم المجموعة"))
        self.label_2.setText(_translate("GroupEdit", "المجموعة الأب"))
        self.select_parent_btn.setText(_translate("GroupEdit", "..."))
