# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_HR_Resign.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HR_Resign(object):
    def setupUi(self, HR_Resign):
        HR_Resign.setObjectName("HR_Resign")
        HR_Resign.resize(317, 192)
        self.gridLayout = QtWidgets.QGridLayout(HR_Resign)
        self.gridLayout.setObjectName("gridLayout")
        self.dateEdit = QtWidgets.QDateEdit(HR_Resign)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(HR_Resign)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.resign_btn = QtWidgets.QPushButton(HR_Resign)
        self.resign_btn.setObjectName("resign_btn")
        self.gridLayout.addWidget(self.resign_btn, 1, 0, 1, 1)
        self.cancel_btn = QtWidgets.QPushButton(HR_Resign)
        self.cancel_btn.setObjectName("cancel_btn")
        self.gridLayout.addWidget(self.cancel_btn, 1, 1, 1, 1)

        self.retranslateUi(HR_Resign)
        QtCore.QMetaObject.connectSlotsByName(HR_Resign)

    def retranslateUi(self, HR_Resign):
        _translate = QtCore.QCoreApplication.translate
        HR_Resign.setWindowTitle(_translate("HR_Resign", "إقالة موظف"))
        self.label.setText(_translate("HR_Resign", "تاريخ الاستقالة:"))
        self.resign_btn.setText(_translate("HR_Resign", "إقالة"))
        self.cancel_btn.setText(_translate("HR_Resign", "إلغاء"))
