# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_HR_Employ.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HR_Employ(object):
    def setupUi(self, HR_Employ):
        HR_Employ.setObjectName("HR_Employ")
        HR_Employ.setWindowModality(QtCore.Qt.ApplicationModal)
        HR_Employ.resize(400, 250)
        HR_Employ.setMinimumSize(QtCore.QSize(400, 250))
        HR_Employ.setMaximumSize(QtCore.QSize(400, 250))
        self.gridLayout_2 = QtWidgets.QGridLayout(HR_Employ)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(HR_Employ)
        self.groupBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.name_label_4 = QtWidgets.QLabel(self.groupBox)
        self.name_label_4.setObjectName("name_label_4")
        self.gridLayout.addWidget(self.name_label_4, 4, 0, 1, 1)
        self.departments_combobox = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.departments_combobox.sizePolicy().hasHeightForWidth())
        self.departments_combobox.setSizePolicy(sizePolicy)
        self.departments_combobox.setObjectName("departments_combobox")
        self.gridLayout.addWidget(self.departments_combobox, 0, 1, 1, 2)
        self.positions_combobox = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.positions_combobox.sizePolicy().hasHeightForWidth())
        self.positions_combobox.setSizePolicy(sizePolicy)
        self.positions_combobox.setObjectName("positions_combobox")
        self.gridLayout.addWidget(self.positions_combobox, 1, 1, 1, 2)
        self.start_date_input = QtWidgets.QDateEdit(self.groupBox)
        self.start_date_input.setObjectName("start_date_input")
        self.gridLayout.addWidget(self.start_date_input, 2, 1, 1, 2)
        self.salary_opposite_account_combobox = QtWidgets.QComboBox(self.groupBox)
        self.salary_opposite_account_combobox.setStyleSheet("QComboBox {\n"
"        background-color: #fafafa;\n"
"        border: 1px solid lightgrey;        \n"
"        height: 22px;\n"
"        color: black;\n"
"    }\n"
"    QComboBox::drop-down {\n"
"        border: none;\n"
"    }")
        self.salary_opposite_account_combobox.setObjectName("salary_opposite_account_combobox")
        self.gridLayout.addWidget(self.salary_opposite_account_combobox, 5, 1, 1, 1)
        self.name_label_3 = QtWidgets.QLabel(self.groupBox)
        self.name_label_3.setObjectName("name_label_3")
        self.gridLayout.addWidget(self.name_label_3, 2, 0, 1, 1)
        self.employ_btn = QtWidgets.QPushButton(self.groupBox)
        self.employ_btn.setObjectName("employ_btn")
        self.gridLayout.addWidget(self.employ_btn, 6, 1, 1, 2)
        self.name_label = QtWidgets.QLabel(self.groupBox)
        self.name_label.setObjectName("name_label")
        self.gridLayout.addWidget(self.name_label, 0, 0, 1, 1)
        self.salary_account_combobox = QtWidgets.QComboBox(self.groupBox)
        self.salary_account_combobox.setStyleSheet("QComboBox {\n"
"        background-color: #fafafa;\n"
"        border: 1px solid lightgrey;        \n"
"        height: 22px;\n"
"        color: black;\n"
"    }\n"
"    QComboBox::drop-down {\n"
"        border: none;\n"
"    }")
        self.salary_account_combobox.setObjectName("salary_account_combobox")
        self.gridLayout.addWidget(self.salary_account_combobox, 4, 1, 1, 1)
        self.name_label_2 = QtWidgets.QLabel(self.groupBox)
        self.name_label_2.setObjectName("name_label_2")
        self.gridLayout.addWidget(self.name_label_2, 1, 0, 1, 1)
        self.name_label_5 = QtWidgets.QLabel(self.groupBox)
        self.name_label_5.setObjectName("name_label_5")
        self.gridLayout.addWidget(self.name_label_5, 5, 0, 1, 1)
        self.select_salary_account_btn = QtWidgets.QToolButton(self.groupBox)
        self.select_salary_account_btn.setObjectName("select_salary_account_btn")
        self.gridLayout.addWidget(self.select_salary_account_btn, 4, 2, 1, 1)
        self.select_salary_opposite_account_btn = QtWidgets.QToolButton(self.groupBox)
        self.select_salary_opposite_account_btn.setObjectName("select_salary_opposite_account_btn")
        self.gridLayout.addWidget(self.select_salary_opposite_account_btn, 5, 2, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(HR_Employ)
        QtCore.QMetaObject.connectSlotsByName(HR_Employ)

    def retranslateUi(self, HR_Employ):
        _translate = QtCore.QCoreApplication.translate
        HR_Employ.setWindowTitle(_translate("HR_Employ", "توظيف"))
        self.name_label_4.setText(_translate("HR_Employ", "حساب الراتب:"))
        self.name_label_3.setText(_translate("HR_Employ", "تاريخ المباشرة:"))
        self.employ_btn.setText(_translate("HR_Employ", " توظيف"))
        self.name_label.setText(_translate("HR_Employ", "القسم:"))
        self.name_label_2.setText(_translate("HR_Employ", "المسمى الوظيفي:"))
        self.name_label_5.setText(_translate("HR_Employ", "حساب الراتب المقابل:"))
        self.select_salary_account_btn.setText(_translate("HR_Employ", "🔎"))
        self.select_salary_opposite_account_btn.setText(_translate("HR_Employ", "🔎"))
