# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_InventoryReport.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InventoryReport(object):
    def setupUi(self, InventoryReport):
        InventoryReport.setObjectName("InventoryReport")
        InventoryReport.setWindowModality(QtCore.Qt.WindowModal)
        InventoryReport.resize(1085, 435)
        InventoryReport.setMinimumSize(QtCore.QSize(0, 400))
        InventoryReport.setLayoutDirection(QtCore.Qt.RightToLeft)
        InventoryReport.setModal(True)
        self.gridLayout_2 = QtWidgets.QGridLayout(InventoryReport)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_3 = QtWidgets.QGroupBox(InventoryReport)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.calculate_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.calculate_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.calculate_btn.setObjectName("calculate_btn")
        self.gridLayout.addWidget(self.calculate_btn, 0, 5, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 6, 1, 1)
        self.to_date_input = QtWidgets.QDateEdit(self.groupBox_3)
        self.to_date_input.setObjectName("to_date_input")
        self.gridLayout.addWidget(self.to_date_input, 0, 4, 1, 1)
        self.select_warehouse_btn = QtWidgets.QToolButton(self.groupBox_3)
        self.select_warehouse_btn.setObjectName("select_warehouse_btn")
        self.gridLayout.addWidget(self.select_warehouse_btn, 0, 2, 1, 1)
        self.results_table = QtWidgets.QTableWidget(self.groupBox_3)
        self.results_table.setObjectName("results_table")
        self.results_table.setColumnCount(4)
        self.results_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.results_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.results_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.results_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.results_table.setHorizontalHeaderItem(3, item)
        self.results_table.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.results_table, 1, 0, 1, 7)
        self.warehouse_combobox = QtWidgets.QComboBox(self.groupBox_3)
        self.warehouse_combobox.setMinimumSize(QtCore.QSize(150, 0))
        self.warehouse_combobox.setStyleSheet("QComboBox {\n"
"        background-color: #fafafa;\n"
"        border: 1px solid lightgrey;        \n"
"        height: 22px;\n"
"        color: black;\n"
"    }\n"
"    QComboBox::drop-down {\n"
"        border: none;\n"
"    }")
        self.warehouse_combobox.setObjectName("warehouse_combobox")
        self.gridLayout.addWidget(self.warehouse_combobox, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_3, 0, 0, 1, 1)

        self.retranslateUi(InventoryReport)
        QtCore.QMetaObject.connectSlotsByName(InventoryReport)

    def retranslateUi(self, InventoryReport):
        _translate = QtCore.QCoreApplication.translate
        InventoryReport.setWindowTitle(_translate("InventoryReport", "تقرير جرد"))
        self.label_3.setText(_translate("InventoryReport", "المستودع:"))
        self.calculate_btn.setText(_translate("InventoryReport", "حساب"))
        self.label_5.setText(_translate("InventoryReport", "التاريخ:"))
        self.select_warehouse_btn.setText(_translate("InventoryReport", "🔎"))
        item = self.results_table.horizontalHeaderItem(0)
        item.setText(_translate("InventoryReport", "معرف المادة"))
        item = self.results_table.horizontalHeaderItem(1)
        item.setText(_translate("InventoryReport", "المادة"))
        item = self.results_table.horizontalHeaderItem(2)
        item.setText(_translate("InventoryReport", "الكمية"))
        item = self.results_table.horizontalHeaderItem(3)
        item.setText(_translate("InventoryReport", "الواحدة"))
