# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_InvoicesSettings.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InvoicesSettings(object):
    def setupUi(self, InvoicesSettings):
        InvoicesSettings.setObjectName("InvoicesSettings")
        InvoicesSettings.resize(893, 547)
        InvoicesSettings.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.gridLayout_3 = QtWidgets.QGridLayout(InvoicesSettings)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(InvoicesSettings)
        self.tabWidget.setObjectName("tabWidget")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.save_btn = QtWidgets.QPushButton(InvoicesSettings)
        self.save_btn.setObjectName("save_btn")
        self.gridLayout_3.addWidget(self.save_btn, 1, 0, 1, 1)

        self.retranslateUi(InvoicesSettings)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(InvoicesSettings)

    def retranslateUi(self, InvoicesSettings):
        _translate = QtCore.QCoreApplication.translate
        InvoicesSettings.setWindowTitle(_translate("InvoicesSettings", "إعدادات الفواتير"))
        self.save_btn.setText(_translate("InvoicesSettings", "حفظ"))
