# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_JournalEntryItemView.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JournalEntryItemView(object):
    def setupUi(self, JournalEntryItemView):
        JournalEntryItemView.setObjectName("JournalEntryItemView")
        JournalEntryItemView.resize(775, 562)
        JournalEntryItemView.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.gridLayout = QtWidgets.QGridLayout(JournalEntryItemView)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_4 = QtWidgets.QGroupBox(JournalEntryItemView)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 200))
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.journal_entry_item_account_combobox = QtWidgets.QComboBox(self.groupBox_4)
        self.journal_entry_item_account_combobox.setMinimumSize(QtCore.QSize(100, 0))
        self.journal_entry_item_account_combobox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.journal_entry_item_account_combobox.setObjectName("journal_entry_item_account_combobox")
        self.gridLayout_2.addWidget(self.journal_entry_item_account_combobox, 0, 1, 1, 1)
        self.select_account_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.select_account_btn.setObjectName("select_account_btn")
        self.gridLayout_2.addWidget(self.select_account_btn, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 6, 1, 1)
        self.journal_entry_item_opposite_account_combobox = QtWidgets.QComboBox(self.groupBox_4)
        self.journal_entry_item_opposite_account_combobox.setMinimumSize(QtCore.QSize(100, 0))
        self.journal_entry_item_opposite_account_combobox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.journal_entry_item_opposite_account_combobox.setObjectName("journal_entry_item_opposite_account_combobox")
        self.gridLayout_2.addWidget(self.journal_entry_item_opposite_account_combobox, 0, 7, 1, 1)
        self.select_opposite_account_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.select_opposite_account_btn.setObjectName("select_opposite_account_btn")
        self.gridLayout_2.addWidget(self.select_opposite_account_btn, 0, 8, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.journal_entry_item_statement_input = QtWidgets.QTextEdit(self.groupBox_4)
        self.journal_entry_item_statement_input.setMaximumSize(QtCore.QSize(16777215, 70))
        self.journal_entry_item_statement_input.setObjectName("journal_entry_item_statement_input")
        self.gridLayout_2.addWidget(self.journal_entry_item_statement_input, 1, 1, 1, 8)
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 1)
        self.journal_entry_item_type_combobox = QtWidgets.QComboBox(self.groupBox_4)
        self.journal_entry_item_type_combobox.setObjectName("journal_entry_item_type_combobox")
        self.gridLayout_2.addWidget(self.journal_entry_item_type_combobox, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 2, 3, 1, 2)
        self.value_input = QtWidgets.QLineEdit(self.groupBox_4)
        self.value_input.setObjectName("value_input")
        self.gridLayout_2.addWidget(self.value_input, 2, 5, 1, 1)
        self.entry_currency_checkbox = QtWidgets.QCheckBox(self.groupBox_4)
        self.entry_currency_checkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.entry_currency_checkbox.setChecked(True)
        self.entry_currency_checkbox.setObjectName("entry_currency_checkbox")
        self.gridLayout_2.addWidget(self.entry_currency_checkbox, 2, 7, 1, 2)
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 3, 0, 1, 1)
        self.journal_entry_cost_center_combobox = QtWidgets.QComboBox(self.groupBox_4)
        self.journal_entry_cost_center_combobox.setObjectName("journal_entry_cost_center_combobox")
        self.gridLayout_2.addWidget(self.journal_entry_cost_center_combobox, 3, 1, 1, 1)
        self.select_cost_center_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.select_cost_center_btn.setObjectName("select_cost_center_btn")
        self.gridLayout_2.addWidget(self.select_cost_center_btn, 3, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(120, 17, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 3, 4, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 3, 7, 1, 1)
        self.journal_entry_item_currency_combobox = QtWidgets.QComboBox(self.groupBox_4)
        self.journal_entry_item_currency_combobox.setEnabled(False)
        self.journal_entry_item_currency_combobox.setObjectName("journal_entry_item_currency_combobox")
        self.gridLayout_2.addWidget(self.journal_entry_item_currency_combobox, 3, 8, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 4, 0, 1, 1)
        self.journal_entry_distributive_cost_center_accounts_table = QtWidgets.QTableWidget(self.groupBox_4)
        self.journal_entry_distributive_cost_center_accounts_table.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.journal_entry_distributive_cost_center_accounts_table.setProperty("showDropIndicator", False)
        self.journal_entry_distributive_cost_center_accounts_table.setDragDropOverwriteMode(False)
        self.journal_entry_distributive_cost_center_accounts_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.journal_entry_distributive_cost_center_accounts_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.journal_entry_distributive_cost_center_accounts_table.setShowGrid(True)
        self.journal_entry_distributive_cost_center_accounts_table.setObjectName("journal_entry_distributive_cost_center_accounts_table")
        self.journal_entry_distributive_cost_center_accounts_table.setColumnCount(5)
        self.journal_entry_distributive_cost_center_accounts_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.journal_entry_distributive_cost_center_accounts_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.journal_entry_distributive_cost_center_accounts_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.journal_entry_distributive_cost_center_accounts_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.journal_entry_distributive_cost_center_accounts_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.journal_entry_distributive_cost_center_accounts_table.setHorizontalHeaderItem(4, item)
        self.journal_entry_distributive_cost_center_accounts_table.horizontalHeader().setVisible(True)
        self.journal_entry_distributive_cost_center_accounts_table.horizontalHeader().setCascadingSectionResizes(False)
        self.journal_entry_distributive_cost_center_accounts_table.horizontalHeader().setSortIndicatorShown(False)
        self.journal_entry_distributive_cost_center_accounts_table.horizontalHeader().setStretchLastSection(True)
        self.journal_entry_distributive_cost_center_accounts_table.verticalHeader().setVisible(False)
        self.journal_entry_distributive_cost_center_accounts_table.verticalHeader().setSortIndicatorShown(False)
        self.journal_entry_distributive_cost_center_accounts_table.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.journal_entry_distributive_cost_center_accounts_table, 4, 1, 2, 8)
        spacerItem1 = QtWidgets.QSpacerItem(17, 181, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 5, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 6, 1, 1, 1)
        self.journal_entry_distributive_cost_center_accounts_total_percentage_input = QtWidgets.QLineEdit(self.groupBox_4)
        self.journal_entry_distributive_cost_center_accounts_total_percentage_input.setEnabled(False)
        self.journal_entry_distributive_cost_center_accounts_total_percentage_input.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border: black solid 1px;")
        self.journal_entry_distributive_cost_center_accounts_total_percentage_input.setObjectName("journal_entry_distributive_cost_center_accounts_total_percentage_input")
        self.gridLayout_2.addWidget(self.journal_entry_distributive_cost_center_accounts_total_percentage_input, 6, 2, 1, 2)
        self.gridLayout.addWidget(self.groupBox_4, 0, 0, 1, 3)
        self.save_btn = QtWidgets.QPushButton(JournalEntryItemView)
        self.save_btn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.save_btn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.save_btn.setStyleSheet("QPushButton {\n"
"    background-color: #C8E6C9;\n"
"    color: black;\n"
"    border: 1px solid #81C784;\n"
"    border-radius: 0px;\n"
"    padding: 8px 16px;\n"
"    font-family: Arial;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A5D6A7;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #81C784;\n"
"}\n"
"")
        self.save_btn.setObjectName("save_btn")
        self.gridLayout.addWidget(self.save_btn, 2, 2, 1, 1)
        self.cancel_btn = QtWidgets.QPushButton(JournalEntryItemView)
        self.cancel_btn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.cancel_btn.setStyleSheet("QPushButton {\n"
"    background-color: #FFCDD2;\n"
"    color: black;\n"
"    border: 1px solid #E57373;\n"
"    border-radius: 0px;\n"
"    padding: 8px 16px;\n"
"    font-family: Arial;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #EF9A9A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #E57373;\n"
"}\n"
"")
        self.cancel_btn.setObjectName("cancel_btn")
        self.gridLayout.addWidget(self.cancel_btn, 2, 1, 1, 1)

        self.retranslateUi(JournalEntryItemView)
        QtCore.QMetaObject.connectSlotsByName(JournalEntryItemView)

    def retranslateUi(self, JournalEntryItemView):
        _translate = QtCore.QCoreApplication.translate
        JournalEntryItemView.setWindowTitle(_translate("JournalEntryItemView", "Dialog"))
        self.groupBox_4.setTitle(_translate("JournalEntryItemView", "مدخلة سند قيد"))
        self.label_5.setText(_translate("JournalEntryItemView", "الحساب:"))
        self.select_account_btn.setText(_translate("JournalEntryItemView", "...اختيار"))
        self.label_6.setText(_translate("JournalEntryItemView", "الحساب المقابل:"))
        self.select_opposite_account_btn.setText(_translate("JournalEntryItemView", "...اختيار"))
        self.label_7.setText(_translate("JournalEntryItemView", "البيان:"))
        self.label_9.setText(_translate("JournalEntryItemView", "الطبيعة:"))
        self.label_10.setText(_translate("JournalEntryItemView", "القيمة:"))
        self.entry_currency_checkbox.setText(_translate("JournalEntryItemView", "استخدام عملة القيد"))
        self.label_11.setText(_translate("JournalEntryItemView", "مركز الكلفة:"))
        self.select_cost_center_btn.setText(_translate("JournalEntryItemView", "...اختيار"))
        self.label_3.setText(_translate("JournalEntryItemView", "العملة:"))
        self.label_12.setText(_translate("JournalEntryItemView", "النسب:"))
        item = self.journal_entry_distributive_cost_center_accounts_table.horizontalHeaderItem(0)
        item.setText(_translate("JournalEntryItemView", "المعرف"))
        item = self.journal_entry_distributive_cost_center_accounts_table.horizontalHeaderItem(1)
        item.setText(_translate("JournalEntryItemView", "معرف الحساب"))
        item = self.journal_entry_distributive_cost_center_accounts_table.horizontalHeaderItem(2)
        item.setText(_translate("JournalEntryItemView", "اسم الحساب"))
        item = self.journal_entry_distributive_cost_center_accounts_table.horizontalHeaderItem(3)
        item.setText(_translate("JournalEntryItemView", "النسبة"))
        item = self.journal_entry_distributive_cost_center_accounts_table.horizontalHeaderItem(4)
        item.setText(_translate("JournalEntryItemView", "القيمة"))
        self.label_13.setText(_translate("JournalEntryItemView", "مجموع النسب:"))
        self.save_btn.setText(_translate("JournalEntryItemView", "حفظ"))
        self.cancel_btn.setText(_translate("JournalEntryItemView", "إلغاء"))
