# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_JournalVoucher.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JournalVoucher(object):
    def setupUi(self, JournalVoucher):
        JournalVoucher.setObjectName("JournalVoucher")
        JournalVoucher.resize(775, 546)
        JournalVoucher.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.gridLayout = QtWidgets.QGridLayout(JournalVoucher)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_4 = QtWidgets.QGroupBox(JournalVoucher)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 200))
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.journal_entry_items_table = QtWidgets.QTableWidget(self.groupBox_4)
        self.journal_entry_items_table.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.journal_entry_items_table.setProperty("showDropIndicator", False)
        self.journal_entry_items_table.setDragDropOverwriteMode(False)
        self.journal_entry_items_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.journal_entry_items_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.journal_entry_items_table.setShowGrid(True)
        self.journal_entry_items_table.setObjectName("journal_entry_items_table")
        self.journal_entry_items_table.setColumnCount(5)
        self.journal_entry_items_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.journal_entry_items_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.journal_entry_items_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.journal_entry_items_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.journal_entry_items_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.journal_entry_items_table.setHorizontalHeaderItem(4, item)
        self.journal_entry_items_table.horizontalHeader().setVisible(True)
        self.journal_entry_items_table.horizontalHeader().setCascadingSectionResizes(False)
        self.journal_entry_items_table.horizontalHeader().setSortIndicatorShown(False)
        self.journal_entry_items_table.horizontalHeader().setStretchLastSection(True)
        self.journal_entry_items_table.verticalHeader().setVisible(False)
        self.journal_entry_items_table.verticalHeader().setSortIndicatorShown(False)
        self.journal_entry_items_table.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.journal_entry_items_table, 3, 0, 1, 9)
        self.opposite_account_combobox = QtWidgets.QComboBox(self.groupBox_4)
        self.opposite_account_combobox.setMinimumSize(QtCore.QSize(100, 0))
        self.opposite_account_combobox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.opposite_account_combobox.setStyleSheet("QComboBox {\n"
"        background-color: #fafafa;\n"
"        border: 1px solid lightgrey;        \n"
"        height: 22px;\n"
"        color: black;\n"
"    }\n"
"    QComboBox::drop-down {\n"
"        border: none;\n"
"    }")
        self.opposite_account_combobox.setObjectName("opposite_account_combobox")
        self.gridLayout_2.addWidget(self.opposite_account_combobox, 0, 4, 1, 1)
        self.account_combobox = QtWidgets.QComboBox(self.groupBox_4)
        self.account_combobox.setMinimumSize(QtCore.QSize(100, 0))
        self.account_combobox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.account_combobox.setStyleSheet("QComboBox {\n"
"        background-color: #fafafa;\n"
"        border: 1px solid lightgrey;        \n"
"        height: 22px;\n"
"        color: black;\n"
"    }\n"
"    QComboBox::drop-down {\n"
"        border: none;\n"
"    }")
        self.account_combobox.setObjectName("account_combobox")
        self.gridLayout_2.addWidget(self.account_combobox, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 4, 2, 1, 1)
        self.value_input = QtWidgets.QLineEdit(self.groupBox_4)
        self.value_input.setObjectName("value_input")
        self.gridLayout_2.addWidget(self.value_input, 0, 8, 1, 1)
        self.journal_entry_distributive_cost_center_accounts_total_percentage_input_3 = QtWidgets.QLineEdit(self.groupBox_4)
        self.journal_entry_distributive_cost_center_accounts_total_percentage_input_3.setEnabled(False)
        self.journal_entry_distributive_cost_center_accounts_total_percentage_input_3.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border: black solid 1px;")
        self.journal_entry_distributive_cost_center_accounts_total_percentage_input_3.setObjectName("journal_entry_distributive_cost_center_accounts_total_percentage_input_3")
        self.gridLayout_2.addWidget(self.journal_entry_distributive_cost_center_accounts_total_percentage_input_3, 4, 1, 1, 1)
        self.select_opposite_account_btn = QtWidgets.QToolButton(self.groupBox_4)
        self.select_opposite_account_btn.setObjectName("select_opposite_account_btn")
        self.gridLayout_2.addWidget(self.select_opposite_account_btn, 0, 5, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 2, 0, 1, 1)
        self.journal_entry_distributive_cost_center_accounts_total_percentage_input = QtWidgets.QLineEdit(self.groupBox_4)
        self.journal_entry_distributive_cost_center_accounts_total_percentage_input.setEnabled(False)
        self.journal_entry_distributive_cost_center_accounts_total_percentage_input.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border: black solid 1px;")
        self.journal_entry_distributive_cost_center_accounts_total_percentage_input.setObjectName("journal_entry_distributive_cost_center_accounts_total_percentage_input")
        self.gridLayout_2.addWidget(self.journal_entry_distributive_cost_center_accounts_total_percentage_input, 4, 8, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 6, 1, 1)
        self.journal_entry_cost_center_combobox = QtWidgets.QComboBox(self.groupBox_4)
        self.journal_entry_cost_center_combobox.setObjectName("journal_entry_cost_center_combobox")
        self.gridLayout_2.addWidget(self.journal_entry_cost_center_combobox, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 4, 7, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 4, 0, 1, 1)
        self.select_account_btn = QtWidgets.QToolButton(self.groupBox_4)
        self.select_account_btn.setObjectName("select_account_btn")
        self.gridLayout_2.addWidget(self.select_account_btn, 0, 2, 1, 1)
        self.journal_entry_distributive_cost_center_accounts_total_percentage_input_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.journal_entry_distributive_cost_center_accounts_total_percentage_input_2.setEnabled(False)
        self.journal_entry_distributive_cost_center_accounts_total_percentage_input_2.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border: black solid 1px;")
        self.journal_entry_distributive_cost_center_accounts_total_percentage_input_2.setObjectName("journal_entry_distributive_cost_center_accounts_total_percentage_input_2")
        self.gridLayout_2.addWidget(self.journal_entry_distributive_cost_center_accounts_total_percentage_input_2, 4, 3, 1, 1)
        self.select_cost_center_btn_2 = QtWidgets.QToolButton(self.groupBox_4)
        self.select_cost_center_btn_2.setObjectName("select_cost_center_btn_2")
        self.gridLayout_2.addWidget(self.select_cost_center_btn_2, 2, 2, 1, 1)
        self.journal_entry_item_statement_input = QtWidgets.QTextEdit(self.groupBox_4)
        self.journal_entry_item_statement_input.setMaximumSize(QtCore.QSize(16777215, 70))
        self.journal_entry_item_statement_input.setObjectName("journal_entry_item_statement_input")
        self.gridLayout_2.addWidget(self.journal_entry_item_statement_input, 1, 1, 1, 8)
        self.currency_combobox = QtWidgets.QComboBox(self.groupBox_4)
        self.currency_combobox.setEnabled(True)
        self.currency_combobox.setObjectName("currency_combobox")
        self.gridLayout_2.addWidget(self.currency_combobox, 2, 4, 1, 1)
        self.add_journal_entry_item = QtWidgets.QPushButton(self.groupBox_4)
        self.add_journal_entry_item.setObjectName("add_journal_entry_item")
        self.gridLayout_2.addWidget(self.add_journal_entry_item, 2, 8, 1, 1)
        self.gridLayout.addWidget(self.groupBox_4, 1, 1, 1, 1)

        self.retranslateUi(JournalVoucher)
        QtCore.QMetaObject.connectSlotsByName(JournalVoucher)

    def retranslateUi(self, JournalVoucher):
        _translate = QtCore.QCoreApplication.translate
        JournalVoucher.setWindowTitle(_translate("JournalVoucher", "سند جديد"))
        self.label_7.setText(_translate("JournalVoucher", "البيان:"))
        item = self.journal_entry_items_table.horizontalHeaderItem(0)
        item.setText(_translate("JournalVoucher", "المعرف"))
        item = self.journal_entry_items_table.horizontalHeaderItem(1)
        item.setText(_translate("JournalVoucher", "معرف الحساب"))
        item = self.journal_entry_items_table.horizontalHeaderItem(2)
        item.setText(_translate("JournalVoucher", "اسم الحساب"))
        item = self.journal_entry_items_table.horizontalHeaderItem(3)
        item.setText(_translate("JournalVoucher", "القيمة"))
        item = self.journal_entry_items_table.horizontalHeaderItem(4)
        item.setText(_translate("JournalVoucher", "العملة"))
        self.label_15.setText(_translate("JournalVoucher", "دائن:"))
        self.select_opposite_account_btn.setText(_translate("JournalVoucher", "🔎"))
        self.label_11.setText(_translate("JournalVoucher", "مركز الكلفة:"))
        self.label_10.setText(_translate("JournalVoucher", "القيمة:"))
        self.label_6.setText(_translate("JournalVoucher", "الحساب المقابل:"))
        self.label_13.setText(_translate("JournalVoucher", "الرصيد النهائي:"))
        self.label_5.setText(_translate("JournalVoucher", "الحساب:"))
        self.label_3.setText(_translate("JournalVoucher", "العملة:"))
        self.label_14.setText(_translate("JournalVoucher", "مدين:"))
        self.select_account_btn.setText(_translate("JournalVoucher", "🔎"))
        self.select_cost_center_btn_2.setText(_translate("JournalVoucher", "🔎"))
        self.add_journal_entry_item.setText(_translate("JournalVoucher", "حفظ"))
