# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Journal.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Journal(object):
    def setupUi(self, Journal):
        Journal.setObjectName("Journal")
        Journal.setWindowModality(QtCore.Qt.WindowModal)
        Journal.resize(1333, 833)
        Journal.setLayoutDirection(QtCore.Qt.RightToLeft)
        Journal.setModal(True)
        self.gridLayout_4 = QtWidgets.QGridLayout(Journal)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.JournalEntry = QtWidgets.QGroupBox(Journal)
        self.JournalEntry.setMaximumSize(QtCore.QSize(300, 16777215))
        self.JournalEntry.setTitle("")
        self.JournalEntry.setObjectName("JournalEntry")
        self.gridLayout = QtWidgets.QGridLayout(self.JournalEntry)
        self.gridLayout.setSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.filter_creditor_checkbox = QtWidgets.QCheckBox(self.JournalEntry)
        self.filter_creditor_checkbox.setChecked(False)
        self.filter_creditor_checkbox.setObjectName("filter_creditor_checkbox")
        self.gridLayout.addWidget(self.filter_creditor_checkbox, 3, 1, 1, 1)
        self.filter_by_account_checkbox = QtWidgets.QCheckBox(self.JournalEntry)
        self.filter_by_account_checkbox.setChecked(False)
        self.filter_by_account_checkbox.setObjectName("filter_by_account_checkbox")
        self.gridLayout.addWidget(self.filter_by_account_checkbox, 2, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(106, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 2, 2, 1)
        self.accounts_tree = QtWidgets.QTreeWidget(self.JournalEntry)
        self.accounts_tree.setEnabled(False)
        self.accounts_tree.setObjectName("accounts_tree")
        self.gridLayout.addWidget(self.accounts_tree, 4, 0, 1, 4)
        self.filter_debtor_checkbox = QtWidgets.QCheckBox(self.JournalEntry)
        self.filter_debtor_checkbox.setChecked(False)
        self.filter_debtor_checkbox.setObjectName("filter_debtor_checkbox")
        self.gridLayout.addWidget(self.filter_debtor_checkbox, 3, 0, 1, 1)
        self.filter_by_date_checkbox = QtWidgets.QCheckBox(self.JournalEntry)
        self.filter_by_date_checkbox.setEnabled(True)
        self.filter_by_date_checkbox.setChecked(False)
        self.filter_by_date_checkbox.setObjectName("filter_by_date_checkbox")
        self.gridLayout.addWidget(self.filter_by_date_checkbox, 0, 0, 1, 2)
        self.calendar = QtWidgets.QCalendarWidget(self.JournalEntry)
        self.calendar.setMinimumSize(QtCore.QSize(0, 200))
        self.calendar.setMaximumSize(QtCore.QSize(16777215, 200))
        self.calendar.setObjectName("calendar")
        self.gridLayout.addWidget(self.calendar, 1, 0, 1, 4)
        self.manage_accounts_btn = QtWidgets.QPushButton(self.JournalEntry)
        self.manage_accounts_btn.setObjectName("manage_accounts_btn")
        self.gridLayout.addWidget(self.manage_accounts_btn, 5, 2, 1, 1)
        self.gridLayout_4.addWidget(self.JournalEntry, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Journal)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.delete_journal_entry_btn = QtWidgets.QPushButton(self.groupBox)
        self.delete_journal_entry_btn.setStyleSheet("QPushButton {\n"
"    background-color: #FFCDD2;\n"
"    color: black;\n"
"    border: 1px solid #E57373;\n"
"    border-radius: 0px;\n"
"    padding: 8px 16px;\n"
"    font-family: Arial;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #EF9A9A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #E57373;\n"
"}\n"
"")
        self.delete_journal_entry_btn.setObjectName("delete_journal_entry_btn")
        self.gridLayout_3.addWidget(self.delete_journal_entry_btn, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(300, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 1, 1, 1)
        self.journals_entries_table = QtWidgets.QTableWidget(self.groupBox)
        self.journals_entries_table.setMinimumSize(QtCore.QSize(400, 0))
        self.journals_entries_table.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.journals_entries_table.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.journals_entries_table.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.journals_entries_table.setLineWidth(1)
        self.journals_entries_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.journals_entries_table.setProperty("showDropIndicator", False)
        self.journals_entries_table.setDragDropOverwriteMode(False)
        self.journals_entries_table.setAlternatingRowColors(True)
        self.journals_entries_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.journals_entries_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.journals_entries_table.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.journals_entries_table.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.journals_entries_table.setWordWrap(True)
        self.journals_entries_table.setObjectName("journals_entries_table")
        self.journals_entries_table.setColumnCount(6)
        self.journals_entries_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.journals_entries_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.journals_entries_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.journals_entries_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.journals_entries_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.journals_entries_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.journals_entries_table.setHorizontalHeaderItem(5, item)
        self.journals_entries_table.horizontalHeader().setVisible(True)
        self.journals_entries_table.horizontalHeader().setStretchLastSection(True)
        self.journals_entries_table.verticalHeader().setVisible(False)
        self.gridLayout_3.addWidget(self.journals_entries_table, 0, 1, 1, 2)
        self.gridLayout_4.addWidget(self.groupBox, 0, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Journal)
        self.groupBox_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.add_journal_entry_item_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.add_journal_entry_item_btn.setStyleSheet("QPushButton {\n"
"    background-color: #FFF9C4;\n"
"    color: #000000;\n"
"    border: 1px solid #E0E0E0;\n"
"    border-radius: 0px;\n"
"    padding: 8px 16px;\n"
"    font-family: Arial;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FFECB3;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #FFE082;\n"
"}\n"
"")
        self.add_journal_entry_item_btn.setObjectName("add_journal_entry_item_btn")
        self.gridLayout_2.addWidget(self.add_journal_entry_item_btn, 1, 1, 1, 1)
        self.journal_entries_items_table = QtWidgets.QTableWidget(self.groupBox_2)
        self.journal_entries_items_table.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.journal_entries_items_table.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.journal_entries_items_table.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.journal_entries_items_table.setLineWidth(1)
        self.journal_entries_items_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.journal_entries_items_table.setProperty("showDropIndicator", False)
        self.journal_entries_items_table.setDragDropOverwriteMode(False)
        self.journal_entries_items_table.setAlternatingRowColors(True)
        self.journal_entries_items_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.journal_entries_items_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.journal_entries_items_table.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.journal_entries_items_table.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.journal_entries_items_table.setWordWrap(True)
        self.journal_entries_items_table.setObjectName("journal_entries_items_table")
        self.journal_entries_items_table.setColumnCount(12)
        self.journal_entries_items_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.journal_entries_items_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.journal_entries_items_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.journal_entries_items_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.journal_entries_items_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.journal_entries_items_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.journal_entries_items_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.journal_entries_items_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.journal_entries_items_table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.journal_entries_items_table.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.journal_entries_items_table.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.journal_entries_items_table.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.journal_entries_items_table.setHorizontalHeaderItem(11, item)
        self.journal_entries_items_table.horizontalHeader().setVisible(True)
        self.journal_entries_items_table.horizontalHeader().setStretchLastSection(True)
        self.journal_entries_items_table.verticalHeader().setVisible(False)
        self.gridLayout_2.addWidget(self.journal_entries_items_table, 0, 0, 1, 4)
        self.save_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.save_btn.setMinimumSize(QtCore.QSize(75, 0))
        self.save_btn.setStyleSheet("QPushButton {\n"
"    background-color: #C8E6C9;\n"
"    color: black;\n"
"    border: 1px solid #81C784;\n"
"    border-radius: 0px;\n"
"    padding: 8px 16px;\n"
"    font-family: Arial;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A5D6A7;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #81C784;\n"
"}\n"
"")
        self.save_btn.setObjectName("save_btn")
        self.gridLayout_2.addWidget(self.save_btn, 1, 3, 1, 1)
        self.delete_journal_entry_item_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.delete_journal_entry_item_btn.setMinimumSize(QtCore.QSize(75, 0))
        self.delete_journal_entry_item_btn.setStyleSheet("QPushButton {\n"
"    background-color: #FFCDD2;\n"
"    color: black;\n"
"    border: 1px solid #E57373;\n"
"    border-radius: 0px;\n"
"    padding: 8px 16px;\n"
"    font-family: Arial;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #EF9A9A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #E57373;\n"
"}\n"
"")
        self.delete_journal_entry_item_btn.setObjectName("delete_journal_entry_item_btn")
        self.gridLayout_2.addWidget(self.delete_journal_entry_item_btn, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(175, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 2, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 0, 2, 1, 1)

        self.retranslateUi(Journal)
        QtCore.QMetaObject.connectSlotsByName(Journal)

    def retranslateUi(self, Journal):
        _translate = QtCore.QCoreApplication.translate
        Journal.setWindowTitle(_translate("Journal", "سندات القيد"))
        self.filter_creditor_checkbox.setText(_translate("Journal", "دائن"))
        self.filter_by_account_checkbox.setText(_translate("Journal", "ترشيح حسب الحساب"))
        self.accounts_tree.headerItem().setText(0, _translate("Journal", "الرمز"))
        self.accounts_tree.headerItem().setText(1, _translate("Journal", "الحساب"))
        self.accounts_tree.headerItem().setText(2, _translate("Journal", "المعرف"))
        self.filter_debtor_checkbox.setText(_translate("Journal", "مدين"))
        self.filter_by_date_checkbox.setText(_translate("Journal", "ترشيح حسب التاريخ"))
        self.manage_accounts_btn.setText(_translate("Journal", "إدارة الحسابات"))
        self.delete_journal_entry_btn.setText(_translate("Journal", "حذف"))
        self.journals_entries_table.setSortingEnabled(True)
        item = self.journals_entries_table.horizontalHeaderItem(0)
        item.setText(_translate("Journal", "المعرف"))
        item = self.journals_entries_table.horizontalHeaderItem(1)
        item.setText(_translate("Journal", "التاريخ"))
        item = self.journals_entries_table.horizontalHeaderItem(2)
        item.setText(_translate("Journal", "نوع القيد"))
        item = self.journals_entries_table.horizontalHeaderItem(3)
        item.setText(_translate("Journal", "معرف العملة"))
        item = self.journals_entries_table.horizontalHeaderItem(4)
        item.setText(_translate("Journal", "العملة"))
        item = self.journals_entries_table.horizontalHeaderItem(5)
        item.setText(_translate("Journal", "تاريخ التسجيل"))
        self.add_journal_entry_item_btn.setText(_translate("Journal", "...إضافة عنصر"))
        self.journal_entries_items_table.setSortingEnabled(True)
        item = self.journal_entries_items_table.horizontalHeaderItem(0)
        item.setText(_translate("Journal", "المعرف"))
        item = self.journal_entries_items_table.horizontalHeaderItem(1)
        item.setText(_translate("Journal", "معرف سند القيد"))
        item = self.journal_entries_items_table.horizontalHeaderItem(2)
        item.setText(_translate("Journal", "معرف الحساب"))
        item = self.journal_entries_items_table.horizontalHeaderItem(3)
        item.setText(_translate("Journal", "معرف الحساب المقابل"))
        item = self.journal_entries_items_table.horizontalHeaderItem(4)
        item.setText(_translate("Journal", "معرف مركز الكلفة"))
        item = self.journal_entries_items_table.horizontalHeaderItem(5)
        item.setText(_translate("Journal", "معرف العملة"))
        item = self.journal_entries_items_table.horizontalHeaderItem(6)
        item.setText(_translate("Journal", "النوع"))
        item = self.journal_entries_items_table.horizontalHeaderItem(7)
        item.setText(_translate("Journal", "دائن"))
        item = self.journal_entries_items_table.horizontalHeaderItem(8)
        item.setText(_translate("Journal", "مدين"))
        item = self.journal_entries_items_table.horizontalHeaderItem(9)
        item.setText(_translate("Journal", "القيمة"))
        item = self.journal_entries_items_table.horizontalHeaderItem(10)
        item.setText(_translate("Journal", "العملة"))
        item = self.journal_entries_items_table.horizontalHeaderItem(11)
        item.setText(_translate("Journal", "البيان"))
        self.save_btn.setText(_translate("Journal", "حفظ"))
        self.delete_journal_entry_item_btn.setText(_translate("Journal", "حذف"))
