# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Manufacture_Cost_Fix.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Manufacture_Cost_Fix(object):
    def setupUi(self, Manufacture_Cost_Fix):
        Manufacture_Cost_Fix.setObjectName("Manufacture_Cost_Fix")
        Manufacture_Cost_Fix.setWindowModality(QtCore.Qt.WindowModal)
        Manufacture_Cost_Fix.resize(407, 320)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("graphics/icon.xpm"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Manufacture_Cost_Fix.setWindowIcon(icon)
        Manufacture_Cost_Fix.setLayoutDirection(QtCore.Qt.RightToLeft)
        Manufacture_Cost_Fix.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Manufacture_Cost_Fix)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Manufacture_Cost_Fix)
        self.groupBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.fix_exchange_price_checkbox = QtWidgets.QCheckBox(self.groupBox)
        self.fix_exchange_price_checkbox.setChecked(True)
        self.fix_exchange_price_checkbox.setObjectName("fix_exchange_price_checkbox")
        self.gridLayout.addWidget(self.fix_exchange_price_checkbox, 2, 0, 1, 1)
        self.fix_composition_checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.fix_composition_checkBox.setChecked(True)
        self.fix_composition_checkBox.setObjectName("fix_composition_checkBox")
        self.gridLayout.addWidget(self.fix_composition_checkBox, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.fix_month_expenses = QtWidgets.QCheckBox(self.groupBox)
        self.fix_month_expenses.setChecked(True)
        self.fix_month_expenses.setObjectName("fix_month_expenses")
        self.gridLayout.addWidget(self.fix_month_expenses, 4, 0, 1, 1)
        self.fix_year_expenses = QtWidgets.QCheckBox(self.groupBox)
        self.fix_year_expenses.setChecked(True)
        self.fix_year_expenses.setObjectName("fix_year_expenses")
        self.gridLayout.addWidget(self.fix_year_expenses, 4, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(Manufacture_Cost_Fix)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.fix_cost_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.fix_cost_btn.setObjectName("fix_cost_btn")
        self.gridLayout_3.addWidget(self.fix_cost_btn, 1, 1, 1, 1)
        self.fix_manufacture_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.fix_manufacture_btn.setObjectName("fix_manufacture_btn")
        self.gridLayout_3.addWidget(self.fix_manufacture_btn, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(Manufacture_Cost_Fix)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 2, 1, 1)
        self.progress_label = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.progress_label.setFont(font)
        self.progress_label.setObjectName("progress_label")
        self.gridLayout_4.addWidget(self.progress_label, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_4)

        self.retranslateUi(Manufacture_Cost_Fix)
        QtCore.QMetaObject.connectSlotsByName(Manufacture_Cost_Fix)

    def retranslateUi(self, Manufacture_Cost_Fix):
        _translate = QtCore.QCoreApplication.translate
        Manufacture_Cost_Fix.setWindowTitle(_translate("Manufacture_Cost_Fix", "إصلاح عمليات التكليف والتصنيع"))
        self.fix_exchange_price_checkbox.setText(_translate("Manufacture_Cost_Fix", "صيانة قيمة سعر الصرف"))
        self.fix_composition_checkBox.setText(_translate("Manufacture_Cost_Fix", "صيانة المنتجات التي تم تعديل تركيبتها"))
        self.label_2.setText(_translate("Manufacture_Cost_Fix", "صيانة التكاليف:"))
        self.fix_month_expenses.setText(_translate("Manufacture_Cost_Fix", "التكاليف الشهرية"))
        self.fix_year_expenses.setText(_translate("Manufacture_Cost_Fix", "التكاليف السنوية"))
        self.fix_cost_btn.setText(_translate("Manufacture_Cost_Fix", "إصلاح عمليات التكليف"))
        self.fix_manufacture_btn.setText(_translate("Manufacture_Cost_Fix", "إصلاح عمليات التصنيع"))
        self.progress_label.setText(_translate("Manufacture_Cost_Fix", "0/0"))
