# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_ManufactureProcesses.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ManufactureProcesses(object):
    def setupUi(self, ManufactureProcesses):
        ManufactureProcesses.setObjectName("ManufactureProcesses")
        ManufactureProcesses.setWindowModality(QtCore.Qt.WindowModal)
        ManufactureProcesses.resize(984, 559)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("graphics/icon.xpm"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ManufactureProcesses.setWindowIcon(icon)
        ManufactureProcesses.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(ManufactureProcesses)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(ManufactureProcesses)
        self.groupBox_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(305, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(305, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 1, 1, 1)
        self.manu_processes_table = QtWidgets.QTableWidget(self.groupBox_2)
        self.manu_processes_table.setObjectName("manu_processes_table")
        self.manu_processes_table.setColumnCount(7)
        self.manu_processes_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.manu_processes_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.manu_processes_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.manu_processes_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.manu_processes_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.manu_processes_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.manu_processes_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.manu_processes_table.setHorizontalHeaderItem(6, item)
        self.gridLayout_2.addWidget(self.manu_processes_table, 0, 1, 1, 4)
        self.export_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.export_btn.setObjectName("export_btn")
        self.gridLayout_2.addWidget(self.export_btn, 1, 4, 1, 1)
        self.new_manu_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.new_manu_btn.setObjectName("new_manu_btn")
        self.gridLayout_2.addWidget(self.new_manu_btn, 1, 2, 1, 1)
        self.materials_tree = QtWidgets.QTreeWidget(self.groupBox_2)
        self.materials_tree.setObjectName("materials_tree")
        self.gridLayout_2.addWidget(self.materials_tree, 0, 0, 1, 1)
        self.delete_manu_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.delete_manu_btn.setObjectName("delete_manu_btn")
        self.gridLayout_2.addWidget(self.delete_manu_btn, 1, 3, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 1)

        self.retranslateUi(ManufactureProcesses)
        QtCore.QMetaObject.connectSlotsByName(ManufactureProcesses)

    def retranslateUi(self, ManufactureProcesses):
        _translate = QtCore.QCoreApplication.translate
        ManufactureProcesses.setWindowTitle(_translate("ManufactureProcesses", "التصنيع"))
        item = self.manu_processes_table.horizontalHeaderItem(0)
        item.setText(_translate("ManufactureProcesses", "المعرف"))
        item = self.manu_processes_table.horizontalHeaderItem(1)
        item.setText(_translate("ManufactureProcesses", "التاريخ"))
        item = self.manu_processes_table.horizontalHeaderItem(2)
        item.setText(_translate("ManufactureProcesses", "الوجبة"))
        item = self.manu_processes_table.horizontalHeaderItem(3)
        item.setText(_translate("ManufactureProcesses", "القيمة"))
        item = self.manu_processes_table.horizontalHeaderItem(4)
        item.setText(_translate("ManufactureProcesses", "معرف العملة"))
        item = self.manu_processes_table.horizontalHeaderItem(5)
        item.setText(_translate("ManufactureProcesses", "العملة"))
        item = self.manu_processes_table.horizontalHeaderItem(6)
        item.setText(_translate("ManufactureProcesses", "الحالة"))
        self.export_btn.setText(_translate("ManufactureProcesses", "تصدير"))
        self.new_manu_btn.setText(_translate("ManufactureProcesses", "...جديد"))
        self.materials_tree.headerItem().setText(0, _translate("ManufactureProcesses", "المجموعة"))
        self.materials_tree.headerItem().setText(1, _translate("ManufactureProcesses", "المادة"))
        self.materials_tree.headerItem().setText(2, _translate("ManufactureProcesses", "معرف المادة"))
        self.materials_tree.headerItem().setText(3, _translate("ManufactureProcesses", "معرف المجموعة"))
        self.delete_manu_btn.setText(_translate("ManufactureProcesses", "الغاء العملية"))
