# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_MaterialMove.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MaterialMove(object):
    def setupUi(self, MaterialMove):
        MaterialMove.setObjectName("MaterialMove")
        MaterialMove.resize(608, 200)
        MaterialMove.setMinimumSize(QtCore.QSize(600, 200))
        MaterialMove.setMaximumSize(QtCore.QSize(608, 300))
        MaterialMove.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.gridLayout = QtWidgets.QGridLayout(MaterialMove)
        self.gridLayout.setObjectName("gridLayout")
        self.add_journal_entry_checkbox = QtWidgets.QCheckBox(MaterialMove)
        self.add_journal_entry_checkbox.setMinimumSize(QtCore.QSize(0, 0))
        self.add_journal_entry_checkbox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.add_journal_entry_checkbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.add_journal_entry_checkbox.setChecked(False)
        self.add_journal_entry_checkbox.setObjectName("add_journal_entry_checkbox")
        self.gridLayout.addWidget(self.add_journal_entry_checkbox, 3, 0, 1, 1)
        self.select_from_account_warehouse_btn = QtWidgets.QToolButton(MaterialMove)
        self.select_from_account_warehouse_btn.setObjectName("select_from_account_warehouse_btn")
        self.gridLayout.addWidget(self.select_from_account_warehouse_btn, 0, 6, 1, 1)
        self.to_account_warehouse_combobox = QtWidgets.QComboBox(MaterialMove)
        self.to_account_warehouse_combobox.setEnabled(True)
        self.to_account_warehouse_combobox.setMinimumSize(QtCore.QSize(0, 0))
        self.to_account_warehouse_combobox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.to_account_warehouse_combobox.setStyleSheet("QComboBox {\n"
"        background-color: #fafafa;\n"
"        border: 1px solid lightgrey;        \n"
"        height: 22px;\n"
"        color: black;\n"
"    }\n"
"    QComboBox::drop-down {\n"
"        border: none;\n"
"    }")
        self.to_account_warehouse_combobox.setObjectName("to_account_warehouse_combobox")
        self.gridLayout.addWidget(self.to_account_warehouse_combobox, 1, 5, 1, 1)
        self.move_btn = QtWidgets.QPushButton(MaterialMove)
        self.move_btn.setObjectName("move_btn")
        self.gridLayout.addWidget(self.move_btn, 5, 5, 1, 1)
        self.label_4 = QtWidgets.QLabel(MaterialMove)
        self.label_4.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.move_unit_combobox = QtWidgets.QComboBox(MaterialMove)
        self.move_unit_combobox.setEnabled(True)
        self.move_unit_combobox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.move_unit_combobox.setStyleSheet("")
        self.move_unit_combobox.setObjectName("move_unit_combobox")
        self.gridLayout.addWidget(self.move_unit_combobox, 2, 2, 1, 1)
        self.journal_entry_item_value = QtWidgets.QLineEdit(MaterialMove)
        self.journal_entry_item_value.setEnabled(False)
        self.journal_entry_item_value.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.journal_entry_item_value.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border: 1px solid #CCC; /* Soft grey outline */\n"
"")
        self.journal_entry_item_value.setObjectName("journal_entry_item_value")
        self.gridLayout.addWidget(self.journal_entry_item_value, 4, 1, 1, 1)
        self.from_account_warehouse_combobox = QtWidgets.QComboBox(MaterialMove)
        self.from_account_warehouse_combobox.setEnabled(True)
        self.from_account_warehouse_combobox.setMinimumSize(QtCore.QSize(0, 0))
        self.from_account_warehouse_combobox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.from_account_warehouse_combobox.setStyleSheet("QComboBox {\n"
"        background-color: #fafafa;\n"
"        border: 1px solid lightgrey;        \n"
"        height: 22px;\n"
"        color: black;\n"
"    }\n"
"    QComboBox::drop-down {\n"
"        border: none;\n"
"    }")
        self.from_account_warehouse_combobox.setObjectName("from_account_warehouse_combobox")
        self.gridLayout.addWidget(self.from_account_warehouse_combobox, 0, 5, 1, 1)
        self.from_warehouse_combobox = QtWidgets.QComboBox(MaterialMove)
        self.from_warehouse_combobox.setEnabled(True)
        self.from_warehouse_combobox.setMinimumSize(QtCore.QSize(60, 0))
        self.from_warehouse_combobox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.from_warehouse_combobox.setStyleSheet("")
        self.from_warehouse_combobox.setObjectName("from_warehouse_combobox")
        self.gridLayout.addWidget(self.from_warehouse_combobox, 2, 5, 1, 1)
        self.label_6 = QtWidgets.QLabel(MaterialMove)
        self.label_6.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(MaterialMove)
        self.label_3.setMinimumSize(QtCore.QSize(0, 0))
        self.label_3.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.journal_entry_origin_combobox = QtWidgets.QComboBox(MaterialMove)
        self.journal_entry_origin_combobox.setEnabled(False)
        self.journal_entry_origin_combobox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.journal_entry_origin_combobox.setStyleSheet("")
        self.journal_entry_origin_combobox.setObjectName("journal_entry_origin_combobox")
        self.gridLayout.addWidget(self.journal_entry_origin_combobox, 5, 2, 1, 1)
        self.select_to_account_warehouse_btn = QtWidgets.QToolButton(MaterialMove)
        self.select_to_account_warehouse_btn.setObjectName("select_to_account_warehouse_btn")
        self.gridLayout.addWidget(self.select_to_account_warehouse_btn, 1, 6, 1, 1)
        self.label_5 = QtWidgets.QLabel(MaterialMove)
        self.label_5.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 4, 1, 1)
        self.label_9 = QtWidgets.QLabel(MaterialMove)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 1)
        self.add_movement_entry_checkbox = QtWidgets.QCheckBox(MaterialMove)
        self.add_movement_entry_checkbox.setMinimumSize(QtCore.QSize(0, 0))
        self.add_movement_entry_checkbox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.add_movement_entry_checkbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.add_movement_entry_checkbox.setChecked(True)
        self.add_movement_entry_checkbox.setObjectName("add_movement_entry_checkbox")
        self.gridLayout.addWidget(self.add_movement_entry_checkbox, 3, 1, 1, 2)
        self.to_warehouse_combobox = QtWidgets.QComboBox(MaterialMove)
        self.to_warehouse_combobox.setEnabled(True)
        self.to_warehouse_combobox.setMinimumSize(QtCore.QSize(50, 0))
        self.to_warehouse_combobox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.to_warehouse_combobox.setStyleSheet("")
        self.to_warehouse_combobox.setObjectName("to_warehouse_combobox")
        self.gridLayout.addWidget(self.to_warehouse_combobox, 3, 5, 1, 1)
        self.select_to_warehouse_btn = QtWidgets.QToolButton(MaterialMove)
        self.select_to_warehouse_btn.setObjectName("select_to_warehouse_btn")
        self.gridLayout.addWidget(self.select_to_warehouse_btn, 3, 6, 1, 1)
        self.journal_entry_item_currency_combobox = QtWidgets.QComboBox(MaterialMove)
        self.journal_entry_item_currency_combobox.setEnabled(False)
        self.journal_entry_item_currency_combobox.setObjectName("journal_entry_item_currency_combobox")
        self.gridLayout.addWidget(self.journal_entry_item_currency_combobox, 4, 2, 1, 1)
        self.warehouse_unit_combobox = QtWidgets.QComboBox(MaterialMove)
        self.warehouse_unit_combobox.setEnabled(False)
        self.warehouse_unit_combobox.setMinimumSize(QtCore.QSize(0, 0))
        self.warehouse_unit_combobox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.warehouse_unit_combobox.setStyleSheet("")
        self.warehouse_unit_combobox.setObjectName("warehouse_unit_combobox")
        self.gridLayout.addWidget(self.warehouse_unit_combobox, 1, 2, 1, 1)
        self.move_quantity_input = QtWidgets.QLineEdit(MaterialMove)
        self.move_quantity_input.setEnabled(True)
        self.move_quantity_input.setMinimumSize(QtCore.QSize(70, 0))
        self.move_quantity_input.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.move_quantity_input.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border: 1px solid #CCC; /* Soft grey outline */\n"
"")
        self.move_quantity_input.setObjectName("move_quantity_input")
        self.gridLayout.addWidget(self.move_quantity_input, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(MaterialMove)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(MaterialMove)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 4, 1, 1)
        self.label = QtWidgets.QLabel(MaterialMove)
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 3, 2, 1)
        self.warehouse_quantity_input = QtWidgets.QLineEdit(MaterialMove)
        self.warehouse_quantity_input.setEnabled(False)
        self.warehouse_quantity_input.setMinimumSize(QtCore.QSize(60, 0))
        self.warehouse_quantity_input.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.warehouse_quantity_input.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border: 1px solid #CCC; /* Soft grey outline */\n"
"")
        self.warehouse_quantity_input.setObjectName("warehouse_quantity_input")
        self.gridLayout.addWidget(self.warehouse_quantity_input, 1, 1, 1, 1)
        self.materials_combobox = QtWidgets.QComboBox(MaterialMove)
        self.materials_combobox.setEnabled(False)
        self.materials_combobox.setMinimumSize(QtCore.QSize(0, 0))
        self.materials_combobox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.materials_combobox.setStyleSheet("QComboBox {\n"
"        background-color: #fafafa;\n"
"        border: 1px solid lightgrey;        \n"
"        height: 22px;\n"
"        color: black;\n"
"    }\n"
"    QComboBox::drop-down {\n"
"        border: none;\n"
"    }")
        self.materials_combobox.setObjectName("materials_combobox")
        self.gridLayout.addWidget(self.materials_combobox, 0, 1, 1, 2)

        self.retranslateUi(MaterialMove)
        QtCore.QMetaObject.connectSlotsByName(MaterialMove)

    def retranslateUi(self, MaterialMove):
        _translate = QtCore.QCoreApplication.translate
        MaterialMove.setWindowTitle(_translate("MaterialMove", "تحريك مادة"))
        self.add_journal_entry_checkbox.setText(_translate("MaterialMove", "توليد سند قيد"))
        self.select_from_account_warehouse_btn.setText(_translate("MaterialMove", "🔎"))
        self.move_btn.setText(_translate("MaterialMove", "تحريك"))
        self.label_4.setText(_translate("MaterialMove", "الكمية المنقولة:"))
        self.label_6.setText(_translate("MaterialMove", "الى مستودع:"))
        self.label_3.setText(_translate("MaterialMove", "الكمية في المستودع:"))
        self.select_to_account_warehouse_btn.setText(_translate("MaterialMove", "🔎"))
        self.label_5.setText(_translate("MaterialMove", "من مستودع:"))
        self.label_9.setText(_translate("MaterialMove", "قيمة السند:"))
        self.add_movement_entry_checkbox.setText(_translate("MaterialMove", "تسجيل عملية النقل"))
        self.select_to_warehouse_btn.setText(_translate("MaterialMove", "🔎"))
        self.label_8.setText(_translate("MaterialMove", "الحساب المقابل:"))
        self.label_7.setText(_translate("MaterialMove", "الحساب:"))
        self.label.setText(_translate("MaterialMove", "المادة:"))
