# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_MoveOutMaterial.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MoveOutMaterial(object):
    def setupUi(self, MoveOutMaterial):
        MoveOutMaterial.setObjectName("MoveOutMaterial")
        MoveOutMaterial.resize(350, 200)
        MoveOutMaterial.setMinimumSize(QtCore.QSize(350, 200))
        MoveOutMaterial.setMaximumSize(QtCore.QSize(350, 200))
        self.gridLayout = QtWidgets.QGridLayout(MoveOutMaterial)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(MoveOutMaterial)
        self.groupBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.quantity_input = QtWidgets.QLineEdit(self.groupBox)
        self.quantity_input.setMinimumSize(QtCore.QSize(150, 0))
        self.quantity_input.setMaximumSize(QtCore.QSize(200, 16777215))
        self.quantity_input.setObjectName("quantity_input")
        self.gridLayout_2.addWidget(self.quantity_input, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.save_btn = QtWidgets.QPushButton(self.groupBox)
        self.save_btn.setObjectName("save_btn")
        self.gridLayout_2.addWidget(self.save_btn, 4, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)
        self.select_account_btn = QtWidgets.QPushButton(self.groupBox)
        self.select_account_btn.setObjectName("select_account_btn")
        self.gridLayout_2.addWidget(self.select_account_btn, 1, 2, 1, 1)
        self.account_combobox = QtWidgets.QComboBox(self.groupBox)
        self.account_combobox.setMinimumSize(QtCore.QSize(100, 0))
        self.account_combobox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.account_combobox.setObjectName("account_combobox")
        self.gridLayout_2.addWidget(self.account_combobox, 1, 1, 1, 1)
        self.opposite_account_combobox = QtWidgets.QComboBox(self.groupBox)
        self.opposite_account_combobox.setMinimumSize(QtCore.QSize(100, 0))
        self.opposite_account_combobox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.opposite_account_combobox.setObjectName("opposite_account_combobox")
        self.gridLayout_2.addWidget(self.opposite_account_combobox, 3, 1, 1, 1)
        self.select_opposite_account_btn = QtWidgets.QPushButton(self.groupBox)
        self.select_opposite_account_btn.setObjectName("select_opposite_account_btn")
        self.gridLayout_2.addWidget(self.select_opposite_account_btn, 3, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)

        self.retranslateUi(MoveOutMaterial)
        QtCore.QMetaObject.connectSlotsByName(MoveOutMaterial)

    def retranslateUi(self, MoveOutMaterial):
        _translate = QtCore.QCoreApplication.translate
        MoveOutMaterial.setWindowTitle(_translate("MoveOutMaterial", "إضافة مادة إلى المستودع"))
        self.label_3.setText(_translate("MoveOutMaterial", "الحساب الهدف:"))
        self.label_2.setText(_translate("MoveOutMaterial", "الكمية:"))
        self.save_btn.setText(_translate("MoveOutMaterial", "حفظ"))
        self.label_5.setText(_translate("MoveOutMaterial", "تاريخ الانتاج:"))
        self.select_account_btn.setText(_translate("MoveOutMaterial", "...اختيار"))
        self.select_opposite_account_btn.setText(_translate("MoveOutMaterial", "...اختيار"))
