# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Media.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Media(object):
    def setupUi(self, Media):
        Media.setObjectName("Media")
        Media.resize(600, 614)
        Media.setLayoutDirection(QtCore.Qt.RightToLeft)
        Media.setStyleSheet("QDialog {\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #0078D4;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    padding: 5px 15px;\n"
"    border-radius: 4px;\n"
"    font-size: 14px;\n"
"    min-width: 80px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1484D7;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #006BBF;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #ccc;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #333333;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    padding: 5px;\n"
"    border: 1px solid #cccccc;\n"
"    border-radius: 4px;\n"
"    background-color: #ffffff;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #0078D4;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Media)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_label = QtWidgets.QLabel(Media)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)
        self.media_table = QtWidgets.QTableWidget(Media)
        self.media_table.setMinimumSize(QtCore.QSize(0, 150))
        self.media_table.setStyleSheet("")
        self.media_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.media_table.setObjectName("media_table")
        self.media_table.setColumnCount(2)
        self.media_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.media_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.media_table.setHorizontalHeaderItem(1, item)
        self.media_table.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.media_table)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.image_preview_label = QtWidgets.QLabel(Media)
        self.image_preview_label.setMinimumSize(QtCore.QSize(400, 300))
        self.image_preview_label.setStyleSheet("QLabel {\n"
"    border: 2px dashed #cccccc;\n"
"    border-radius: 4px;\n"
"    background-color: #f5f5f5;\n"
"}")
        self.image_preview_label.setAlignment(QtCore.Qt.AlignCenter)
        self.image_preview_label.setObjectName("image_preview_label")
        self.verticalLayout.addWidget(self.image_preview_label)
        self.name_label = QtWidgets.QLabel(Media)
        self.name_label.setObjectName("name_label")
        self.verticalLayout.addWidget(self.name_label)
        self.media_name_input = QtWidgets.QLineEdit(Media)
        self.media_name_input.setMinimumSize(QtCore.QSize(200, 30))
        self.media_name_input.setObjectName("media_name_input")
        self.verticalLayout.addWidget(self.media_name_input)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.select_image_btn = QtWidgets.QPushButton(Media)
        self.select_image_btn.setMinimumSize(QtCore.QSize(110, 30))
        self.select_image_btn.setObjectName("select_image_btn")
        self.horizontalLayout.addWidget(self.select_image_btn)
        self.save_btn = QtWidgets.QPushButton(Media)
        self.save_btn.setEnabled(False)
        self.save_btn.setMinimumSize(QtCore.QSize(110, 30))
        self.save_btn.setObjectName("save_btn")
        self.horizontalLayout.addWidget(self.save_btn)
        self.delete_btn = QtWidgets.QPushButton(Media)
        self.delete_btn.setMinimumSize(QtCore.QSize(110, 30))
        self.delete_btn.setStyleSheet("QPushButton {\n"
"    background-color: #dc3545;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #c82333;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #bd2130;\n"
"}")
        self.delete_btn.setObjectName("delete_btn")
        self.horizontalLayout.addWidget(self.delete_btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Media)
        QtCore.QMetaObject.connectSlotsByName(Media)

    def retranslateUi(self, Media):
        _translate = QtCore.QCoreApplication.translate
        Media.setWindowTitle(_translate("Media", "إدارة الوسائط"))
        self.title_label.setText(_translate("Media", "إدارة الوسائط"))
        item = self.media_table.horizontalHeaderItem(0)
        item.setText(_translate("Media", "معرف"))
        item = self.media_table.horizontalHeaderItem(1)
        item.setText(_translate("Media", "اسم الملف"))
        self.image_preview_label.setText(_translate("Media", "معاينة الصورة"))
        self.name_label.setText(_translate("Media", "اسم الملف:"))
        self.media_name_input.setPlaceholderText(_translate("Media", "اسم الملف"))
        self.select_image_btn.setText(_translate("Media", "اختيار صورة"))
        self.save_btn.setText(_translate("Media", "حفظ"))
        self.delete_btn.setText(_translate("Media", "حذف"))
