# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_PeriodStartJournalEntries.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PeriodStartJournalEntries(object):
    def setupUi(self, PeriodStartJournalEntries):
        PeriodStartJournalEntries.setObjectName("PeriodStartJournalEntries")
        PeriodStartJournalEntries.setWindowModality(QtCore.Qt.WindowModal)
        PeriodStartJournalEntries.resize(1420, 744)
        PeriodStartJournalEntries.setLayoutDirection(QtCore.Qt.RightToLeft)
        PeriodStartJournalEntries.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(PeriodStartJournalEntries)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(PeriodStartJournalEntries)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.JournalEntry = QtWidgets.QGroupBox(self.groupBox_2)
        self.JournalEntry.setMaximumSize(QtCore.QSize(300, 16777215))
        self.JournalEntry.setTitle("")
        self.JournalEntry.setObjectName("JournalEntry")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.JournalEntry)
        self.gridLayout_4.setSpacing(1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.filter_creditor_checkbox = QtWidgets.QCheckBox(self.JournalEntry)
        self.filter_creditor_checkbox.setChecked(True)
        self.filter_creditor_checkbox.setObjectName("filter_creditor_checkbox")
        self.gridLayout_4.addWidget(self.filter_creditor_checkbox, 3, 1, 1, 1)
        self.filter_by_account_checkbox = QtWidgets.QCheckBox(self.JournalEntry)
        self.filter_by_account_checkbox.setChecked(True)
        self.filter_by_account_checkbox.setObjectName("filter_by_account_checkbox")
        self.gridLayout_4.addWidget(self.filter_by_account_checkbox, 2, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(106, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 2, 2, 2, 1)
        self.accounts_tree = QtWidgets.QTreeWidget(self.JournalEntry)
        self.accounts_tree.setObjectName("accounts_tree")
        self.gridLayout_4.addWidget(self.accounts_tree, 4, 0, 1, 4)
        self.filter_debtor_checkbox = QtWidgets.QCheckBox(self.JournalEntry)
        self.filter_debtor_checkbox.setChecked(True)
        self.filter_debtor_checkbox.setObjectName("filter_debtor_checkbox")
        self.gridLayout_4.addWidget(self.filter_debtor_checkbox, 3, 0, 1, 1)
        self.filter_by_date_checkbox = QtWidgets.QCheckBox(self.JournalEntry)
        self.filter_by_date_checkbox.setChecked(True)
        self.filter_by_date_checkbox.setObjectName("filter_by_date_checkbox")
        self.gridLayout_4.addWidget(self.filter_by_date_checkbox, 0, 0, 1, 2)
        self.calendar = QtWidgets.QCalendarWidget(self.JournalEntry)
        self.calendar.setMinimumSize(QtCore.QSize(0, 200))
        self.calendar.setMaximumSize(QtCore.QSize(16777215, 200))
        self.calendar.setObjectName("calendar")
        self.gridLayout_4.addWidget(self.calendar, 1, 0, 1, 4)
        self.pushButton_2 = QtWidgets.QPushButton(self.JournalEntry)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_4.addWidget(self.pushButton_2, 5, 2, 1, 1)
        self.gridLayout_8.addWidget(self.JournalEntry, 0, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.update_journal_entry_item_btn = QtWidgets.QPushButton(self.groupBox_5)
        self.update_journal_entry_item_btn.setStyleSheet("QPushButton {\n"
"    background-color: #C8E6C9;\n"
"    color: black;\n"
"    border: 1px solid #81C784;\n"
"    border-radius: 0px;\n"
"    padding: 8px 16px;\n"
"    font-family: Arial;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A5D6A7;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #81C784;\n"
"}\n"
"")
        self.update_journal_entry_item_btn.setObjectName("update_journal_entry_item_btn")
        self.gridLayout_7.addWidget(self.update_journal_entry_item_btn, 2, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 4, 1, 2)
        self.value_input = QtWidgets.QLineEdit(self.groupBox_4)
        self.value_input.setObjectName("value_input")
        self.gridLayout_2.addWidget(self.value_input, 2, 5, 1, 4)
        self.journal_entry_cost_center_combobox = QtWidgets.QComboBox(self.groupBox_4)
        self.journal_entry_cost_center_combobox.setMinimumSize(QtCore.QSize(110, 0))
        self.journal_entry_cost_center_combobox.setObjectName("journal_entry_cost_center_combobox")
        self.gridLayout_2.addWidget(self.journal_entry_cost_center_combobox, 3, 5, 1, 4)
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 3, 3, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(17, 128, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 5, 0, 1, 1)
        self.journal_entry_item_account_combobox = QtWidgets.QComboBox(self.groupBox_4)
        self.journal_entry_item_account_combobox.setMinimumSize(QtCore.QSize(110, 0))
        self.journal_entry_item_account_combobox.setObjectName("journal_entry_item_account_combobox")
        self.gridLayout_2.addWidget(self.journal_entry_item_account_combobox, 0, 1, 1, 1)
        self.journal_entry_item_currency_combobox = QtWidgets.QComboBox(self.groupBox_4)
        self.journal_entry_item_currency_combobox.setObjectName("journal_entry_item_currency_combobox")
        self.gridLayout_2.addWidget(self.journal_entry_item_currency_combobox, 2, 9, 1, 1)
        self.journal_entry_item_type_combobox = QtWidgets.QComboBox(self.groupBox_4)
        self.journal_entry_item_type_combobox.setObjectName("journal_entry_item_type_combobox")
        self.gridLayout_2.addWidget(self.journal_entry_item_type_combobox, 2, 1, 1, 2)
        self.journal_entry_item_opposite_account_combobox = QtWidgets.QComboBox(self.groupBox_4)
        self.journal_entry_item_opposite_account_combobox.setMinimumSize(QtCore.QSize(110, 0))
        self.journal_entry_item_opposite_account_combobox.setObjectName("journal_entry_item_opposite_account_combobox")
        self.gridLayout_2.addWidget(self.journal_entry_item_opposite_account_combobox, 0, 6, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 4, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 2, 3, 1, 1)
        self.journal_entry_distributive_cost_center_accounts_table = QtWidgets.QTableWidget(self.groupBox_4)
        self.journal_entry_distributive_cost_center_accounts_table.setEnabled(False)
        self.journal_entry_distributive_cost_center_accounts_table.setMaximumSize(QtCore.QSize(16777215, 150))
        self.journal_entry_distributive_cost_center_accounts_table.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.journal_entry_distributive_cost_center_accounts_table.setProperty("showDropIndicator", False)
        self.journal_entry_distributive_cost_center_accounts_table.setDragDropOverwriteMode(False)
        self.journal_entry_distributive_cost_center_accounts_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.journal_entry_distributive_cost_center_accounts_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.journal_entry_distributive_cost_center_accounts_table.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.journal_entry_distributive_cost_center_accounts_table.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.journal_entry_distributive_cost_center_accounts_table.setShowGrid(True)
        self.journal_entry_distributive_cost_center_accounts_table.setObjectName("journal_entry_distributive_cost_center_accounts_table")
        self.journal_entry_distributive_cost_center_accounts_table.setColumnCount(5)
        self.journal_entry_distributive_cost_center_accounts_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.journal_entry_distributive_cost_center_accounts_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.journal_entry_distributive_cost_center_accounts_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.journal_entry_distributive_cost_center_accounts_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.journal_entry_distributive_cost_center_accounts_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.journal_entry_distributive_cost_center_accounts_table.setHorizontalHeaderItem(4, item)
        self.journal_entry_distributive_cost_center_accounts_table.horizontalHeader().setVisible(True)
        self.journal_entry_distributive_cost_center_accounts_table.horizontalHeader().setCascadingSectionResizes(False)
        self.journal_entry_distributive_cost_center_accounts_table.horizontalHeader().setSortIndicatorShown(False)
        self.journal_entry_distributive_cost_center_accounts_table.horizontalHeader().setStretchLastSection(True)
        self.journal_entry_distributive_cost_center_accounts_table.verticalHeader().setVisible(False)
        self.journal_entry_distributive_cost_center_accounts_table.verticalHeader().setSortIndicatorShown(False)
        self.journal_entry_distributive_cost_center_accounts_table.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.journal_entry_distributive_cost_center_accounts_table, 4, 1, 2, 9)
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.select_account_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.select_account_btn.setObjectName("select_account_btn")
        self.gridLayout_2.addWidget(self.select_account_btn, 0, 3, 1, 1)
        self.journal_entry_item_statement_input = QtWidgets.QTextEdit(self.groupBox_4)
        self.journal_entry_item_statement_input.setMaximumSize(QtCore.QSize(16777215, 100))
        self.journal_entry_item_statement_input.setObjectName("journal_entry_item_statement_input")
        self.gridLayout_2.addWidget(self.journal_entry_item_statement_input, 1, 1, 1, 9)
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 6, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 1)
        self.journal_entry_distributive_cost_center_accounts_total_percentage_input = QtWidgets.QLineEdit(self.groupBox_4)
        self.journal_entry_distributive_cost_center_accounts_total_percentage_input.setEnabled(False)
        self.journal_entry_distributive_cost_center_accounts_total_percentage_input.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border: black solid 1px;")
        self.journal_entry_distributive_cost_center_accounts_total_percentage_input.setObjectName("journal_entry_distributive_cost_center_accounts_total_percentage_input")
        self.gridLayout_2.addWidget(self.journal_entry_distributive_cost_center_accounts_total_percentage_input, 6, 2, 1, 4)
        self.select_opposite_account_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.select_opposite_account_btn.setObjectName("select_opposite_account_btn")
        self.gridLayout_2.addWidget(self.select_opposite_account_btn, 0, 9, 1, 1)
        self.select_cost_center_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.select_cost_center_btn.setObjectName("select_cost_center_btn")
        self.gridLayout_2.addWidget(self.select_cost_center_btn, 3, 9, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_4, 1, 0, 1, 4)
        self.add_journal_entry_item_btn = QtWidgets.QPushButton(self.groupBox_5)
        self.add_journal_entry_item_btn.setStyleSheet("QPushButton {\n"
"    background-color: #FFF9C4;\n"
"    color: #000000;\n"
"    border: 1px solid #E0E0E0;\n"
"    border-radius: 0px;\n"
"    padding: 8px 16px;\n"
"    font-family: Arial;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FFECB3;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #FFE082;\n"
"}\n"
"")
        self.add_journal_entry_item_btn.setObjectName("add_journal_entry_item_btn")
        self.gridLayout_7.addWidget(self.add_journal_entry_item_btn, 2, 3, 1, 1)
        self.delete_journal_entry_item_btn = QtWidgets.QPushButton(self.groupBox_5)
        self.delete_journal_entry_item_btn.setStyleSheet("QPushButton {\n"
"    background-color: #FFCDD2;\n"
"    color: black;\n"
"    border: 1px solid #E57373;\n"
"    border-radius: 0px;\n"
"    padding: 8px 16px;\n"
"    font-family: Arial;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #EF9A9A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #E57373;\n"
"}\n"
"")
        self.delete_journal_entry_item_btn.setObjectName("delete_journal_entry_item_btn")
        self.gridLayout_7.addWidget(self.delete_journal_entry_item_btn, 2, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem2, 2, 0, 1, 1)
        self.journal_entries_items_table = QtWidgets.QTableWidget(self.groupBox_5)
        self.journal_entries_items_table.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.journal_entries_items_table.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.journal_entries_items_table.setLineWidth(1)
        self.journal_entries_items_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.journal_entries_items_table.setProperty("showDropIndicator", False)
        self.journal_entries_items_table.setDragDropOverwriteMode(False)
        self.journal_entries_items_table.setAlternatingRowColors(True)
        self.journal_entries_items_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.journal_entries_items_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.journal_entries_items_table.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.journal_entries_items_table.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.journal_entries_items_table.setWordWrap(True)
        self.journal_entries_items_table.setObjectName("journal_entries_items_table")
        self.journal_entries_items_table.setColumnCount(11)
        self.journal_entries_items_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.journal_entries_items_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.journal_entries_items_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.journal_entries_items_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.journal_entries_items_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.journal_entries_items_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.journal_entries_items_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.journal_entries_items_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.journal_entries_items_table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.journal_entries_items_table.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.journal_entries_items_table.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.journal_entries_items_table.setHorizontalHeaderItem(10, item)
        self.journal_entries_items_table.horizontalHeader().setVisible(True)
        self.journal_entries_items_table.horizontalHeader().setStretchLastSection(True)
        self.journal_entries_items_table.verticalHeader().setVisible(False)
        self.gridLayout_7.addWidget(self.journal_entries_items_table, 0, 0, 1, 4)
        self.gridLayout_8.addWidget(self.groupBox_5, 0, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setSpacing(4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.journals_entries_table = QtWidgets.QTableWidget(self.groupBox)
        self.journals_entries_table.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.journals_entries_table.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.journals_entries_table.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.journals_entries_table.setLineWidth(1)
        self.journals_entries_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.journals_entries_table.setProperty("showDropIndicator", False)
        self.journals_entries_table.setDragDropOverwriteMode(False)
        self.journals_entries_table.setAlternatingRowColors(True)
        self.journals_entries_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.journals_entries_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.journals_entries_table.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.journals_entries_table.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.journals_entries_table.setWordWrap(True)
        self.journals_entries_table.setObjectName("journals_entries_table")
        self.journals_entries_table.setColumnCount(5)
        self.journals_entries_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.journals_entries_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.journals_entries_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.journals_entries_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.journals_entries_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.journals_entries_table.setHorizontalHeaderItem(4, item)
        self.journals_entries_table.horizontalHeader().setVisible(False)
        self.journals_entries_table.horizontalHeader().setStretchLastSection(True)
        self.journals_entries_table.verticalHeader().setVisible(False)
        self.gridLayout_5.addWidget(self.journals_entries_table, 0, 0, 1, 4)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_6.setSpacing(1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 3, 1, 1)
        self.journal_entry_date_input = QtWidgets.QDateEdit(self.groupBox_3)
        self.journal_entry_date_input.setObjectName("journal_entry_date_input")
        self.gridLayout_6.addWidget(self.journal_entry_date_input, 0, 1, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 0, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 0, 0, 1, 1)
        self.journal_entry_currency_combobox = QtWidgets.QComboBox(self.groupBox_3)
        self.journal_entry_currency_combobox.setObjectName("journal_entry_currency_combobox")
        self.gridLayout_6.addWidget(self.journal_entry_currency_combobox, 0, 4, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_3, 1, 0, 1, 4)
        spacerItem4 = QtWidgets.QSpacerItem(54, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem4, 2, 0, 1, 1)
        self.update_journal_entry_btn = QtWidgets.QPushButton(self.groupBox)
        self.update_journal_entry_btn.setStyleSheet("QPushButton {\n"
"    background-color: #C8E6C9;\n"
"    color: black;\n"
"    border: 1px solid #81C784;\n"
"    border-radius: 0px;\n"
"    padding: 8px 16px;\n"
"    font-family: Arial;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A5D6A7;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #81C784;\n"
"}\n"
"")
        self.update_journal_entry_btn.setObjectName("update_journal_entry_btn")
        self.gridLayout_5.addWidget(self.update_journal_entry_btn, 2, 1, 1, 1)
        self.delete_journal_entry_btn = QtWidgets.QPushButton(self.groupBox)
        self.delete_journal_entry_btn.setStyleSheet("QPushButton {\n"
"    background-color: #FFCDD2;\n"
"    color: black;\n"
"    border: 1px solid #E57373;\n"
"    border-radius: 0px;\n"
"    padding: 8px 16px;\n"
"    font-family: Arial;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #EF9A9A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #E57373;\n"
"}\n"
"")
        self.delete_journal_entry_btn.setObjectName("delete_journal_entry_btn")
        self.gridLayout_5.addWidget(self.delete_journal_entry_btn, 2, 2, 1, 1)
        self.add_journal_entry_btn = QtWidgets.QPushButton(self.groupBox)
        self.add_journal_entry_btn.setStyleSheet("QPushButton {\n"
"    background-color: #FFF9C4;\n"
"    color: #000000;\n"
"    border: 1px solid #E0E0E0;\n"
"    border-radius: 0px;\n"
"    padding: 8px 16px;\n"
"    font-family: Arial;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FFECB3;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #FFE082;\n"
"}\n"
"")
        self.add_journal_entry_btn.setObjectName("add_journal_entry_btn")
        self.gridLayout_5.addWidget(self.add_journal_entry_btn, 2, 3, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 1)

        self.retranslateUi(PeriodStartJournalEntries)
        QtCore.QMetaObject.connectSlotsByName(PeriodStartJournalEntries)

    def retranslateUi(self, PeriodStartJournalEntries):
        _translate = QtCore.QCoreApplication.translate
        PeriodStartJournalEntries.setWindowTitle(_translate("PeriodStartJournalEntries", "القيد الافتتاحي"))
        self.filter_creditor_checkbox.setText(_translate("PeriodStartJournalEntries", "دائن"))
        self.filter_by_account_checkbox.setText(_translate("PeriodStartJournalEntries", "ترشيح حسب الحساب"))
        self.accounts_tree.headerItem().setText(0, _translate("PeriodStartJournalEntries", "الرمز"))
        self.accounts_tree.headerItem().setText(1, _translate("PeriodStartJournalEntries", "الحساب"))
        self.accounts_tree.headerItem().setText(2, _translate("PeriodStartJournalEntries", "المعرف"))
        self.filter_debtor_checkbox.setText(_translate("PeriodStartJournalEntries", "مدين"))
        self.filter_by_date_checkbox.setText(_translate("PeriodStartJournalEntries", "ترشيح حسب التاريخ"))
        self.pushButton_2.setText(_translate("PeriodStartJournalEntries", "إدارة الحسابات"))
        self.update_journal_entry_item_btn.setText(_translate("PeriodStartJournalEntries", "حفظ"))
        self.groupBox_4.setTitle(_translate("PeriodStartJournalEntries", "تعديل"))
        self.label_6.setText(_translate("PeriodStartJournalEntries", "الحساب المقابل:"))
        self.label_11.setText(_translate("PeriodStartJournalEntries", "مركز الكلفة:"))
        self.label_12.setText(_translate("PeriodStartJournalEntries", "النسب:"))
        self.label_10.setText(_translate("PeriodStartJournalEntries", "القيمة:"))
        item = self.journal_entry_distributive_cost_center_accounts_table.horizontalHeaderItem(0)
        item.setText(_translate("PeriodStartJournalEntries", "المعرف"))
        item = self.journal_entry_distributive_cost_center_accounts_table.horizontalHeaderItem(1)
        item.setText(_translate("PeriodStartJournalEntries", "معرف الحساب"))
        item = self.journal_entry_distributive_cost_center_accounts_table.horizontalHeaderItem(2)
        item.setText(_translate("PeriodStartJournalEntries", "اسم الحساب"))
        item = self.journal_entry_distributive_cost_center_accounts_table.horizontalHeaderItem(3)
        item.setText(_translate("PeriodStartJournalEntries", "النسبة"))
        item = self.journal_entry_distributive_cost_center_accounts_table.horizontalHeaderItem(4)
        item.setText(_translate("PeriodStartJournalEntries", "القيمة"))
        self.label_5.setText(_translate("PeriodStartJournalEntries", "الحساب:"))
        self.label_7.setText(_translate("PeriodStartJournalEntries", "البيان:"))
        self.select_account_btn.setText(_translate("PeriodStartJournalEntries", "...اختيار"))
        self.label_13.setText(_translate("PeriodStartJournalEntries", "مجموع النسب:"))
        self.label_9.setText(_translate("PeriodStartJournalEntries", "الطبيعة:"))
        self.select_opposite_account_btn.setText(_translate("PeriodStartJournalEntries", "...اختيار"))
        self.select_cost_center_btn.setText(_translate("PeriodStartJournalEntries", "...اختيار"))
        self.add_journal_entry_item_btn.setText(_translate("PeriodStartJournalEntries", "...إضافة عنصر"))
        self.delete_journal_entry_item_btn.setText(_translate("PeriodStartJournalEntries", "حذف"))
        self.journal_entries_items_table.setSortingEnabled(True)
        item = self.journal_entries_items_table.horizontalHeaderItem(0)
        item.setText(_translate("PeriodStartJournalEntries", "المعرف"))
        item = self.journal_entries_items_table.horizontalHeaderItem(1)
        item.setText(_translate("PeriodStartJournalEntries", "معرف سند القيد"))
        item = self.journal_entries_items_table.horizontalHeaderItem(2)
        item.setText(_translate("PeriodStartJournalEntries", "معرف الحساب"))
        item = self.journal_entries_items_table.horizontalHeaderItem(3)
        item.setText(_translate("PeriodStartJournalEntries", "الحساب"))
        item = self.journal_entries_items_table.horizontalHeaderItem(4)
        item.setText(_translate("PeriodStartJournalEntries", "مدين"))
        item = self.journal_entries_items_table.horizontalHeaderItem(5)
        item.setText(_translate("PeriodStartJournalEntries", "دائن"))
        item = self.journal_entries_items_table.horizontalHeaderItem(6)
        item.setText(_translate("PeriodStartJournalEntries", "البيان"))
        item = self.journal_entries_items_table.horizontalHeaderItem(7)
        item.setText(_translate("PeriodStartJournalEntries", "معرف العملة"))
        item = self.journal_entries_items_table.horizontalHeaderItem(8)
        item.setText(_translate("PeriodStartJournalEntries", "العملة"))
        item = self.journal_entries_items_table.horizontalHeaderItem(9)
        item.setText(_translate("PeriodStartJournalEntries", "معرف الحساب المقابل"))
        item = self.journal_entries_items_table.horizontalHeaderItem(10)
        item.setText(_translate("PeriodStartJournalEntries", "الحساب المقابل"))
        self.journals_entries_table.setSortingEnabled(True)
        item = self.journals_entries_table.horizontalHeaderItem(0)
        item.setText(_translate("PeriodStartJournalEntries", "المعرف"))
        item = self.journals_entries_table.horizontalHeaderItem(1)
        item.setText(_translate("PeriodStartJournalEntries", "التاريخ"))
        item = self.journals_entries_table.horizontalHeaderItem(2)
        item.setText(_translate("PeriodStartJournalEntries", "معرف العملة"))
        item = self.journals_entries_table.horizontalHeaderItem(3)
        item.setText(_translate("PeriodStartJournalEntries", "العملة"))
        item = self.journals_entries_table.horizontalHeaderItem(4)
        item.setText(_translate("PeriodStartJournalEntries", "تاريخ التسجيل"))
        self.groupBox_3.setTitle(_translate("PeriodStartJournalEntries", "تعديل"))
        self.label.setText(_translate("PeriodStartJournalEntries", "العملة:"))
        self.journal_entry_date_input.setDisplayFormat(_translate("PeriodStartJournalEntries", "dd/M/yyyy"))
        self.label_2.setText(_translate("PeriodStartJournalEntries", "التاريخ:"))
        self.update_journal_entry_btn.setText(_translate("PeriodStartJournalEntries", "حفظ"))
        self.delete_journal_entry_btn.setText(_translate("PeriodStartJournalEntries", "حذف"))
        self.add_journal_entry_btn.setText(_translate("PeriodStartJournalEntries", "...إضافة قيد"))
