# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Position_Report.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Position_Report(object):
    def setupUi(self, Position_Report):
        Position_Report.setObjectName("Position_Report")
        Position_Report.setWindowModality(QtCore.Qt.WindowModal)
        Position_Report.resize(982, 618)
        Position_Report.setMinimumSize(QtCore.QSize(0, 0))
        Position_Report.setMaximumSize(QtCore.QSize(1686786, 1686786))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/coin_dollar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Position_Report.setWindowIcon(icon)
        Position_Report.setLayoutDirection(QtCore.Qt.RightToLeft)
        Position_Report.setModal(True)
        self.gridLayout_2 = QtWidgets.QGridLayout(Position_Report)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(Position_Report)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 50))
        self.groupBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 5, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.from_date = QtWidgets.QDateEdit(self.groupBox)
        self.from_date.setObjectName("from_date")
        self.gridLayout.addWidget(self.from_date, 0, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(343, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 8, 1, 1)
        self.position_combobox = QtWidgets.QComboBox(self.groupBox)
        self.position_combobox.setMinimumSize(QtCore.QSize(125, 0))
        self.position_combobox.setStyleSheet("QComboBox {\n"
"        background-color: #fafafa;\n"
"        border: 1px solid lightgrey;        \n"
"        height: 22px;\n"
"        color: black;\n"
"    }\n"
"    QComboBox::drop-down {\n"
"        border: none;\n"
"    }")
        self.position_combobox.setObjectName("position_combobox")
        self.gridLayout.addWidget(self.position_combobox, 0, 1, 1, 1)
        self.calculate_btn = QtWidgets.QPushButton(self.groupBox)
        self.calculate_btn.setObjectName("calculate_btn")
        self.gridLayout.addWidget(self.calculate_btn, 0, 7, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 3, 1, 1)
        self.to_date = QtWidgets.QDateEdit(self.groupBox)
        self.to_date.setObjectName("to_date")
        self.gridLayout.addWidget(self.to_date, 0, 6, 1, 1)
        self.select_position_btn = QtWidgets.QToolButton(self.groupBox)
        self.select_position_btn.setObjectName("select_position_btn")
        self.gridLayout.addWidget(self.select_position_btn, 0, 2, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 2)
        self.groupBox_2 = QtWidgets.QGroupBox(Position_Report)
        self.groupBox_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.salary_change_chart = QtWidgets.QGroupBox(self.groupBox_2)
        self.salary_change_chart.setTitle("")
        self.salary_change_chart.setObjectName("salary_change_chart")
        self.gridLayout_3.addWidget(self.salary_change_chart, 1, 3, 1, 1)
        self.department_info = QtWidgets.QGroupBox(self.groupBox_2)
        self.department_info.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.department_info.setTitle("")
        self.department_info.setObjectName("department_info")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.department_info)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tableWidget = QtWidgets.QTableWidget(self.department_info)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.gridLayout_4.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.department_info, 0, 0, 1, 1)
        self.employee_num_chart = QtWidgets.QGroupBox(self.groupBox_2)
        self.employee_num_chart.setTitle("")
        self.employee_num_chart.setObjectName("employee_num_chart")
        self.gridLayout_3.addWidget(self.employee_num_chart, 1, 0, 1, 1)
        self.avg_salary_chart = QtWidgets.QGroupBox(self.groupBox_2)
        self.avg_salary_chart.setTitle("")
        self.avg_salary_chart.setObjectName("avg_salary_chart")
        self.gridLayout_3.addWidget(self.avg_salary_chart, 0, 3, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 0, 1, 2)

        self.retranslateUi(Position_Report)
        QtCore.QMetaObject.connectSlotsByName(Position_Report)

    def retranslateUi(self, Position_Report):
        _translate = QtCore.QCoreApplication.translate
        Position_Report.setWindowTitle(_translate("Position_Report", "تقرير منصب"))
        self.label_2.setText(_translate("Position_Report", "إلى:"))
        self.label_3.setText(_translate("Position_Report", "المنصب:"))
        self.calculate_btn.setText(_translate("Position_Report", "حساب"))
        self.label.setText(_translate("Position_Report", "من:"))
        self.select_position_btn.setText(_translate("Position_Report", "🔎"))
        self.groupBox_2.setTitle(_translate("Position_Report", "GroupBox"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Position_Report", "#"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Position_Report", "القيمة"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Position_Report", "العملة"))
