# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_QuantitiesReport.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QuantitiesReport(object):
    def setupUi(self, QuantitiesReport):
        QuantitiesReport.setObjectName("QuantitiesReport")
        QuantitiesReport.setWindowModality(QtCore.Qt.WindowModal)
        QuantitiesReport.resize(1019, 587)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("graphics/icon.xpm"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        QuantitiesReport.setWindowIcon(icon)
        QuantitiesReport.setModal(True)
        self.gridLayout_2 = QtWidgets.QGridLayout(QuantitiesReport)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.chart_groupbox = QtWidgets.QGroupBox(QuantitiesReport)
        self.chart_groupbox.setTitle("")
        self.chart_groupbox.setObjectName("chart_groupbox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.chart_groupbox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2.addWidget(self.chart_groupbox, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(QuantitiesReport)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 60))
        self.groupBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.select_product_btn = QtWidgets.QPushButton(self.groupBox)
        self.select_product_btn.setObjectName("select_product_btn")
        self.gridLayout.addWidget(self.select_product_btn, 0, 2, 1, 1)
        self.calc_btn = QtWidgets.QPushButton(self.groupBox)
        self.calc_btn.setObjectName("calc_btn")
        self.gridLayout.addWidget(self.calc_btn, 0, 7, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.product_combobox = QtWidgets.QComboBox(self.groupBox)
        self.product_combobox.setMaximumSize(QtCore.QSize(500, 16777215))
        self.product_combobox.setStyleSheet("QComboBox {\n"
"        background-color: #fafafa;\n"
"        border: 1px solid lightgrey;        \n"
"        height: 22px;\n"
"        color: black;\n"
"    }\n"
"    QComboBox::drop-down {\n"
"        border: none;\n"
"    }")
        self.product_combobox.setObjectName("product_combobox")
        self.gridLayout.addWidget(self.product_combobox, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 8, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(QuantitiesReport)
        QtCore.QMetaObject.connectSlotsByName(QuantitiesReport)

    def retranslateUi(self, QuantitiesReport):
        _translate = QtCore.QCoreApplication.translate
        QuantitiesReport.setWindowTitle(_translate("QuantitiesReport", "خطة الانتاج"))
        self.select_product_btn.setText(_translate("QuantitiesReport", "...اختيار"))
        self.calc_btn.setText(_translate("QuantitiesReport", "حساب النتيجة"))
        self.label.setText(_translate("QuantitiesReport", "المنتج:"))
