# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_RemoveMaterialFromWarehouse.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RemoveMaterialFromWarehouse(object):
    def setupUi(self, RemoveMaterialFromWarehouse):
        RemoveMaterialFromWarehouse.setObjectName("RemoveMaterialFromWarehouse")
        RemoveMaterialFromWarehouse.resize(521, 200)
        RemoveMaterialFromWarehouse.setMinimumSize(QtCore.QSize(521, 200))
        RemoveMaterialFromWarehouse.setMaximumSize(QtCore.QSize(521, 200))
        self.gridLayout = QtWidgets.QGridLayout(RemoveMaterialFromWarehouse)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(RemoveMaterialFromWarehouse)
        self.groupBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.quantity_input = QtWidgets.QLineEdit(self.groupBox)
        self.quantity_input.setMinimumSize(QtCore.QSize(150, 0))
        self.quantity_input.setMaximumSize(QtCore.QSize(200, 16777215))
        self.quantity_input.setObjectName("quantity_input")
        self.gridLayout_2.addWidget(self.quantity_input, 0, 1, 1, 2)
        self.unit_combobox = QtWidgets.QComboBox(self.groupBox)
        self.unit_combobox.setMinimumSize(QtCore.QSize(100, 0))
        self.unit_combobox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.unit_combobox.setObjectName("unit_combobox")
        self.gridLayout_2.addWidget(self.unit_combobox, 0, 5, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1)
        self.price_input = QtWidgets.QLineEdit(self.groupBox)
        self.price_input.setMaximumSize(QtCore.QSize(200, 16777215))
        self.price_input.setObjectName("price_input")
        self.gridLayout_2.addWidget(self.price_input, 1, 1, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 4, 1, 1)
        self.currency_combobox = QtWidgets.QComboBox(self.groupBox)
        self.currency_combobox.setMinimumSize(QtCore.QSize(200, 0))
        self.currency_combobox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.currency_combobox.setObjectName("currency_combobox")
        self.gridLayout_2.addWidget(self.currency_combobox, 1, 5, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 1)
        self.account_combobox = QtWidgets.QComboBox(self.groupBox)
        self.account_combobox.setMinimumSize(QtCore.QSize(100, 0))
        self.account_combobox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.account_combobox.setStyleSheet("QComboBox {\n"
"        background-color: #fafafa;\n"
"        border: 1px solid lightgrey;        \n"
"        height: 22px;\n"
"        color: black;\n"
"    }\n"
"    QComboBox::drop-down {\n"
"        border: none;\n"
"    }")
        self.account_combobox.setObjectName("account_combobox")
        self.gridLayout_2.addWidget(self.account_combobox, 2, 1, 1, 1)
        self.select_account_btn = QtWidgets.QPushButton(self.groupBox)
        self.select_account_btn.setObjectName("select_account_btn")
        self.gridLayout_2.addWidget(self.select_account_btn, 2, 2, 1, 2)
        self.save_btn = QtWidgets.QPushButton(self.groupBox)
        self.save_btn.setObjectName("save_btn")
        self.gridLayout_2.addWidget(self.save_btn, 2, 5, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 4, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)

        self.retranslateUi(RemoveMaterialFromWarehouse)
        QtCore.QMetaObject.connectSlotsByName(RemoveMaterialFromWarehouse)

    def retranslateUi(self, RemoveMaterialFromWarehouse):
        _translate = QtCore.QCoreApplication.translate
        RemoveMaterialFromWarehouse.setWindowTitle(_translate("RemoveMaterialFromWarehouse", "إضافة مادة إلى المستودع"))
        self.label_2.setText(_translate("RemoveMaterialFromWarehouse", "الكمية:"))
        self.label_8.setText(_translate("RemoveMaterialFromWarehouse", "السعر:"))
        self.label_7.setText(_translate("RemoveMaterialFromWarehouse", "العملة:"))
        self.label_9.setText(_translate("RemoveMaterialFromWarehouse", "الحساب:"))
        self.select_account_btn.setText(_translate("RemoveMaterialFromWarehouse", "...اختيار"))
        self.save_btn.setText(_translate("RemoveMaterialFromWarehouse", "اخراج"))
        self.label_4.setText(_translate("RemoveMaterialFromWarehouse", "الواحدة:"))
