# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_ReOrderMaterialReport.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReOrderMaterialReport(object):
    def setupUi(self, ReOrderMaterialReport):
        ReOrderMaterialReport.setObjectName("ReOrderMaterialReport")
        ReOrderMaterialReport.setWindowModality(QtCore.Qt.WindowModal)
        ReOrderMaterialReport.resize(953, 583)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("graphics/icon.xpm"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ReOrderMaterialReport.setWindowIcon(icon)
        ReOrderMaterialReport.setModal(True)
        self.gridLayout_2 = QtWidgets.QGridLayout(ReOrderMaterialReport)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(ReOrderMaterialReport)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.materials_table = QtWidgets.QTableWidget(self.groupBox_2)
        self.materials_table.setMaximumSize(QtCore.QSize(16777215, 500))
        self.materials_table.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.materials_table.setObjectName("materials_table")
        self.materials_table.setColumnCount(5)
        self.materials_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.materials_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.materials_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.materials_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.materials_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.materials_table.setHorizontalHeaderItem(4, item)
        self.materials_table.horizontalHeader().setStretchLastSection(True)
        self.materials_table.verticalHeader().setStretchLastSection(False)
        self.gridLayout_3.addWidget(self.materials_table, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(ReOrderMaterialReport)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.select_warehouse_btn = QtWidgets.QToolButton(self.groupBox)
        self.select_warehouse_btn.setObjectName("select_warehouse_btn")
        self.gridLayout.addWidget(self.select_warehouse_btn, 0, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.calc_btn = QtWidgets.QPushButton(self.groupBox)
        self.calc_btn.setObjectName("calc_btn")
        self.gridLayout.addWidget(self.calc_btn, 0, 5, 1, 1)
        self.percent_input = QtWidgets.QLineEdit(self.groupBox)
        self.percent_input.setObjectName("percent_input")
        self.gridLayout.addWidget(self.percent_input, 0, 1, 1, 1)
        self.warehouse_combobox = QtWidgets.QComboBox(self.groupBox)
        self.warehouse_combobox.setMinimumSize(QtCore.QSize(125, 0))
        self.warehouse_combobox.setStyleSheet("QComboBox {\n"
"        background-color: #fafafa;\n"
"        border: 1px solid lightgrey;        \n"
"        height: 22px;\n"
"        color: black;\n"
"    }\n"
"    QComboBox::drop-down {\n"
"        border: none;\n"
"    }")
        self.warehouse_combobox.setObjectName("warehouse_combobox")
        self.gridLayout.addWidget(self.warehouse_combobox, 0, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 6, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(ReOrderMaterialReport)
        QtCore.QMetaObject.connectSlotsByName(ReOrderMaterialReport)

    def retranslateUi(self, ReOrderMaterialReport):
        _translate = QtCore.QCoreApplication.translate
        ReOrderMaterialReport.setWindowTitle(_translate("ReOrderMaterialReport", "تقرير اعادة الطلب"))
        item = self.materials_table.horizontalHeaderItem(0)
        item.setText(_translate("ReOrderMaterialReport", "المعرف"))
        item = self.materials_table.horizontalHeaderItem(1)
        item.setText(_translate("ReOrderMaterialReport", "الكود"))
        item = self.materials_table.horizontalHeaderItem(2)
        item.setText(_translate("ReOrderMaterialReport", "المنتج"))
        item = self.materials_table.horizontalHeaderItem(3)
        item.setText(_translate("ReOrderMaterialReport", "الحد الأدنى"))
        item = self.materials_table.horizontalHeaderItem(4)
        item.setText(_translate("ReOrderMaterialReport", "الكمية الحالية"))
        self.label_2.setText(_translate("ReOrderMaterialReport", "المستودع:"))
        self.select_warehouse_btn.setText(_translate("ReOrderMaterialReport", "🔎"))
        self.label_3.setText(_translate("ReOrderMaterialReport", "النسبة:"))
        self.calc_btn.setText(_translate("ReOrderMaterialReport", "حساب النتيجة"))
