# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_ResetPassword.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ResetPassword(object):
    def setupUi(self, ResetPassword):
        ResetPassword.setObjectName("ResetPassword")
        ResetPassword.setWindowModality(QtCore.Qt.WindowModal)
        ResetPassword.resize(264, 149)
        ResetPassword.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.gridLayout = QtWidgets.QGridLayout(ResetPassword)
        self.gridLayout.setObjectName("gridLayout")
        self.password_label = QtWidgets.QLabel(ResetPassword)
        self.password_label.setObjectName("password_label")
        self.gridLayout.addWidget(self.password_label, 0, 0, 1, 1)
        self.password_input = QtWidgets.QLineEdit(ResetPassword)
        self.password_input.setObjectName("password_input")
        self.gridLayout.addWidget(self.password_input, 1, 0, 1, 1)
        self.password_toggle = QtWidgets.QPushButton(ResetPassword)
        self.password_toggle.setMaximumSize(QtCore.QSize(20, 16777215))
        self.password_toggle.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: black;\n"
"    font-size: 24px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 0, 0, 0.1);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 0.2);\n"
"}")
        self.password_toggle.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/eye_closed.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.password_toggle.setIcon(icon)
        self.password_toggle.setObjectName("password_toggle")
        self.gridLayout.addWidget(self.password_toggle, 1, 1, 1, 1)
        self.confirm_password_label = QtWidgets.QLabel(ResetPassword)
        self.confirm_password_label.setObjectName("confirm_password_label")
        self.gridLayout.addWidget(self.confirm_password_label, 2, 0, 1, 1)
        self.confirm_password_input = QtWidgets.QLineEdit(ResetPassword)
        self.confirm_password_input.setObjectName("confirm_password_input")
        self.gridLayout.addWidget(self.confirm_password_input, 3, 0, 1, 1)
        self.confirm_password_toggle = QtWidgets.QPushButton(ResetPassword)
        self.confirm_password_toggle.setMaximumSize(QtCore.QSize(20, 16777215))
        self.confirm_password_toggle.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: black;\n"
"    font-size: 24px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 0, 0, 0.1);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 0.2);\n"
"}")
        self.confirm_password_toggle.setText("")
        self.confirm_password_toggle.setIcon(icon)
        self.confirm_password_toggle.setObjectName("confirm_password_toggle")
        self.gridLayout.addWidget(self.confirm_password_toggle, 3, 1, 1, 1)
        self.save_btn = QtWidgets.QPushButton(ResetPassword)
        self.save_btn.setObjectName("save_btn")
        self.gridLayout.addWidget(self.save_btn, 4, 0, 1, 1)

        self.retranslateUi(ResetPassword)
        QtCore.QMetaObject.connectSlotsByName(ResetPassword)

    def retranslateUi(self, ResetPassword):
        _translate = QtCore.QCoreApplication.translate
        ResetPassword.setWindowTitle(_translate("ResetPassword", "تغيير كلمة المرور"))
        self.password_label.setText(_translate("ResetPassword", "كلمة المرور الجديدة"))
        self.confirm_password_label.setText(_translate("ResetPassword", "تأكيد كلمة المرور"))
        self.save_btn.setText(_translate("ResetPassword", "موافق"))
