# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_SaveFinancialStatement.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SaveFinancialStatement(object):
    def setupUi(self, SaveFinancialStatement):
        SaveFinancialStatement.setObjectName("SaveFinancialStatement")
        SaveFinancialStatement.resize(344, 232)
        self.gridLayout_2 = QtWidgets.QGridLayout(SaveFinancialStatement)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(SaveFinancialStatement)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label)
        self.financial_statement_name = QtWidgets.QLineEdit(self.groupBox)
        self.financial_statement_name.setObjectName("financial_statement_name")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.financial_statement_name)
        self.save_btn = QtWidgets.QPushButton(self.groupBox)
        self.save_btn.setObjectName("save_btn")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.save_btn)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_2)
        self.final_financial_statement_name = QtWidgets.QLineEdit(self.groupBox)
        self.final_financial_statement_name.setReadOnly(True)
        self.final_financial_statement_name.setObjectName("final_financial_statement_name")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.final_financial_statement_name)
        self.edit_final_financial_statement_btn = QtWidgets.QPushButton(self.groupBox)
        self.edit_final_financial_statement_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.edit_final_financial_statement_btn.setObjectName("edit_final_financial_statement_btn")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.edit_final_financial_statement_btn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(4, QtWidgets.QFormLayout.SpanningRole, spacerItem)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(SaveFinancialStatement)
        QtCore.QMetaObject.connectSlotsByName(SaveFinancialStatement)

    def retranslateUi(self, SaveFinancialStatement):
        _translate = QtCore.QCoreApplication.translate
        SaveFinancialStatement.setWindowTitle(_translate("SaveFinancialStatement", "إضافة قائمة مالية"))
        self.label.setText(_translate("SaveFinancialStatement", "اسم القائمة المالية:"))
        self.save_btn.setText(_translate("SaveFinancialStatement", "حفظ"))
        self.label_2.setText(_translate("SaveFinancialStatement", "القائمة المالية الختامية:"))
        self.edit_final_financial_statement_btn.setText(_translate("SaveFinancialStatement", "تعديل"))
