# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_SimplePlan.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SimplePlan(object):
    def setupUi(self, SimplePlan):
        SimplePlan.setObjectName("SimplePlan")
        SimplePlan.setWindowModality(QtCore.Qt.WindowModal)
        SimplePlan.resize(823, 614)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("graphics/icon.xpm"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SimplePlan.setWindowIcon(icon)
        SimplePlan.setLayoutDirection(QtCore.Qt.RightToLeft)
        SimplePlan.setModal(True)
        self.gridLayout_3 = QtWidgets.QGridLayout(SimplePlan)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(SimplePlan)
        self.groupBox_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.plan_items_table = QtWidgets.QTableWidget(self.groupBox_2)
        self.plan_items_table.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.plan_items_table.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.plan_items_table.setObjectName("plan_items_table")
        self.plan_items_table.setColumnCount(5)
        self.plan_items_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.plan_items_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.plan_items_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.plan_items_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.plan_items_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.plan_items_table.setHorizontalHeaderItem(4, item)
        self.plan_items_table.horizontalHeader().setStretchLastSection(False)
        self.plan_items_table.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.plan_items_table, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 1, 0, 1, 2)
        self.groupBox_3 = QtWidgets.QGroupBox(SimplePlan)
        self.groupBox_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.batches_input = QtWidgets.QLineEdit(self.groupBox_3)
        self.batches_input.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.batches_input.setObjectName("batches_input")
        self.gridLayout.addWidget(self.batches_input, 0, 4, 1, 1)
        self.add_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.add_btn.setObjectName("add_btn")
        self.gridLayout.addWidget(self.add_btn, 0, 5, 1, 1)
        self.products = QtWidgets.QComboBox(self.groupBox_3)
        self.products.setMinimumSize(QtCore.QSize(125, 0))
        self.products.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.products.setStyleSheet("QComboBox {\n"
"        background-color: #fafafa;\n"
"        border: 1px solid lightgrey;        \n"
"        height: 22px;\n"
"        color: black;\n"
"    }\n"
"    QComboBox::drop-down {\n"
"        border: none;\n"
"    }")
        self.products.setObjectName("products")
        self.gridLayout.addWidget(self.products, 0, 1, 1, 1)
        self.products_btn = QtWidgets.QToolButton(self.groupBox_3)
        self.products_btn.setObjectName("products_btn")
        self.gridLayout.addWidget(self.products_btn, 0, 2, 1, 1)
        self.calc_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.calc_btn.setObjectName("calc_btn")
        self.gridLayout.addWidget(self.calc_btn, 0, 6, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_3, 0, 0, 1, 2)
        self.clear_btn = QtWidgets.QPushButton(SimplePlan)
        self.clear_btn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.clear_btn.setMouseTracking(False)
        self.clear_btn.setObjectName("clear_btn")
        self.gridLayout_3.addWidget(self.clear_btn, 2, 1, 1, 1)

        self.retranslateUi(SimplePlan)
        QtCore.QMetaObject.connectSlotsByName(SimplePlan)

    def retranslateUi(self, SimplePlan):
        _translate = QtCore.QCoreApplication.translate
        SimplePlan.setWindowTitle(_translate("SimplePlan", "خطة الانتاج"))
        item = self.plan_items_table.horizontalHeaderItem(0)
        item.setText(_translate("SimplePlan", "المعرف"))
        item = self.plan_items_table.horizontalHeaderItem(1)
        item.setText(_translate("SimplePlan", "الكود"))
        item = self.plan_items_table.horizontalHeaderItem(2)
        item.setText(_translate("SimplePlan", "المنتج"))
        item = self.plan_items_table.horizontalHeaderItem(3)
        item.setText(_translate("SimplePlan", "الأولوية"))
        item = self.plan_items_table.horizontalHeaderItem(4)
        item.setText(_translate("SimplePlan", "حذف"))
        self.label.setText(_translate("SimplePlan", "المنتج:"))
        self.label_2.setText(_translate("SimplePlan", "عدد القطع المطلوب:"))
        self.add_btn.setText(_translate("SimplePlan", "اضافة"))
        self.products_btn.setText(_translate("SimplePlan", "🔎"))
        self.calc_btn.setText(_translate("SimplePlan", "حساب النتيجة"))
        self.clear_btn.setText(_translate("SimplePlan", "حذف الكل"))
