# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Select_Language.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SelectLanguage(object):
    def setupUi(self, SelectLanguage):
        SelectLanguage.setObjectName("SelectLanguage")
        SelectLanguage.setWindowModality(QtCore.Qt.WindowModal)
        SelectLanguage.resize(264, 95)
        SelectLanguage.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.gridLayout = QtWidgets.QGridLayout(SelectLanguage)
        self.gridLayout.setObjectName("gridLayout")
        self.label_11 = QtWidgets.QLabel(SelectLanguage)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 6, 1, 1, 1)
        self.save_btn = QtWidgets.QPushButton(SelectLanguage)
        self.save_btn.setObjectName("save_btn")
        self.gridLayout.addWidget(self.save_btn, 6, 2, 1, 1)
        self.language_combobox = QtWidgets.QComboBox(SelectLanguage)
        self.language_combobox.setObjectName("language_combobox")
        self.gridLayout.addWidget(self.language_combobox, 0, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(SelectLanguage)
        self.label_10.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 1, 1, 1)

        self.retranslateUi(SelectLanguage)
        QtCore.QMetaObject.connectSlotsByName(SelectLanguage)

    def retranslateUi(self, SelectLanguage):
        _translate = QtCore.QCoreApplication.translate
        SelectLanguage.setWindowTitle(_translate("SelectLanguage", "تغيير كلمة المرور"))
        self.label_11.setText(_translate("SelectLanguage", "⚠️ قد تحتاج إلى إعادة التشغيل"))
        self.save_btn.setText(_translate("SelectLanguage", "حفظ"))
        self.label_10.setText(_translate("SelectLanguage", "اللغة الافتراضية:"))
