# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Synchronization_Settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Synchronization_Settings(object):
    def setupUi(self, Synchronization_Settings):
        Synchronization_Settings.setObjectName("Synchronization_Settings")
        Synchronization_Settings.resize(348, 327)
        Synchronization_Settings.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.gridLayout_3 = QtWidgets.QGridLayout(Synchronization_Settings)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox = QtWidgets.QGroupBox(Synchronization_Settings)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.material_pricing_method_combobox = QtWidgets.QComboBox(self.groupBox)
        self.material_pricing_method_combobox.setObjectName("material_pricing_method_combobox")
        self.gridLayout.addWidget(self.material_pricing_method_combobox, 0, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 4)
        spacerItem = QtWidgets.QSpacerItem(153, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 2, 0, 1, 1)
        self.save_btn = QtWidgets.QPushButton(Synchronization_Settings)
        self.save_btn.setObjectName("save_btn")
        self.gridLayout_3.addWidget(self.save_btn, 2, 2, 1, 1)
        self.expenses_groupbox = QtWidgets.QGroupBox(Synchronization_Settings)
        self.expenses_groupbox.setEnabled(True)
        self.expenses_groupbox.setObjectName("expenses_groupbox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.expenses_groupbox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.expenses_type_combobox = QtWidgets.QComboBox(self.expenses_groupbox)
        self.expenses_type_combobox.setEnabled(True)
        self.expenses_type_combobox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.expenses_type_combobox.setObjectName("expenses_type_combobox")
        self.gridLayout_2.addWidget(self.expenses_type_combobox, 0, 0, 1, 1)
        self.no_expenses_radio = QtWidgets.QRadioButton(self.expenses_groupbox)
        self.no_expenses_radio.setEnabled(True)
        self.no_expenses_radio.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.no_expenses_radio.setChecked(True)
        self.no_expenses_radio.setObjectName("no_expenses_radio")
        self.gridLayout_2.addWidget(self.no_expenses_radio, 1, 0, 1, 1)
        self.quantity_expenses_radio = QtWidgets.QRadioButton(self.expenses_groupbox)
        self.quantity_expenses_radio.setEnabled(True)
        self.quantity_expenses_radio.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.quantity_expenses_radio.setObjectName("quantity_expenses_radio")
        self.gridLayout_2.addWidget(self.quantity_expenses_radio, 2, 0, 1, 1)
        self.radio_quantity_unit_expenses_combobox = QtWidgets.QComboBox(self.expenses_groupbox)
        self.radio_quantity_unit_expenses_combobox.setEnabled(True)
        self.radio_quantity_unit_expenses_combobox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radio_quantity_unit_expenses_combobox.setObjectName("radio_quantity_unit_expenses_combobox")
        self.gridLayout_2.addWidget(self.radio_quantity_unit_expenses_combobox, 3, 0, 1, 1)
        self.hours_expenses_radio = QtWidgets.QRadioButton(self.expenses_groupbox)
        self.hours_expenses_radio.setEnabled(True)
        self.hours_expenses_radio.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.hours_expenses_radio.setObjectName("hours_expenses_radio")
        self.gridLayout_2.addWidget(self.hours_expenses_radio, 4, 0, 1, 1)
        self.gridLayout_3.addWidget(self.expenses_groupbox, 1, 0, 1, 4)
        self.cancel_btn = QtWidgets.QPushButton(Synchronization_Settings)
        self.cancel_btn.setObjectName("cancel_btn")
        self.gridLayout_3.addWidget(self.cancel_btn, 2, 1, 1, 1)

        self.retranslateUi(Synchronization_Settings)
        QtCore.QMetaObject.connectSlotsByName(Synchronization_Settings)

    def retranslateUi(self, Synchronization_Settings):
        _translate = QtCore.QCoreApplication.translate
        Synchronization_Settings.setWindowTitle(_translate("Synchronization_Settings", "افتراضيات المزامنة"))
        self.groupBox.setTitle(_translate("Synchronization_Settings", "التسعير"))
        self.label_16.setText(_translate("Synchronization_Settings", "طريقة تسعير المواد الأولية:"))
        self.save_btn.setText(_translate("Synchronization_Settings", "حفظ"))
        self.expenses_groupbox.setTitle(_translate("Synchronization_Settings", ":توزيع مصاريف التصنيع حسب"))
        self.no_expenses_radio.setText(_translate("Synchronization_Settings", "بدون مصاريف"))
        self.quantity_expenses_radio.setText(_translate("Synchronization_Settings", "الكمية"))
        self.hours_expenses_radio.setText(_translate("Synchronization_Settings", "ساعات العمل"))
        self.cancel_btn.setText(_translate("Synchronization_Settings", "رجوع"))
