# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_SelectFinalFinancialStatement.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SelectFinalFinancialStatement(object):
    def setupUi(self, SelectFinalFinancialStatement):
        SelectFinalFinancialStatement.setObjectName("SelectFinalFinancialStatement")
        SelectFinalFinancialStatement.resize(645, 503)
        SelectFinalFinancialStatement.setMinimumSize(QtCore.QSize(645, 503))
        SelectFinalFinancialStatement.setMaximumSize(QtCore.QSize(645, 503))
        self.groupBox = QtWidgets.QGroupBox(SelectFinalFinancialStatement)
        self.groupBox.setGeometry(QtCore.QRect(11, 11, 621, 68))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 68))
        self.groupBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.financial_statement_name_input = QtWidgets.QLineEdit(self.groupBox)
        self.financial_statement_name_input.setObjectName("financial_statement_name_input")
        self.gridLayout.addWidget(self.financial_statement_name_input, 0, 1, 1, 1)
        self.search_financial_statement_btn = QtWidgets.QPushButton(self.groupBox)
        self.search_financial_statement_btn.setObjectName("search_financial_statement_btn")
        self.gridLayout.addWidget(self.search_financial_statement_btn, 0, 2, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(SelectFinalFinancialStatement)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 90, 624, 403))
        self.groupBox_2.setMinimumSize(QtCore.QSize(624, 400))
        self.groupBox_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.financial_statement_table = QtWidgets.QTableWidget(self.groupBox_2)
        self.financial_statement_table.setObjectName("financial_statement_table")
        self.financial_statement_table.setColumnCount(2)
        self.financial_statement_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.financial_statement_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.financial_statement_table.setHorizontalHeaderItem(1, item)
        self.gridLayout_2.addWidget(self.financial_statement_table, 0, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(439, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        self.cancel_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.cancel_btn.setObjectName("cancel_btn")
        self.gridLayout_2.addWidget(self.cancel_btn, 1, 1, 1, 1)
        self.save_final_financial_statement_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.save_final_financial_statement_btn.setObjectName("save_final_financial_statement_btn")
        self.gridLayout_2.addWidget(self.save_final_financial_statement_btn, 1, 2, 1, 1)

        self.retranslateUi(SelectFinalFinancialStatement)
        QtCore.QMetaObject.connectSlotsByName(SelectFinalFinancialStatement)

    def retranslateUi(self, SelectFinalFinancialStatement):
        _translate = QtCore.QCoreApplication.translate
        SelectFinalFinancialStatement.setWindowTitle(_translate("SelectFinalFinancialStatement", "اختيار قائمة مالية ختامية"))
        self.groupBox.setTitle(_translate("SelectFinalFinancialStatement", "البحث عن قائمة مالية"))
        self.search_financial_statement_btn.setText(_translate("SelectFinalFinancialStatement", "بحث"))
        self.groupBox_2.setTitle(_translate("SelectFinalFinancialStatement", "اختيار قائمة مالية ختامية"))
        item = self.financial_statement_table.horizontalHeaderItem(0)
        item.setText(_translate("SelectFinalFinancialStatement", "المعرف"))
        item = self.financial_statement_table.horizontalHeaderItem(1)
        item.setText(_translate("SelectFinalFinancialStatement", "الاسم"))
        self.cancel_btn.setText(_translate("SelectFinalFinancialStatement", "الغاء"))
        self.save_final_financial_statement_btn.setText(_translate("SelectFinalFinancialStatement", "حفظ"))
