# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_ShortCutSettings.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ShortCutSettings(object):
    def setupUi(self, ShortCutSettings):
        ShortCutSettings.setObjectName("ShortCutSettings")
        ShortCutSettings.resize(500, 300)
        ShortCutSettings.setMinimumSize(QtCore.QSize(500, 300))
        ShortCutSettings.setMaximumSize(QtCore.QSize(500, 300))
        ShortCutSettings.setLayoutDirection(QtCore.Qt.RightToLeft)
        ShortCutSettings.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(ShortCutSettings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(ShortCutSettings)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 480, 251))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.right_column = QtWidgets.QVBoxLayout()
        self.right_column.setObjectName("right_column")
        self.horizontalLayout.addLayout(self.right_column)
        self.left_column = QtWidgets.QVBoxLayout()
        self.left_column.setObjectName("left_column")
        self.horizontalLayout.addLayout(self.left_column)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.save_btn = QtWidgets.QPushButton(ShortCutSettings)
        self.save_btn.setObjectName("save_btn")
        self.verticalLayout.addWidget(self.save_btn)

        self.retranslateUi(ShortCutSettings)
        QtCore.QMetaObject.connectSlotsByName(ShortCutSettings)

    def retranslateUi(self, ShortCutSettings):
        _translate = QtCore.QCoreApplication.translate
        ShortCutSettings.setWindowTitle(_translate("ShortCutSettings", "إعدادات الاختصارات"))
        self.save_btn.setText(_translate("ShortCutSettings", "حفظ"))
