# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Salary_Report.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Salary_Report(object):
    def setupUi(self, Salary_Report):
        Salary_Report.setObjectName("Salary_Report")
        Salary_Report.setWindowModality(QtCore.Qt.WindowModal)
        Salary_Report.resize(952, 521)
        Salary_Report.setMinimumSize(QtCore.QSize(0, 400))
        Salary_Report.setLayoutDirection(QtCore.Qt.RightToLeft)
        Salary_Report.setModal(True)
        self.gridLayout_2 = QtWidgets.QGridLayout(Salary_Report)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_3 = QtWidgets.QGroupBox(Salary_Report)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox.setStyleSheet("")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)
        self.salary_cycle_combobox = QtWidgets.QComboBox(self.groupBox)
        self.salary_cycle_combobox.setObjectName("salary_cycle_combobox")
        self.gridLayout_3.addWidget(self.salary_cycle_combobox, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 2, 1, 1)
        self.position_combobox = QtWidgets.QComboBox(self.groupBox)
        self.position_combobox.setEnabled(False)
        self.position_combobox.setStyleSheet("QComboBox {\n"
"        background-color: #fafafa;\n"
"        border: 1px solid lightgrey;        \n"
"        height: 22px;\n"
"        color: black;\n"
"    }\n"
"    QComboBox::drop-down {\n"
"        border: none;\n"
"    }")
        self.position_combobox.setObjectName("position_combobox")
        self.gridLayout_3.addWidget(self.position_combobox, 0, 3, 1, 1)
        self.select_position_btn = QtWidgets.QToolButton(self.groupBox)
        self.select_position_btn.setObjectName("select_position_btn")
        self.gridLayout_3.addWidget(self.select_position_btn, 0, 4, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 5, 1, 1)
        self.department_combobox = QtWidgets.QComboBox(self.groupBox)
        self.department_combobox.setEnabled(False)
        self.department_combobox.setStyleSheet("QComboBox {\n"
"        background-color: #fafafa;\n"
"        border: 1px solid lightgrey;        \n"
"        height: 22px;\n"
"        color: black;\n"
"    }\n"
"    QComboBox::drop-down {\n"
"        border: none;\n"
"    }")
        self.department_combobox.setObjectName("department_combobox")
        self.gridLayout_3.addWidget(self.department_combobox, 0, 6, 1, 1)
        self.select_department_btn = QtWidgets.QToolButton(self.groupBox)
        self.select_department_btn.setObjectName("select_department_btn")
        self.gridLayout_3.addWidget(self.select_department_btn, 0, 7, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 8, 1, 1)
        self.from_date_input = QtWidgets.QDateEdit(self.groupBox)
        self.from_date_input.setObjectName("from_date_input")
        self.gridLayout_3.addWidget(self.from_date_input, 0, 9, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.groupBox)
        self.label_51.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_51.setObjectName("label_51")
        self.gridLayout_3.addWidget(self.label_51, 0, 10, 1, 1)
        self.to_date_input = QtWidgets.QDateEdit(self.groupBox)
        self.to_date_input.setObjectName("to_date_input")
        self.gridLayout_3.addWidget(self.to_date_input, 0, 11, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 12, 1, 1)
        self.currency_combobox = QtWidgets.QComboBox(self.groupBox)
        self.currency_combobox.setObjectName("currency_combobox")
        self.gridLayout_3.addWidget(self.currency_combobox, 0, 13, 1, 1)
        self.calculate_btn = QtWidgets.QPushButton(self.groupBox)
        self.calculate_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.calculate_btn.setObjectName("calculate_btn")
        self.gridLayout_3.addWidget(self.calculate_btn, 0, 14, 1, 1)
        self.label_81 = QtWidgets.QLabel(self.groupBox)
        self.label_81.setGeometry(QtCore.QRect(10, 13, 16, 16))
        self.label_81.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_81.setText("")
        self.label_81.setObjectName("label_81")
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.results_table = QtWidgets.QTableWidget(self.groupBox_3)
        self.results_table.setObjectName("results_table")
        self.results_table.setColumnCount(6)
        self.results_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.results_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.results_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.results_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.results_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.results_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.results_table.setHorizontalHeaderItem(5, item)
        self.results_table.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.results_table, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_3, 0, 0, 1, 1)

        self.retranslateUi(Salary_Report)
        QtCore.QMetaObject.connectSlotsByName(Salary_Report)

    def retranslateUi(self, Salary_Report):
        _translate = QtCore.QCoreApplication.translate
        Salary_Report.setWindowTitle(_translate("Salary_Report", "تقرير الراتب"))
        self.label_8.setText(_translate("Salary_Report", "دورة الراتب:"))
        self.label_7.setText(_translate("Salary_Report", "المسمى الوظيفي:"))
        self.select_position_btn.setText(_translate("Salary_Report", "🔎"))
        self.label_9.setText(_translate("Salary_Report", "القسم:"))
        self.select_department_btn.setText(_translate("Salary_Report", "🔎"))
        self.label_5.setText(_translate("Salary_Report", "من:"))
        self.label_51.setText(_translate("Salary_Report", "الى:"))
        self.label_4.setText(_translate("Salary_Report", "العملة:"))
        self.calculate_btn.setText(_translate("Salary_Report", "حساب"))
        item = self.results_table.horizontalHeaderItem(0)
        item.setText(_translate("Salary_Report", "دورة الراتب"))
        item = self.results_table.horizontalHeaderItem(1)
        item.setText(_translate("Salary_Report", "الاجمالي"))
        item = self.results_table.horizontalHeaderItem(2)
        item.setText(_translate("Salary_Report", "العملة"))
        item = self.results_table.horizontalHeaderItem(3)
        item.setText(_translate("Salary_Report", "السلف"))
        item = self.results_table.horizontalHeaderItem(4)
        item.setText(_translate("Salary_Report", "الخصومات"))
        item = self.results_table.horizontalHeaderItem(5)
        item.setText(_translate("Salary_Report", "الاضافات"))
