# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_SalesReport.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SalesReport(object):
    def setupUi(self, SalesReport):
        SalesReport.setObjectName("SalesReport")
        SalesReport.setWindowModality(QtCore.Qt.WindowModal)
        SalesReport.resize(1327, 773)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("graphics/icon.xpm"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SalesReport.setWindowIcon(icon)
        SalesReport.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(SalesReport)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(SalesReport)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.groupBox_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.sales_table = QtWidgets.QTableWidget(self.groupBox_3)
        self.sales_table.setObjectName("sales_table")
        self.sales_table.setColumnCount(4)
        self.sales_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sales_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sales_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sales_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.sales_table.setHorizontalHeaderItem(3, item)
        self.sales_table.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_3.addWidget(self.sales_table, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 1, 0, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(SalesReport)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.currency_combobox = QtWidgets.QComboBox(self.groupBox)
        self.currency_combobox.setObjectName("currency_combobox")
        self.gridLayout_2.addWidget(self.currency_combobox, 0, 13, 1, 1)
        self.buy_manufacture_date = QtWidgets.QDateEdit(self.groupBox)
        self.buy_manufacture_date.setObjectName("buy_manufacture_date")
        self.gridLayout_2.addWidget(self.buy_manufacture_date, 0, 11, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 0, 12, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 8, 1, 1)
        self.materials_combobox = QtWidgets.QComboBox(self.groupBox)
        self.materials_combobox.setMinimumSize(QtCore.QSize(125, 0))
        self.materials_combobox.setStyleSheet("QComboBox {\n"
"        background-color: #fafafa;\n"
"        border: 1px solid lightgrey;        \n"
"        height: 22px;\n"
"        color: black;\n"
"    }\n"
"    QComboBox::drop-down {\n"
"        border: none;\n"
"    }")
        self.materials_combobox.setObjectName("materials_combobox")
        self.gridLayout_2.addWidget(self.materials_combobox, 0, 1, 1, 1)
        self.select_material_btn = QtWidgets.QToolButton(self.groupBox)
        self.select_material_btn.setObjectName("select_material_btn")
        self.gridLayout_2.addWidget(self.select_material_btn, 0, 2, 1, 1)
        self.to_date_input = QtWidgets.QDateEdit(self.groupBox)
        self.to_date_input.setObjectName("to_date_input")
        self.gridLayout_2.addWidget(self.to_date_input, 0, 9, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 6, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.clients_combobox = QtWidgets.QComboBox(self.groupBox)
        self.clients_combobox.setEnabled(False)
        self.clients_combobox.setMinimumSize(QtCore.QSize(150, 0))
        self.clients_combobox.setStyleSheet("QComboBox {\n"
"        background-color: #fafafa;\n"
"        border: 1px solid lightgrey;        \n"
"        height: 22px;\n"
"        color: black;\n"
"    }\n"
"    QComboBox::drop-down {\n"
"        border: none;\n"
"    }")
        self.clients_combobox.setObjectName("clients_combobox")
        self.gridLayout_2.addWidget(self.clients_combobox, 0, 4, 1, 1)
        self.calc_btn = QtWidgets.QPushButton(self.groupBox)
        self.calc_btn.setObjectName("calc_btn")
        self.gridLayout_2.addWidget(self.calc_btn, 0, 14, 1, 1)
        self.from_date_input = QtWidgets.QDateEdit(self.groupBox)
        self.from_date_input.setObjectName("from_date_input")
        self.gridLayout_2.addWidget(self.from_date_input, 0, 7, 1, 1)
        self.select_client_btn = QtWidgets.QToolButton(self.groupBox)
        self.select_client_btn.setObjectName("select_client_btn")
        self.gridLayout_2.addWidget(self.select_client_btn, 0, 5, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 10, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 15, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 2)

        self.retranslateUi(SalesReport)
        QtCore.QMetaObject.connectSlotsByName(SalesReport)

    def retranslateUi(self, SalesReport):
        _translate = QtCore.QCoreApplication.translate
        SalesReport.setWindowTitle(_translate("SalesReport", "تقرير مبيع"))
        item = self.sales_table.horizontalHeaderItem(0)
        item.setText(_translate("SalesReport", "المعرف"))
        item = self.sales_table.horizontalHeaderItem(1)
        item.setText(_translate("SalesReport", "المادة"))
        item = self.sales_table.horizontalHeaderItem(2)
        item.setText(_translate("SalesReport", "الكود"))
        item = self.sales_table.horizontalHeaderItem(3)
        item.setText(_translate("SalesReport", "الربح"))
        self.groupBox.setTitle(_translate("SalesReport", "تقرير مادة"))
        self.label_12.setText(_translate("SalesReport", "العملة:"))
        self.label_10.setText(_translate("SalesReport", "الزبون:"))
        self.label_3.setText(_translate("SalesReport", "إلى تاريخ:"))
        self.select_material_btn.setText(_translate("SalesReport", "🔎"))
        self.label_2.setText(_translate("SalesReport", "من تاريخ:"))
        self.label.setText(_translate("SalesReport", "المادة:"))
        self.calc_btn.setText(_translate("SalesReport", "عرض"))
        self.select_client_btn.setText(_translate("SalesReport", "🔎"))
        self.label_9.setText(_translate("SalesReport", "تاريخ التصنيع/الشراء:"))
