# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_SalesCostReport.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SalesCostReport(object):
    def setupUi(self, SalesCostReport):
        SalesCostReport.setObjectName("SalesCostReport")
        SalesCostReport.setWindowModality(QtCore.Qt.WindowModal)
        SalesCostReport.resize(761, 467)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("graphics/icon.xpm"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SalesCostReport.setWindowIcon(icon)
        SalesCostReport.setModal(True)
        self.gridLayout_2 = QtWidgets.QGridLayout(SalesCostReport)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.chart_groupbox = QtWidgets.QGroupBox(SalesCostReport)
        self.chart_groupbox.setTitle("")
        self.chart_groupbox.setObjectName("chart_groupbox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.chart_groupbox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2.addWidget(self.chart_groupbox, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(SalesCostReport)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 60))
        self.groupBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 6, 1, 1)
        self.calculate_btn = QtWidgets.QPushButton(self.groupBox)
        self.calculate_btn.setObjectName("calculate_btn")
        self.gridLayout.addWidget(self.calculate_btn, 0, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.filter_combobox = QtWidgets.QComboBox(self.groupBox)
        self.filter_combobox.setObjectName("filter_combobox")
        self.gridLayout.addWidget(self.filter_combobox, 0, 4, 1, 1)
        self.select_product_btn = QtWidgets.QToolButton(self.groupBox)
        self.select_product_btn.setObjectName("select_product_btn")
        self.gridLayout.addWidget(self.select_product_btn, 0, 2, 1, 1)
        self.product_combobox = QtWidgets.QComboBox(self.groupBox)
        self.product_combobox.setEnabled(False)
        self.product_combobox.setMinimumSize(QtCore.QSize(125, 0))
        self.product_combobox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.product_combobox.setStyleSheet("QComboBox {\n"
"        background-color: #fafafa;\n"
"        border: 1px solid lightgrey;        \n"
"        height: 22px;\n"
"        color: black;\n"
"    }\n"
"    QComboBox::drop-down {\n"
"        border: none;\n"
"    }")
        self.product_combobox.setDuplicatesEnabled(True)
        self.product_combobox.setObjectName("product_combobox")
        self.gridLayout.addWidget(self.product_combobox, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(SalesCostReport)
        QtCore.QMetaObject.connectSlotsByName(SalesCostReport)

    def retranslateUi(self, SalesCostReport):
        _translate = QtCore.QCoreApplication.translate
        SalesCostReport.setWindowTitle(_translate("SalesCostReport", "تكاليف المبيعات مع الوقت"))
        self.calculate_btn.setText(_translate("SalesCostReport", "حساب النتيجة"))
        self.label.setText(_translate("SalesCostReport", "المنتج:"))
        self.select_product_btn.setText(_translate("SalesCostReport", "🔎"))
        self.label_2.setText(_translate("SalesCostReport", "حسب:"))
