# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_SellPricesReport.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SellPricesReport(object):
    def setupUi(self, SellPricesReport):
        SellPricesReport.setObjectName("SellPricesReport")
        SellPricesReport.setWindowModality(QtCore.Qt.WindowModal)
        SellPricesReport.resize(1481, 798)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("graphics/icon.xpm"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SellPricesReport.setWindowIcon(icon)
        SellPricesReport.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(SellPricesReport)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(SellPricesReport)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 70))
        self.groupBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.show_btn = QtWidgets.QPushButton(self.groupBox)
        self.show_btn.setObjectName("show_btn")
        self.gridLayout_2.addWidget(self.show_btn, 0, 2, 1, 1)
        self.chart_combobox = QtWidgets.QComboBox(self.groupBox)
        self.chart_combobox.setStyleSheet("QComboBox {\n"
"        background-color: #fafafa;\n"
"        border: 1px solid lightgrey;        \n"
"        height: 22px;\n"
"        color: black;\n"
"    }\n"
"    QComboBox::drop-down {\n"
"        border: none;\n"
"    }")
        self.chart_combobox.setObjectName("chart_combobox")
        self.gridLayout_2.addWidget(self.chart_combobox, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 3, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.chart_groupbox = QtWidgets.QGroupBox(SellPricesReport)
        self.chart_groupbox.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.chart_groupbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chart_groupbox.setTitle("")
        self.chart_groupbox.setObjectName("chart_groupbox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.chart_groupbox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout.addWidget(self.chart_groupbox, 1, 0, 1, 1)

        self.retranslateUi(SellPricesReport)
        QtCore.QMetaObject.connectSlotsByName(SellPricesReport)

    def retranslateUi(self, SellPricesReport):
        _translate = QtCore.QCoreApplication.translate
        SellPricesReport.setWindowTitle(_translate("SellPricesReport", "تقرير حركة مادة"))
        self.label.setText(_translate("SellPricesReport", "المخطط:"))
        self.show_btn.setText(_translate("SellPricesReport", "عرض"))
