# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Users.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Users(object):
    def setupUi(self, Users):
        Users.setObjectName("Users")
        Users.resize(746, 499)
        self.gridLayout_5 = QtWidgets.QGridLayout(Users)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_2 = QtWidgets.QGroupBox(Users)
        self.groupBox_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.users_table = QtWidgets.QTableWidget(self.groupBox_2)
        self.users_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.users_table.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.users_table.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.users_table.setObjectName("users_table")
        self.users_table.setColumnCount(2)
        self.users_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.users_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.users_table.setHorizontalHeaderItem(1, item)
        self.users_table.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.users_table, 0, 0, 1, 4)
        self.add_user_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.add_user_btn.setObjectName("add_user_btn")
        self.gridLayout.addWidget(self.add_user_btn, 1, 0, 1, 1)
        self.reset_password_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.reset_password_btn.setObjectName("reset_password_btn")
        self.gridLayout.addWidget(self.reset_password_btn, 1, 1, 1, 1)
        self.remove_user_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.remove_user_btn.setObjectName("remove_user_btn")
        self.gridLayout.addWidget(self.remove_user_btn, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(388, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 3, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_2, 1, 0, 1, 2)

        self.retranslateUi(Users)
        QtCore.QMetaObject.connectSlotsByName(Users)

    def retranslateUi(self, Users):
        _translate = QtCore.QCoreApplication.translate
        Users.setWindowTitle(_translate("Users", "مستخدمون"))
        self.groupBox_2.setTitle(_translate("Users", "سماحيات المستخدم"))
        item = self.users_table.horizontalHeaderItem(0)
        item.setText(_translate("Users", "معرف المستخدم"))
        item = self.users_table.horizontalHeaderItem(1)
        item.setText(_translate("Users", "المستخدم"))
        self.add_user_btn.setText(_translate("Users", "إضافة مستخدم"))
        self.reset_password_btn.setText(_translate("Users", "تغيير كلمة المرور"))
        self.remove_user_btn.setText(_translate("Users", "حذف"))
