# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_WarehouseMovement.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WarehouseMovement(object):
    def setupUi(self, WarehouseMovement):
        WarehouseMovement.setObjectName("WarehouseMovement")
        WarehouseMovement.setWindowModality(QtCore.Qt.WindowModal)
        WarehouseMovement.resize(1085, 444)
        WarehouseMovement.setMinimumSize(QtCore.QSize(0, 400))
        WarehouseMovement.setLayoutDirection(QtCore.Qt.RightToLeft)
        WarehouseMovement.setModal(True)
        self.gridLayout_7 = QtWidgets.QGridLayout(WarehouseMovement)
        self.gridLayout_7.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox_3 = QtWidgets.QGroupBox(WarehouseMovement)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 120))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 120))
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 68, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 0, 1, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_8.setStyleSheet("QComboBox {\n"
"        background-color: #fafafa;\n"
"        border: 1px solid lightgrey;        \n"
"        height: 22px;\n"
"        color: black;\n"
"    }\n"
"    QComboBox::drop-down {\n"
"        border: none;\n"
"    }")
        self.groupBox_8.setTitle("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.select_warehouse_btn = QtWidgets.QPushButton(self.groupBox_8)
        self.select_warehouse_btn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.select_warehouse_btn.setObjectName("select_warehouse_btn")
        self.gridLayout_2.addWidget(self.select_warehouse_btn, 0, 0, 1, 1)
        self.warehouse_combobox = QtWidgets.QComboBox(self.groupBox_8)
        self.warehouse_combobox.setObjectName("warehouse_combobox")
        self.gridLayout_2.addWidget(self.warehouse_combobox, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_8)
        self.label_3.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_8)
        self.label_5.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 2, 1, 1)
        self.to_date_input = QtWidgets.QDateEdit(self.groupBox_8)
        self.to_date_input.setObjectName("to_date_input")
        self.gridLayout_2.addWidget(self.to_date_input, 1, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_8, 0, 2, 2, 1)
        spacerItem1 = QtWidgets.QSpacerItem(732, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 0, 1, 1)
        self.calculate_btn = QtWidgets.QPushButton(self.groupBox)
        self.calculate_btn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.calculate_btn.setObjectName("calculate_btn")
        self.gridLayout_3.addWidget(self.calculate_btn, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.results_table = QtWidgets.QTableWidget(self.groupBox_3)
        self.results_table.setObjectName("results_table")
        self.results_table.setColumnCount(4)
        self.results_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.results_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.results_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.results_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.results_table.setHorizontalHeaderItem(3, item)
        self.gridLayout.addWidget(self.results_table, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_3, 1, 0, 1, 1)

        self.retranslateUi(WarehouseMovement)
        QtCore.QMetaObject.connectSlotsByName(WarehouseMovement)

    def retranslateUi(self, WarehouseMovement):
        _translate = QtCore.QCoreApplication.translate
        WarehouseMovement.setWindowTitle(_translate("WarehouseMovement", "الحسابات الختامية"))
        self.select_warehouse_btn.setText(_translate("WarehouseMovement", "...اختيار"))
        self.label_3.setText(_translate("WarehouseMovement", "المستودع:"))
        self.label_5.setText(_translate("WarehouseMovement", "إلى تاريخ:"))
        self.calculate_btn.setText(_translate("WarehouseMovement", "حساب"))
        item = self.results_table.horizontalHeaderItem(0)
        item.setText(_translate("WarehouseMovement", "معرف المادة"))
        item = self.results_table.horizontalHeaderItem(1)
        item.setText(_translate("WarehouseMovement", "المادة"))
        item = self.results_table.horizontalHeaderItem(2)
        item.setText(_translate("WarehouseMovement", "الكمية"))
        item = self.results_table.horizontalHeaderItem(3)
        item.setText(_translate("WarehouseMovement", "الواحدة"))
