# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_WarehouseVariables.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WarehouseVariables(object):
    def setupUi(self, WarehouseVariables):
        WarehouseVariables.setObjectName("WarehouseVariables")
        WarehouseVariables.resize(303, 145)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("graphics/icon.xpm"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        WarehouseVariables.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(WarehouseVariables)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtWidgets.QLineEdit(WarehouseVariables)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(WarehouseVariables)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(WarehouseVariables)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 1, 1, 1)

        self.retranslateUi(WarehouseVariables)
        QtCore.QMetaObject.connectSlotsByName(WarehouseVariables)

    def retranslateUi(self, WarehouseVariables):
        _translate = QtCore.QCoreApplication.translate
        WarehouseVariables.setWindowTitle(_translate("WarehouseVariables", "ضبط متغيرات المستودعات"))
        self.label.setText(_translate("WarehouseVariables", "رمز المواد الأولية:"))
        self.pushButton.setText(_translate("WarehouseVariables", "حفظ"))
